### ISSUE TITLE
ParticleContainerOutput - discussion

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#100]
In multiple occasions I needed some sort of "temporary"  container for detected particles that I could use directly through python like an iterator. For testing purposes or simple scenarios, I would like to avoid creating TextOutput or any other permanent storage and importing the data back again to the program.

Usage would be like all other output modules:
```python
obs = Observer()
obs.add(ObserverPoint())
container = ParticleContainerOutput(Output.Event1D)
obs.onDetection(container)
sim.add(obs)
```
while iterating it would return saved candidates:
```
for c in container:
    print c.getTrajectoryLength()
```

Although I am aware of the fact that this is not practical for full-blown simulations, and everything will be saved to memory (approx. 1M candidates would take ~500MB of RAM), I still think it would be useful, especially for Jupyter notebooks.

I already did the implementation, but having trouble with smart pointers...

Header:
```c++
#include <vector>
#include "crpropa/module/Output.h"

namespace crpropa {

/**
 @class ParticleContainerOutput
 @brief A helper ouput mechanism to directly transfer candidates to Python
 */
class ParticleContainerOutput: public Output {
protected:
        typedef std::vector<ref_ptr<Candidate>> tContainer;
        mutable tContainer container;
        std::size_t max_size;

public:
        ParticleContainerOutput(OutputType outputtype, std::size_t max_size = 1e6);
        ~ParticleContainerOutput();

        void process(Candidate *candidate) const;
        std::size_t numberOfCandidates() const;
        void clearContainer();
        std::string getDescription() const;

        // iterator goodies
        typedef tContainer::iterator iterator;
        typedef tContainer::const_iterator const_iterator;
        iterator begin();
        const_iterator begin() const;
        iterator end();
        const_iterator end() const;
};

} // namespace crpropa
```

Source:
```c++
ParticleContainerOutput::ParticleContainerOutput(OutputType outputtype, std::size_t max_size) : Output(outputtype) {
        max_size = max_size;
        container.reserve(max_size); // max_size = 1e6 ~ 500MB RAM
}

void ParticleContainerOutput::process(Candidate* c) const {
#pragma omp critical
        {
                if (container.size() < max_size)
                        container.push_back(c->clone());
        }
}

(...)
```

...but this generally doesn't work due to sporadic null-pointers left inside the container which is probably the consequence of my misunderstanding of ``ref_ptr``.

**Comment by geromueller** [comment]
Hello,

- you do no need to inherit from Output, just Module.
- make the cloning optional?
- the process method should work, maybe the iterator has problems?

If you send me the sources, i could try to help you further.

Gero


Am Montag, 29. August 2016, 05:45:06 CEST schrieb Andrej Dundovic:
> In multiple occasions I needed some sort of "temporary"  container for
> detected particles that I could use directly through python like an
> iterator. For testing purposes or simple scenarios, I would like to avoid
> creating TextOutput or any other permanent storage and importing the data
> back again to the program.
> 
> Usage would be like all other output modules:
> ```python
> obs = Observer()
> obs.add(ObserverPoint())
> container = ParticleContainerOutput(Output.Event1D)
> obs.onDetection(container)
> sim.add(obs)
> ```
> while iterating it would return saved candidates:
> ```
> for c in container:
>     print c.getTrajectoryLength()
> ```
> 
> Although I am aware of the fact that this is not practical for full-blown
> simulations, and everything will be saved to memory (approx. 1M candidates
> would take ~500MB of RAM), I still think it would be useful, especially for
> Jupyter notebooks.
> 
> I already did the implementation, but having trouble with smart pointers...
> 
> Header:
> ```c++
> #include <vector>
> #include "crpropa/module/Output.h"
> 
> namespace crpropa {
> 
> /**
>  @class ParticleContainerOutput
>  @brief A helper ouput mechanism to directly transfer candidates to Python
>  */
> class ParticleContainerOutput: public Output {
> protected:
>         typedef std::vector<ref_ptr<Candidate>> tContainer;
>         mutable tContainer container;
>         std::size_t max_size;
> 
> public:
>         ParticleContainerOutput(OutputType outputtype, std::size_t max_size
> = 1e6); ~ParticleContainerOutput();
> 
>         void process(Candidate *candidate) const;
>         std::size_t numberOfCandidates() const;
>         void clearContainer();
>         std::string getDescription() const;
> 
>         // iterator goodies
>         typedef tContainer::iterator iterator;
>         typedef tContainer::const_iterator const_iterator;
>         iterator begin();
>         const_iterator begin() const;
>         iterator end();
>         const_iterator end() const;
> };
> 
> } // namespace crpropa
> ```
> 
> Source:
> ```c++
> ParticleContainerOutput::ParticleContainerOutput(OutputType outputtype,
> std::size_t max_size) : Output(outputtype) { max_size = max_size;
>         container.reserve(max_size); // max_size = 1e6 ~ 500MB RAM
> }
> 
> void ParticleContainerOutput::process(Candidate* c) const {
> #pragma omp critical
>         {
>                 if (container.size() < max_size)
>                         container.push_back(c->clone());
>         }
> }
> 
> (...)
> ```
> 
> ...but this generally doesn't work due to sporadic null-pointers left inside
> the container which is probably the consequence of my misunderstanding of
> ``ref_ptr``.

**Comment by adundovi** [comment]
Implemented in 536344c.

**Comment by geromueller** [comment]
could you rename it? It is not an Output, So simple ParticleContainer, or 
ParticlCollector or something like that would be more suitable.

Thanks
Gero

Am Dienstag, 30. August 2016, 23:01:35 CEST schrieb Andrej Dundovic:
> Implemented in 536344c.

**Comment by geromueller** [comment]
And, could you add options for cloning and recursive cloning?

Then it would be possible to use it in non recursive cloning mode as tracking 
collector.

Thanks

Am Mittwoch, 31. August 2016, 08:21:08 CEST schrieben Sie:
> could you rename it? It is not an Output, So simple ParticleContainer, or
> ParticlCollector or something like that would be more suitable.
> 
> Thanks
> Gero
> 
> Am Dienstag, 30. August 2016, 23:01:35 CEST schrieb Andrej Dundovic:
> > Implemented in 536344c.

**Comment by DavidWalz** [comment]
ParticleCollector sounds best to me.

**Comment by adundovi** [comment]
OK, I will rename it and add an option for cloning. I suppose that the most appropriate place would be to add it to constructor, right?

I picked the ...Output name to emphasise it should be used instead or like other Output modules, but ParticleCollector sounds good.

**Comment by adundovi** [comment]
Done.

**Comment by adundovi** [comment]
I've added dump() and load() methods. Dump() uses OutputText(Output.Everything) to store particles, but I've needed to implement a load method to load it back from the file. This gives a convenient way to load results back to a jupyter notebook and analyze them within the CRPropa framework which treats the data like well-known candidates and not a generic tabular data (like numpy does). This approach has some drawbacks (slower compared to numpy, inefficient as a storage), but it is really easy and transparent to use, for example in a case of prototyping.

Still, I have one question regarding the implementation: I would like to put the part of the load method inside OutputText class, but I'm not sure how to decouple it properly: should I pass the whole Collector instance to a new load method of OutputText which would fill it up or there is a smarter way?

Here is the current implementation: https://github.com/CRPropa/CRPropa3/blob/master/src/module/ParticleCollector.cpp#L61

**Comment by adundovi** [comment]
I've split the load method between TextOutput and ParticleCollector, thus TextOutput::load() contains all the details of loading the data from files (analogous to writing the data also present in it), while ParticleCollector only abstracts those mechanisms.
