### ISSUE TITLE
Problem downloading data file on the RWTH physics cluster

### ISSUE THREAD

**Issue by DavidWalz** [CRPropa/CRPropa3#101]
> file DOWNLOAD HASH mismatch
> ....
> status: [1;"Unsupported protocol"]

using /net/software_cms/vispa/sl6_local/cmake-3.3.0/bin/cmake

**Comment by adundovi** [comment]
This is probably a CMake issue or the way how it is locally compiled. CMake uses curl to download stuff -- does your curl support SSL? Why do we use SSL to download the data anyway? It is nice to do so, but not necessary in my opinion.

**Comment by DavidWalz** [comment]
Both, wget and curl are available, I don't know which one CMake is using. 
Changing the adress to http gives the same error.

You're probably right that its an issue with the local CMake install and not a CRPropa bug. Just wanted to get someone else's opinion.

**Comment by adundovi** [comment]
What was the issue at the end? :-)

**Comment by DavidWalz** [comment]
Unsolved :/

**Comment by adundovi** [comment]
I suppose that downloading the file manually with curl or wget is possible, right? If yes, everything narrows down to your cmake where you could use --trace, -Wdev or --debug-output to get verbose output to debug it (or even strace). At least I can confirm it works with versions 2.8.12 and 3.5.2.
