### ISSUE TITLE
DintPropagation: Energy too low -inf

### ISSUE THREAD

**Issue by avvliet** [CRPropa/CRPropa3#105]
DINT error when starting with iron, shows "DintPropagation: Energy too low -inf". Does not occur when starting with protons.

Might perhaps have something to do with positron/electron events with 0 energy, like these:
-11    0       2701.2417       1000240540        0.5057        1000260560        0.6219        3551.2108
11    0       3283.9744       1000130280        7.9643        1000260560       30.0610        3937.1775

Also occurs when photons are disabled during photodisintegration itself. So probably related to nuclear decay module. This does not occur when nuclear decay is switched off.

The steering card:
 ```python
from crpropa import *
import crpropa

photons = True

# module setup
EBL = IRB_Gilmore12
m = ModuleList()
m.add(SimplePropagation(1*kpc, 10*Mpc))
m.add(Redshift())
m.add(PhotoPionProduction(CMB, photons))
m.add(PhotoPionProduction(EBL, photons))
m.add(PhotoDisintegration(CMB))
m.add(PhotoDisintegration(EBL))
m.add(NuclearDecay(photons, photons))
m.add(ElectronPairProduction(CMB, photons))
m.add(ElectronPairProduction(EBL, photons))
m.add(PhotonOutput1D('photon-inputTest.txt'))

# observer
obs = Observer()
obs.add(ObserverPoint())
output = TextOutput('nucleons-Test.txt', Output.Event1D)
obs.onDetection( output )
m.add(obs)

# source
source = Source()
source.add(SourceUniform1D(0, redshift2ComovingDistance(6)))
source.add(SourceRedshift1D())
source.add(SourcePowerLawSpectrum(0.1 * EeV, 1000. * EeV, -1.0))
source.add(SourceParticleType(nucleusId(56, 26)))

# run simulation for 100 primaries
m.setShowProgress(True)
m.run(source, 100, True)

crpropa.DintPropagation('photon-inputTest.txt', 'photon-Test.txt', True, True, 0.)
```

**Comment by DavidWalz** [comment]
This is due to an inaccuracy in NuclearDecay
In beta-decays, when the energy of emitted gammas (unphysically) exceeds the Q-value of the decay, the resulting electron / positron energy could not be assigned.
For simplicity, and due to the small impact I'm taking out that the Q is reduced by the emitted photon energies.
