### ISSUE TITLE
Vector3 comparision operator does not work as described

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#111]
The comparison operator of the Vector3 does not work as advertised:

a = crpropa.Vector3d(1,2,3)
b = crpropa.Vector3d(2,0,0)
a < b
Out[4]: True
from the comment `False' is expected. 

However, I think we should remove this operator, as it is not obvious to me how the comparison of vectors should work. Here e.g. also b <= a is false, but logically implied by not a < b.

**Comment by adundovi** [comment]
I agree that the vector comparison is not a well defined operation: vectors are generally quantities which shouldn't depend on a choice of coordinate system and this comparison is defined by the choice of coordinate system, thus I'll remove it.

**Comment by adundovi** [comment]
It seems that SWIG is overriding this behaviour with its comparison method:
```c++
SWIGINTERN PyObject *
SwigPyBuiltin__crpropa__Vector3T_double_t_richcompare(PyObject *self, PyObject *other, int op) {
  PyObject *result = NULL;
  PyObject *tuple = PyTuple_New(1);
  assert(tuple);
  PyTuple_SET_ITEM(tuple, 0, other);
  Py_XINCREF(other);
  switch (op) {
    case Py_EQ : result = _wrap_Vector3d___eq__(self, tuple); break;
    default : break;
  }
  if (!result) {
    if (SwigPyObject_Check(self) && SwigPyObject_Check(other)) {
      result = SwigPyObject_richcompare((SwigPyObject *)self, (SwigPyObject *)other, op);
    } else {
      result = Py_NotImplemented;
      Py_INCREF(result);
    }
  }
  Py_DECREF(tuple);
  return result;
}
```
which ends up in comparing pointers (python __cmp__ method is redirected to SWIG SwigPyObject_compare). I don't know how to easily disable it - maybe by implementing __lt__ and __gr__ which would return Py_NotImplemented?
