### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#113]
Compilation error

 CMakeLists does not check for mpi, whose headers are required by HDF5. Therefore, it would be prudent to either check for mpi when running cmake, or disable the hdf5 output by default. I've done the latter manually and it fixes the problem.

```

In file included from /Data/Software/CRPropa3/src/module/HDF5Output.cpp:3:
In file included from /Data/Software/CRPropa3/include/crpropa/module/HDF5Output.h:9:
In file included from /opt/local/include/H5Ipublic.h:24:
/opt/local/include/H5public.h:61:13: fatal error: 'mpi.h' file not found
#  include <mpi.h>
            ^
/Data/Software/CRPropa3/src/module/OutputShell.cpp:48:8: warning: expression result unused [-Wunused-value]
                for (i; i != c->properties.end(); i++) {
                     ^
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputROOT.cpp.o
```

**Comment by adundovi** [comment]
Are you sure that HDF5 requires MPI? I've checked and it seems that this holds only for the parallel version of HDF5. Look here the difference: [parallel HDF5](https://support.hdfgroup.org/ftp/HDF5/current18/src/unpacked/release_docs/INSTALL_parallel) and [serial HDF5](https://support.hdfgroup.org/ftp/HDF5/current18/src/unpacked/release_docs/INSTALL). But I agree that we could note that somewhere...

**Comment by rafaelab** [comment]
I'm not sure MPI is required, but we should at least check for it in H5Ipublic.h. Just and #ifdef in the preprocessor would suffice.

**Comment by adundovi** [comment]
OK. I've added a line in CMakeLists.txt which forces serial versions of HDF5 - that should work.
