### ISSUE TITLE
How increase the number of digits in the ascii output?

### ISSUE THREAD

**Issue by CRPropaUser** [CRPropa/CRPropa3#115]
I simulate secondaries down to 10^10 eV, but the ascii output for E and E0 allows only a min. energy of 0.00001EeV=10^13 eV.
Smaller values are all 0.00000!
How can I increase the number of digits (for E and E0) in the ascii output (if it is possible, I don't want to install a new version of crpropa to avoid different results due to different crpropa versions)?

**Comment by TobiasWinchen** [comment]
The behavior is changed by commit 598238c in the current development version. For a higher precision in previous versions I can recommend to use HDF5 output.

**Comment by DavidWalz** [comment]
You can change the base unit in which energies and distances / coordinates are written out with
```python
out = TextOutput(...)
out.setEnergyScale(1E12 * eV)
out.setLengthScale(1 * kpc)
```
