### ISSUE TITLE
Vector3 interoperability with numpy / Switch to C++11

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#116]
To increase the interoperability with numpy, it would be great to implement the Array interface for the Vector3. This would allow to use numpy methods on Vector3 and in particular to e.g. add a Vctor3 to a numpy array. However, this requires the Vector3 to have the data in an array and not in separate variables x,y,z. The resulting major change to the interface can be avoided by switching to C++11 and have public references x,y,z, to the array data as in:
``
...
public:
  T data[3];
  T &x = data[0]; 
  T &y = data[1]; 
  T &z = data[2];
...
``

Any thoughts about moving to C++11 ?

**Comment by adundovi** [comment]
I mainly use it on CentOS 7 or newer machines which should support c++11 via gcc 4.8 ( https://access.redhat.com/solutions/19458 ), therefore the migration is fine with me, but I doubt that it is so with others, like those on Scientific Linux 6 or similar.

But I would also like c++11 goodies :-)

Maybe tagging 3.1 as the last pre-c++11 version could save some confusion?

On 17 February 2017 11:52:40 CET, Tobias Winchen <notifications@github.com> wrote:
>To increase the interoperability with numpy, it would be great to
>implement the Array interface for the Vector3. This would allow to use
>numpy methods on Vector3 and in particular to e.g. add a Vctor3 to a
>numpy array. However, this requires the Vector3 to have the data in an
>array and not in separate variables x,y,z. The resulting major change
>to the interface can be avoided by switching to C++11 and have public
>references x,y,z, to the array data as in:
>``
>...
>public:
>  T data[3];
>  T &x = data[0]; 
>  T &y = data[1]; 
>  T &z = data[2];
>...
>``
>
>Any thoughts about moving to C++11 ?
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CRPropa/CRPropa3/issues/116

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by TobiasWinchen** [comment]
C++ 11 may be required after 3.2 release

**Comment by adundovi** [comment]
It's been more than two years since this request, and certain requirements that we already discuss are now met or almost met. As RHEL 8 is released (comes with GCC-8 by default), and soon CentOS 8 will be, we can expect that cluster users of CRPropa (those which usually encounter the most "out-dated" software versions) will soon get the full C++11 support, thus, we can enable it in the master branch of CRPropa by default.

Besides that, I would really like some features of newer versions of C++ :-)

**Comment by adundovi** [comment]
Python 2 is reaching EOL soon ([counter](https://pythonclock.org)).
