### ISSUE TITLE
OpenMP Schedule prevents parallelization of few trajectories

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#117]
The OpenMP scheduler is set to parallelize the simulation in bunches of 1000 candidates. This prevents parallel processing in simulations with few long running particles. I didn't observe any performance issues when reducing the chunk size to 1 via ``#pragma omp parallel for schedule(static, 1)`` - is there any specific reason to have this at 1000?

**Comment by geromueller** [comment]
Hi!

when i developed this code, i had many short trajectories. In this case
this scheduler worked best. But, this is only the default, you can
change the scheduler with
  export OMP_SCHEDULE="dynamic"
see
http://docs.cray.com/books/S-2179-52/html-S-2179-52/z1050587246oswald.html
maybe dynamic is a good default?

Gero

**Comment by TobiasWinchen** [comment]
Hi,

On Friday 17 February 2017 03:20:05 Gero Müller wrote:
> when i developed this code, i had many short trajectories. In this case
> this scheduler worked best. But, this is only the default, you can
> change the scheduler with
>   export OMP_SCHEDULE="dynamic"
> see
> http://docs.cray.com/books/S-2179-52/html-S-2179-52/z1050587246oswald.html
> maybe dynamic is a good default?

The environment variable is only used when runtime schedule is selected in the 
pragma. Dynamic is probably a bad idea in case of many short trajectories due 
to the overhead. Did you try static with chunk size 1 when you did this first? 
I see no performance difference in case of simple 1D simulation, but my setup 
is not very sensitive. 

Cheers,


Tobi

**Comment by adundovi** [comment]
Isn't this fixed with #169 ?

**Comment by TobiasWinchen** [comment]
It is -
