### ISSUE TITLE
fatal error: mpi.h: No such file or directory

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#123]
While using make comand the output is

make 

/usr/bin/cmake -H/home/saikat/CRPropa3-3.1 -B/home/saikat/CRPropa3-3.1/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/saikat/CRPropa3-3.1/build/CMakeFiles /home/saikat/CRPropa3-3.1/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/healpix_base/CMakeFiles/healpix_base.dir/build.make libs/healpix_base/CMakeFiles/healpix_base.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/healpix_base /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/healpix_base /home/saikat/CRPropa3-3.1/build/libs/healpix_base/CMakeFiles/healpix_base.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/healpix_base/CMakeFiles/healpix_base.dir/build.make libs/healpix_base/CMakeFiles/healpix_base.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/healpix_base/CMakeFiles/healpix_base.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[  4%] Built target healpix_base
make -f libs/kiss/CMakeFiles/kiss.dir/build.make libs/kiss/CMakeFiles/kiss.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/kiss /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/kiss /home/saikat/CRPropa3-3.1/build/libs/kiss/CMakeFiles/kiss.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/kiss/CMakeFiles/kiss.dir/build.make libs/kiss/CMakeFiles/kiss.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/kiss/CMakeFiles/kiss.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[  8%] Built target kiss
make -f libs/pugixml/CMakeFiles/pugixml.dir/build.make libs/pugixml/CMakeFiles/pugixml.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/pugixml /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/pugixml /home/saikat/CRPropa3-3.1/build/libs/pugixml/CMakeFiles/pugixml.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/pugixml/CMakeFiles/pugixml.dir/build.make libs/pugixml/CMakeFiles/pugixml.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/pugixml/CMakeFiles/pugixml.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[  9%] Built target pugixml
make -f libs/HepPID/CMakeFiles/HepPID.dir/build.make libs/HepPID/CMakeFiles/HepPID.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/HepPID /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/HepPID /home/saikat/CRPropa3-3.1/build/libs/HepPID/CMakeFiles/HepPID.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/HepPID/CMakeFiles/HepPID.dir/build.make libs/HepPID/CMakeFiles/HepPID.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/HepPID/CMakeFiles/HepPID.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 17%] Built target HepPID
make -f libs/sophia/CMakeFiles/sophia.dir/build.make libs/sophia/CMakeFiles/sophia.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/sophia /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/sophia /home/saikat/CRPropa3-3.1/build/libs/sophia/CMakeFiles/sophia.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/sophia/CMakeFiles/sophia.dir/build.make libs/sophia/CMakeFiles/sophia.dir/requires
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/sophia/CMakeFiles/sophia.dir/requires'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/sophia/CMakeFiles/sophia.dir/build.make libs/sophia/CMakeFiles/sophia.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/sophia/CMakeFiles/sophia.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 18%] Built target sophia
make -f libs/dint/CMakeFiles/dint.dir/build.make libs/dint/CMakeFiles/dint.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/dint /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/dint /home/saikat/CRPropa3-3.1/build/libs/dint/CMakeFiles/dint.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/dint/CMakeFiles/dint.dir/build.make libs/dint/CMakeFiles/dint.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/dint/CMakeFiles/dint.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 34%] Built target dint
make -f libs/EleCa/CMakeFiles/eleca.dir/build.make libs/EleCa/CMakeFiles/eleca.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/EleCa /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/EleCa /home/saikat/CRPropa3-3.1/build/libs/EleCa/CMakeFiles/eleca.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/EleCa/CMakeFiles/eleca.dir/build.make libs/EleCa/CMakeFiles/eleca.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/EleCa/CMakeFiles/eleca.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 38%] Built target eleca
make -f CMakeFiles/crpropa.dir/build.make CMakeFiles/crpropa.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/CMakeFiles/crpropa.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f CMakeFiles/crpropa.dir/build.make CMakeFiles/crpropa.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
[ 38%] Building CXX object CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o
/usr/bin/c++   -DCRPROPA_HAVE_FFTW3F -DCRPROPA_HAVE_HDF5 -DCRPROPA_HAVE_MUPARSER -DCRPROPA_HAVE_QUIMBY -DCRPROPA_HAVE_ROOT -DCRPROPA_HAVE_ZLIB -DCRPROPA_INSTALL_PREFIX=\"/CP\" -Dcrpropa_EXPORTS -I/home/saikat/CRPropa3-3.1/libs/gtest/include -I/home/saikat/CRPropa3-3.1/include -I/home/saikat/CRPropa3-3.1/libs/kiss/include -I/home/saikat/CRPropa3-3.1/libs/pugixml -I/home/saikat/CRPropa3-3.1/libs/HepPID/include -I/home/saikat/CRPropa3-3.1/libs/sophia -I/home/saikat/CRPropa3-3.1/libs/dint/include -I/home/saikat/CRPropa3-3.1/libs/EleCa/include -I/home/saikat/CRPropa3-3.1/libs/eigen3 -I/home/saikat/CRPropa3-3.1/libs/healpix_base/include -I/fftw-3.3.5/include -I/usr/local/include -I/home/saikat/CRPropa3-3.1/libs/zstream-cpp -I/usr/include/hdf5/openmpi -I/usr/include/python2.7 -I/home/saikat/.local/lib/python2.7/site-packages/numpy/core/include  -pthread -m64 -I/usr/include/root -fopenmp -O3 -DNDEBUG -fPIC   -o CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o -c /home/saikat/CRPropa3-3.1/src/module/HDF5Output.cpp
In file included from /usr/include/hdf5/openmpi/H5Ipublic.h:24:0,
                 from /home/saikat/CRPropa3-3.1/include/crpropa/module/HDF5Output.h:9,
                 from /home/saikat/CRPropa3-3.1/src/module/HDF5Output.cpp:3:
/usr/include/hdf5/openmpi/H5public.h:61:20: fatal error: mpi.h: No such file or directory
compilation terminated.
CMakeFiles/crpropa.dir/build.make:809: recipe for target 'CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o' failed
make[2]: *** [CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o] Error 1
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
CMakeFiles/Makefile2:368: recipe for target 'CMakeFiles/crpropa.dir/all' failed
make[1]: *** [CMakeFiles/crpropa.dir/all] Error 2
make[1]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by adundovi** [comment]
It is probably related to bug #113. The parallel version of HDF5 should be skipped because it is not supported in CRPropa3. Try to disable HDF5 manually: `cmake .. -DENABLE_HDF5=Off` if you don't need it, or report here which cmake version you use with `cmake --version` so we can try to reproduce ourselves.

**Comment by saikat8018** [comment]
Thank you for the prompt reply. That is fixed. The cmake version I am using is 

cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by saikat8018** [comment]
But now I have a new error 

make

/usr/bin/cmake -H/home/saikat/CRPropa3-3.1 -B/home/saikat/CRPropa3-3.1/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/saikat/CRPropa3-3.1/build/CMakeFiles /home/saikat/CRPropa3-3.1/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/healpix_base/CMakeFiles/healpix_base.dir/build.make libs/healpix_base/CMakeFiles/healpix_base.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/healpix_base /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/healpix_base /home/saikat/CRPropa3-3.1/build/libs/healpix_base/CMakeFiles/healpix_base.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/healpix_base/CMakeFiles/healpix_base.dir/build.make libs/healpix_base/CMakeFiles/healpix_base.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/healpix_base/CMakeFiles/healpix_base.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[  4%] Built target healpix_base
make -f libs/kiss/CMakeFiles/kiss.dir/build.make libs/kiss/CMakeFiles/kiss.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/kiss /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/kiss /home/saikat/CRPropa3-3.1/build/libs/kiss/CMakeFiles/kiss.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/kiss/CMakeFiles/kiss.dir/build.make libs/kiss/CMakeFiles/kiss.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/kiss/CMakeFiles/kiss.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[  8%] Built target kiss
make -f libs/pugixml/CMakeFiles/pugixml.dir/build.make libs/pugixml/CMakeFiles/pugixml.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/pugixml /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/pugixml /home/saikat/CRPropa3-3.1/build/libs/pugixml/CMakeFiles/pugixml.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/pugixml/CMakeFiles/pugixml.dir/build.make libs/pugixml/CMakeFiles/pugixml.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/pugixml/CMakeFiles/pugixml.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[  9%] Built target pugixml
make -f libs/HepPID/CMakeFiles/HepPID.dir/build.make libs/HepPID/CMakeFiles/HepPID.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/HepPID /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/HepPID /home/saikat/CRPropa3-3.1/build/libs/HepPID/CMakeFiles/HepPID.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/HepPID/CMakeFiles/HepPID.dir/build.make libs/HepPID/CMakeFiles/HepPID.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/HepPID/CMakeFiles/HepPID.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 17%] Built target HepPID
make -f libs/sophia/CMakeFiles/sophia.dir/build.make libs/sophia/CMakeFiles/sophia.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/sophia /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/sophia /home/saikat/CRPropa3-3.1/build/libs/sophia/CMakeFiles/sophia.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/sophia/CMakeFiles/sophia.dir/build.make libs/sophia/CMakeFiles/sophia.dir/requires
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/sophia/CMakeFiles/sophia.dir/requires'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/sophia/CMakeFiles/sophia.dir/build.make libs/sophia/CMakeFiles/sophia.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/sophia/CMakeFiles/sophia.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 18%] Built target sophia
make -f libs/dint/CMakeFiles/dint.dir/build.make libs/dint/CMakeFiles/dint.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/dint /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/dint /home/saikat/CRPropa3-3.1/build/libs/dint/CMakeFiles/dint.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/dint/CMakeFiles/dint.dir/build.make libs/dint/CMakeFiles/dint.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/dint/CMakeFiles/dint.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 34%] Built target dint
make -f libs/EleCa/CMakeFiles/eleca.dir/build.make libs/EleCa/CMakeFiles/eleca.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/libs/EleCa /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/libs/EleCa /home/saikat/CRPropa3-3.1/build/libs/EleCa/CMakeFiles/eleca.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f libs/EleCa/CMakeFiles/eleca.dir/build.make libs/EleCa/CMakeFiles/eleca.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: Nothing to be done for 'libs/EleCa/CMakeFiles/eleca.dir/build'.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
[ 38%] Built target eleca
make -f CMakeFiles/crpropa.dir/build.make CMakeFiles/crpropa.dir/depend
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
cd /home/saikat/CRPropa3-3.1/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1 /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build /home/saikat/CRPropa3-3.1/build/CMakeFiles/crpropa.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
make -f CMakeFiles/crpropa.dir/build.make CMakeFiles/crpropa.dir/build
make[2]: Entering directory '/home/saikat/CRPropa3-3.1/build'
make[2]: *** No rule to make target '/fftw-3.3.5/lib/libfftw3f.a', needed by 'libcrpropa.so'.  Stop.
make[2]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
CMakeFiles/Makefile2:368: recipe for target 'CMakeFiles/crpropa.dir/all' failed
make[1]: *** [CMakeFiles/crpropa.dir/all] Error 2
make[1]: Leaving directory '/home/saikat/CRPropa3-3.1/build'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by adundovi** [comment]
You need to install FFTW independently, either through your system installer or manually by compiling it from the source. You could also disable it (`-DENABLE_FFTW3F=OFF`) but in that case you lose the ability to use turbulent fields.

I suggest that you follow "Recommended deployment" from [here](https://github.com/CRPropa/CRPropa3/wiki/Installation).

**Comment by saikat8018** [comment]
Thank you. The problem is solved
