### ISSUE TITLE
Apply Galactic Lenses

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#124]
For **Galactic lenses of Simulated cosmic rays** there is this plot for the case -  _applying magnetic lenses_. There it is given:

To apply a lens to a map, a lens object needs to be created and then applied to the map. The normalization of the lens ensures that the lens does not distort the spectra.

`lens = crpropa.MagneticLens('pathto/lens.cfg')`

Can anyone tell me how to get this "lens.cfg" file?

**Comment by adundovi** [comment]
Either you can generate it yourself using CRPropa or you can use already prepared lenses from [here](https://web.physik.rwth-aachen.de/Auger_MagneticFields/PARSEC/downloads.php) (e.g. download JF12full.tgz, unpack it and you will have all required files).

**Comment by tfitoussi** [comment]
Hello,

Can you explain how to generate a custom lens using CRPropa. I did not find any example.

Thank you.

Thomas

**Comment by lukasmerten** [comment]
Hi Thomas,
there is no easy plug-and-play way to generate custom lenses with CRPropa.
You still can set up a simulation to generate custom lenses. Have a look e.g. at the PARSEC code (https://arxiv.org/abs/1302.3761) on how this can be done in general.
Best, 
Lukas
