### ISSUE TITLE
Electron spectrum at low energies incorrect (betaDecay)?

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#126]
I've been told that there exists a discrepancy between electron and el. neutrino spectrum on low energies (below 1 PeV). The spectrum should be the same. The spectrum from other (private) codes also differs from CRPropa one. The bug is still not confirmed as I need to write a minimal example for it, but generally, the reporter said that the mistake should be somewhere in the beta decay module.

**Comment by rafaelab** [comment]
@adundovi  
Do you have a minimum working example that I can use to reproduce the problem?

**Comment by lukasmerten** [comment]
Just a few comments on this issue as I started to look into the nuclear decay for some other project:

1) CRPropa neglects any effects from Coulomb interaction between the electron/positron and the daughter nucleus for beta decay. This leads, e.g., to the same electron spectra for beta+ and beta- decay, which should be different at low energies. This could be updated by inclusion of the Fermi function into the beta decay routine. However, I am not sure if that is really relevant.

2) CRPropa assumes, as everywhere else, that the parent nucleus is moving with the speed of light v_N=c. With that assumption the Lorentz trafo of the electron energy from the nucleus into the lab frame is wrong at low nucleus energies, e.g., at rest. That good be fixed relatively easy.

If you want I can propose a PR for the two issues above but I am not sure if this will lead to the same spectra for neutrinos and electrons.

**Comment by lukasmerten** [comment]
The differences between theoretical expectations and the CRPropa results are from my quick research negligible for energies above 1TeV. As going to lower energies would break many other assumptions in CRPropa in basically all modules, I suggest to not fix this issue. In this way we consistently stick with ultra-relativitic approximations also for the beta decay.

I have added some more details to the comments in the beta decay function of the NuclearDecay module, to make the user more aware of this. In case there are additional problems with the secondary, we can open a new issue.

I would close this issue when the linked PR is merged.
