### ISSUE TITLE
Missing P0 in Output.Event3D

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#127]
Is the removal of P0x, P0y, P0z from Output.Event 3D intentional?
The absence of a P0 column is  serious problem for deflection studies.
RIght now the only columns are:  D, ID, E, X, Y, Z, Px, Py, Pz, ID0, E0, X0, Y0, Z0
I believe P0x, P0y, P0z should be added to it, as before.

**Comment by DavidWalz** [comment]
Yes (P0x, P0y, P0z) got lost due to a typo in 2ec8fe033d2631ca88f74cbfe4b822ddf3d296c0.
You can always customize the output to your liking though.
