### ISSUE TITLE
Simulation is stuck when SimplePropagation is used

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#128]
It seems that when a candidate is injected inside of the observer, simulation will stuck if `SimplePropagation` propagation is used. Here is a minimal example (with `PropagationCK` everything works fine).

```
from crpropa import *

sun_pos = Vector3d(-8.5, 0, 0) * kpc

obs = Observer()
obs.add(ObserverSmallSphere(sun_pos, 5*kpc))

#vgrid = VectorGrid(Vector3d(-30*kpc), 256, 0.2*kpc)
#Bfield = MagneticFieldGrid(vgrid)

sim = ModuleList()
prop = SimplePropagation()
#prop = PropagationCK(Bfield)
sim.add(prop)
sim.add(MaximumTrajectoryLength(100*kpc))
sim.add(obs)

sources = Source()
sources.add(SourceUniformSphere(Vector3d(0), 30*kpc))
sources.add(SourceEnergy(10*EeV))
sources.add(SourceIsotropicEmission())
sources.add(SourceParticleType(nucleusId(1,1)))

sim.setShowProgress()
sim.run(sources, 10000)
```

**Comment by DavidWalz** [comment]
This is probably due to Observer.cpp, line 107
```c++
	// conservatively limit next step to prevent overshooting
	candidate->limitNextStep(fabs(d - radius));
```

**Comment by DavidWalz** [comment]
We could 
a) increase SimplePropagation minStep to a small default value, say 1pc, or 
b) modify ObserverSmallSphere
```c++
if (d > radius)
	candidate->limitNextStep(fabs(d - radius));
```
I'm for doing both, because ObserverSmallSphere shouldn't limit the step size in that case, but there can be other instances where something limits the step size to 0.

**Comment by adundovi** [comment]
Tnx for your input. I put the issue here because I didn't know where to fix it. I'm more for your second suggestion because I wouldn't like to introduce any scale dependence in basic modules and I would like to avoid any context awareness of modules (e.g. that a propagation module knows for the observer's size).

In the case of PropagationCK, there is no problem, thus I would adjust the behaviour that SimplePropagation would behave the same as PropagationCK with the zero field, but I'm not sure how PropagationCK handles the situation.

**Comment by DavidWalz** [comment]
PropagationCK handles the situation the same way but currently has a default minimum step size of 0.1 * kpc.

I also think that context awareness is a no-go, and that scale independence would be good.
However we're only discussing the default value which only needs to work for default simulations, namely extragalactic and galactic propagation. I suggested 1 pc as a sane default even for galactic propagation.
In any case we should set the defaults of SimplePropagation and PropagationCK to the same value.

**Comment by adundovi** [comment]
OK. Now I see that in PropagationCK is the same. I agree that we update SimplePropagation module too with default values.

First, I thought of adding a check in ModuleList before injecting a candidate if it is inside of observer(s), but that would introduce an unneeded complexity.

What about writing an additional condition in propagation modules: if the current position is the same as the previous one, the propagated candidate is considered as trapped and should be discarded (e.g. zero step is not allowed in any propagation module): that does not introduce any hardcoded lengths, and the interpretation of it is physically straightforward: a particle cannot stay in-place between two points in "time".

**Comment by DavidWalz** [comment]
An even simpler check would be ```candidate->getNextStep() > 0```. 
We can do this but in my opinion it's not good if particles can drop out because something in the simulation chain caused the step size to go to 0, possibly causing a bias.
We can simply fix the case you found in ObserverSmallSphere.

**Comment by adundovi** [comment]
What if we throw a warning if the particle has been dropped in the case the step equals zero? I want to secure that a simulation always finishes, on the opposite, if it is stuck you don't have anything, not even biased results, and you don't know what happened to it. All breaking conditions are directly or indirectly connected to the propagation and if the propagation stops you end up in an endless loop - that's why we need a safe guard mechanism that will stop it in every case. Observers should not care what is going on with the propagation in general. Can you suggest cases where the step could drop to zero and that those cases are not considered bugs or non-physical issues?

On 9 June 2017 14:12:50 CEST, David Walz <notifications@github.com> wrote:
>An even simpler check would be ```candidate->getNextStep() > 0```. 
>We can do this but in my opinion it's not good if particles can drop
>out because something in the simulation chain caused the step size to
>go to 0, possibly causing a bias.
>We can simply fix the case you found in ObserverSmallSphere.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/CRPropa/CRPropa3/issues/128#issuecomment-307372587

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by DavidWalz** [comment]
It's exactly because i cannot think of any physical case where the step size should go to 0, that I think we should not catch this behavior **silently** and continue with the simulation.
If we throw a warning it's fine, at least as long as the output is looked at.
Personally I would always rather have the particle be propagated for the minimum step size than to have it dropped out.

I don't have a strong opinion about this, since the check is short and cheap. In PropagationCK it will be a little bit strange to look at, because ```double step = clip(candidate->getNextStep(), minStep, maxStep);``` effectively prevents it from ever occuring unless minStep is set 0 which doesn't play nice with an effective propagation in magnetic fields.

Apart from that topic, do you agree to adding the check for d < radius in ObserverSmallSphere which fixes the currently only known case for this bug?

**Comment by adundovi** [comment]
:-)

First, I agree to adjust default values for SimplePropagation to match PropagationCK which effectively fixes this issue. The previous setting minStep = 0 does not make sense to me - we cannot recommend using the zero step size in any propagation module.

Secondly, I think that we should not interrupt a 3-days simulation with millions injected candidates because of one or two extreme conditions we didn't handle properly. I would suggest a trivial "log facility" which would log notices, errors, and warnings to standard stdout/stderr by default or optionally to a file (or python). There, we could log not only technical details of the run but also already mentioned errors: a candidate with missing mass in the nuclear table, a dropped candidate or something user-customizable. That would be a mid-term task, not a part of this fix.

I don't have anything against an additional check in ObserverSmallSphere, but for me, your suggested fix doesn't work as it again converges, maybe not to zero, but somewhere close to it. Something like the following works, but it looks ugly as it implicitly brings the minimal step:
```c++
if (d > 1.001*radius)
                candidate->limitNextStep(fabs(d - radius));
```
Do you have any other suggestion?

The first thing already fixes the issue for the default scenario, and that is fine with me. Of course, there will always be a way how one could prepare a steering card which will not work, ending up in the infinite loop, but we cannot make CRPropa proof for any set-up.

**Comment by DavidWalz** [comment]
The boundary conditions (SphericalBoundary ...) have a margin setting that does allows for a small overshooting of the geometric surface pretty similar to what you propose.

**Comment by adundovi** [comment]
Meh, I don't like it as it is again a scale dependent parameter which one needs to keep in mind when going into non-default scales. :-)

I wrongly diagnosed the bug: it is not when a candidate is injected inside of the observer, but when it is approach to the observer "tangentially". Limiting the step to fabs(d-radius) is unnecessarily restrictive, a proper way to do it would be the tangent length sqrt(d^2-radius^2) which will serve the same purpose - preventing overshooting, but will not lead to a situation where the particle stops and "hovers" above the sphere surface as it is the case with fabs(d-radius). Only the case where the particle is heading to the center of the sphere, two cases will be the same. After fixing that, everything works as expected and there is no scale dependence. The previous fix leads to 10% less detections - which is a faulty result compared to default PropagationCK and SimplePropagation with the minimal step larger than 0.

**Comment by DavidWalz** [comment]
Good fix!
