### ISSUE TITLE
Candidate.addSecondaries doesn't always use ref_ptr

### ISSUE THREAD

**Issue by mattjweiss** [CRPropa/CRPropa3#129]
Is this a bug? `Candidate.addSecondary` in most cases seems to add a `ref_ptr<Candidate>` to `Candidate.secondaries`, but in one case it just uses a normal pointer, as in the code below. Additionally, adding a clone of a `Candidate` as a secondary seems to cause a core dump if a `ref_ptr` is not used.

```
114 void Candidate::addSecondary(Candidate *c) {
115     secondaries.push_back(c);
116 }
```
I was trying to clone particles with `Candidate.clone` and then add them as secondaries, but `Candidate.clone` returns a `ref_ptr<Candidate>` and `addSecondary` threw a type error when I passed that to it:

```
>>> candidate = Candidate()
>>> clone = candidate.clone()
>>> candidate.addSecondary(clone)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Candidate_addSecondary'.
  Possible C/C++ prototypes are:
    crpropa::Candidate::addSecondary(crpropa::Candidate *)
    crpropa::Candidate::addSecondary(int,double)
    crpropa::Candidate::addSecondary(int,double,crpropa::Vector3d)
```

 I then tried using `CandidateRefPtr.get` before passing to `addSecondary`, but I got a core dump:

```
from crpropa import *
candidate = Candidate()
clone = candidate.clone().get()
candidate.addSecondary(clone)

sim = ModuleList()
sim.add(SimplePropagation())
sim.add(MinimumEnergy(1*EeV))
sim.run(candidate)
```

```
*** Error in `python': malloc(): memory corruption: 0x00007fa8ed56eb10 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fa8ed2227e5]
...
...
...
7fff28a7a000-7fff28a9b000 rw-p 00000000 00:00 0                          [stack]
7fff28bd5000-7fff28bd7000 r--p 00000000 00:00 0                          [vvar]
7fff28bd7000-7fff28bd9000 r-xp 00000000 00:00 0                          [vdso]Aborted (core dumped)
```
(For some reason this doesn't always fail when pasted into a python terminal, but it always fails when run as a script).

 I was forced to use `Candidate.secondaries.push_back` to add a `ref_ptr<Candidate>` to `Candidate.secondaries`, which may not be intended as a part of CRPropa's interface.
```
from crpropa import *
candidate = Candidate()
clone = candidate.clone()
candidate.secondaries.push_back(clone)

sim = ModuleList()
sim.add(SimplePropagation())
sim.add(MinimumEnergy(1*EeV))
sim.run(candidate)
```

**Comment by adundovi** [comment]
I'll take a look into it. It is probably caused by the SWIG interface and the object ownership which is not so easy to debug. Try to disown the cloned particle like this:
```
...
clone = candidate.clone()
clone.disown()
candidate.addSecondary(clone.get())
...
```
In the worst case scenario, you can try to write a program within [C++](https://github.com/CRPropa/CRPropa3/wiki/Cpp-projects) where you have a full control over pointers and the memory allocation.
