### ISSUE TITLE
Exact reproducibility

### ISSUE THREAD

**Issue by dfche** [CRPropa/CRPropa3#131]
What steps are necessary to force a simulation to be exactly reproducible?
I have tried seeding the random number generator at the start of the script

import sys
from crpropa import *
randomseed=(a fixed number)
crpropa.Random.instance().seed(randomseed)
etc.

but I find that the outputs are different (and not just ordered
differently as might be expected for a multithreaded application).

**Comment by adundovi** [comment]
The main seed for most modules can be set with (see [here](https://github.com/CRPropa/CRPropa3/wiki/Random-Numbers)):
```
Random_seedThreads(seed)  # seed from 0 - 2^32-1
```
Here is an example:
```
from crpropa import *
Random_seedThreads(10)
s = Source()
s.add(SourceIsotropicEmission())
c = s.getCandidate()
print c.current.getDirection()
```
which always returns: `Vector(0.253337, -0.80085, 0.542641)`.

Exceptions are `initTurbulence` (for a turbulent field) and `PhotonPropagation` where the seed should be set independently.
