### ISSUE TITLE
Specify a source evolution in a 1D simulation

### ISSUE THREAD

**Issue by DavidWalz** [CRPropa/CRPropa3#134]
_Received via mail:_
But doesn't specifying the redshift distribution of sources automatically specifies the distance for each source? If not, how do I do it?

```python
source = Source()
source.add(SourceParticleType(nucleusId(1, 1)))
source.add(SourcePowerLawSpectrum(1 * EeV, 200 * EeV, -1))
source.add(SourceRedshiftEvolution(1.5, 0.001, 3))
```

**Comment by DavidWalz** [comment]
CRPropa can simulate in 4D for which spatial coordinates are specified separately from time (redshift).
If you want to perform a 1D simulation with sources distributed according to (1 + z)^m you can define a custom source property like so (see https://github.com/CRPropa/CRPropa3/wiki/Extending-CRPropa)

```python
class MySourceFeature(SourceFeature):
    """ Set the distance according to the redshift """
    def prepareCandidate(self, candidate):
        z = candidate.getRedshift()
        d = redshift2ComovingDistance(z)
        candidate.source.setPosition(Vector3d(d, 0, 0))
        candidate.create.setPosition(Vector3d(d, 0, 0))
        candidate.current.setPosition(Vector3d(d, 0, 0))
        candidate.previous.setPosition(Vector3d(d, 0, 0))

source = Source()
source.add(SourceParticleType(nucleusId(1, 1)))
source.add(SourcePowerLawSpectrum(1 * EeV, 200 * EeV, -1))
source.add(SourceRedshiftEvolution(1.5, 0.001, 3))
f = MySourceFeature()
source.add(f)

# try it out
for i in range(10):
    c = source.getCandidate()
    z = c.getRedshift()
    d = c.current.getPosition().getR() / Mpc
    print(z, d)
```

**Comment by saikat8018** [comment]
Here I get an AttributeError:

`Run ModuleList
Traceback (most recent call last):
  File "<stdin>", line 7, in prepareCandidate
Traceback (most recent call last):
Traceback (most recent call last):
AttributeError: Traceback (most recent call last):
'crpropa.Candidate' object has no attribute 'create'  File "<stdin>", line 7, in prepareCandidate
  File "<stdin>", line 7, in prepareCandidate
  File "<stdin>", line 7, in prepareCandidate

AttributeErrorAttributeErrorAttributeError: 'crpropa.Candidate' object has no attribute 'create'Exception KeyError: KeyError(140198136055552,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'>: :  ignored`

**Comment by saikat8018** [comment]
Okay, it should be `created` instead of `create` :-
`candidate.created.setPosition(Vector3d(d, 0, 0))`

But even after this, there is no change in the energy. Is it because I am using:
```
obs = Observer()
obs.add(ObserverDetectAll())
```
Or, can it be because the sources from the nearest redshift dominate? But then, with higher redshift also there is no change in energy. Here is the full script that I am running,

```
from crpropa import *

# random turbulent field
randomSeed = 42
vgrid = VectorGrid(Vector3d(0), 256, 30*kpc)
initTurbulence(vgrid, 8*nG, 60*kpc, 800*kpc, -11./3., randomSeed)
Bfield = MagneticFieldGrid(vgrid)

# adding the modules for simulation
sim = ModuleList()
sim.add( PropagationCK(Bfield) )
sim.add( Redshift())
sim.add( PhotoPionProduction(CMB) )
sim.add( PhotoPionProduction(IRB) )
sim.add( PhotoDisintegration(CMB) )
sim.add( PhotoDisintegration(IRB) )
sim.add( ElectronPairProduction(CMB) )
sim.add( ElectronPairProduction(IRB) )
sim.add( NuclearDecay() )
sim.add( MinimumEnergy(1 * EeV) )

# defining the observer
obs = Observer()
obs.add( ObserverDetectAll() )
output = TextOutput('sim_3d.txt', Output.Event3D)
obs.onDetection(output)
sim.add(obs)
print obs

# defining the source
class MySourceFeature(SourceFeature):
    """ Set the distance according to the redshift """
    def prepareCandidate(self, candidate):
        z = candidate.getRedshift()
        d = redshift2ComovingDistance(z)
        candidate.source.setPosition(Vector3d(d, 0, 0))
        candidate.created.setPosition(Vector3d(d, 0, 0))
        candidate.current.setPosition(Vector3d(d, 0, 0))
        candidate.previous.setPosition(Vector3d(d, 0, 0))

source = Source()
source.add(SourceParticleType(nucleusId(1, 1)))
source.add(SourcePowerLawSpectrum(1 * EeV, 200 * EeV, -1))
source.add(SourceRedshiftEvolution(1.5, 0.001, 3))
f = MySourceFeature()
source.add(f)

sim.setShowProgress(True)
sim.run(source, 20000)
```

**Comment by DavidWalz** [comment]
Thanks, updated.

**Comment by saikat8018** [comment]
Yes, I have seen the example at https://github.com/CRPropa/CRPropa3-notebooks/blob/master/sim1D/sim1D.py

But for a redshift distribution of sources of the form (1+z)^m, `candidate.source.setPosition(Vector3d(d, 0, 0))` will specify the direction in a particular direction. How can I randomize the position of the sources in arbitrary directions?

Also in case of 4D simulation, where both magnetic field and time(redshift) is to be specified, how should one define the observer, so that the particles are detected at (0, 0, 0). What should be the correct alternative for `ObserverDetectAll`

**Comment by DavidWalz** [comment]
I just added a [4D simulation example](https://github.com/CRPropa/CRPropa3-notebooks/blob/master/sim4D/sim4D.v3.ipynb) which you can refer to. If you have specific questions to your simulation please open a new ticket.

**Comment by saikat8018** [comment]
Okay, thank you very much.
