### ISSUE TITLE
 Could not open file IRB_Kneiske04

### ISSUE THREAD

**Issue by rattallah** [CRPropa/CRPropa3#135]
Hi,
I've installed the last version of CRPropa 3 without any problem.
During the execution of an example, I received the following error:
--------------------------------------------------------------------------------------
terminate called after throwing an instance of 'std::runtime_error'
what():  crpropa: could not open file IRB_Kneiske04
Aborted (core dumped)
-----------------------------------------------------------------------------
Any help, please?
Reda

**Comment by rattallah** [comment]
Dear Lukas,
Thanks a lot for your reply. In fact, I got the error mentioned in my previous post when I installed CRPropa using "git clone ...". When I installed CRPropa after downloading the tar.gz source code, I didn't get any error. Now everything is working fine.
Thanks once more, Reda.

**Comment by adundovi** [comment]
Dear Reda, during the cmake step of [the installation](https://github.com/CRPropa/CRPropa3/wiki/Installation) (``c(c)make ..``) an archive with photon fields and other data files is downloaded and extracted in the build folder. When the ``make install`` step is successfully finished all extracted data files should be copied in `(installation destination)/share/crpropa/`. Among those files you should have ``*_IRB_Kneiske04.txt`` files listed. Please check if that is true.

**Comment by adundovi** [comment]
Dear Reda, during the cmake step of the installation (c(c)make ..) an archive with photon fields and other data files is downloaded and extracted in the build folder. When the make install step is successfully finished all extracted data files should be copied in (installation destination)/share/crpropa/. Among those files you should have *_IRB_Kneiske04.txt files listed. Please check if that is true.

**Comment by rattallah** [comment]
That is true. This file exists. But as I mentioned in my previous post, with the installation through the tar source file (instead of clone ...), things got back to normal.
