### ISSUE TITLE
Remove ROOT as a dependency

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#142]
Remove ROOT as a dependency and provide a conversion script from the default to the ROOT output.

**Comment by TobiasWinchen** [comment]
As discssed in meeting, move ROOT Output to  a new plugin repository.

**Comment by adundovi** [comment]
HDF5 output can be converted to ROOT with [hdf2root](https://github.com/delaossa/hdf2root) so should we have the plugin at all?

**Comment by rafaelab** [comment]
I appreciate that this is simpler, but it would add an additional dependence for users who want to use just ROOT, since it would require both packages to be installed.
Nevertheless, nowadays HDF5 can be found in most OS by default, so this requirement is not very strict.
