### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by lyang54** [CRPropa/CRPropa3#150]
I follow the example here https://github.com/CRPropa/CRPropa3-notebooks/blob/master/galactic_lensing/lensing_cr.py, and getting the error complaining about the data type of id, which I have already make them as int… I am wondering, if you know if there is any error here. Thanks a lot.

import crpropa
import numpy as np

M = crpropa.ParticleMapsContainer()
crdata = np.genfromtxt("crpropa_output.txt")
id = crdata[:,3]
id = np.array(map(int, id))
E = crdata[:,4] * crpropa.EeV
E0 = crdata[:,13] * crpropa.EeV
px = crdata[:,8]
py = crdata[:,9]
pz = crdata[:,10]
galactic_longitude = np.arctan2(-1. * py, -1. *px)
galactic_latitude = np.pi / 2 - np.arccos( -pz / (px*px + py*py+ pz*pz) )

M.addParticles(id, E, galactic_longitude, galactic_latitude, E0**-2.56)

>>> M.addParticles(id, E, galactic_longitude, galactic_latitude, E0**-2.56)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: ParticleMapsContainer::addParticles -  require array of type int as input for ids

With Tobias's help, adding id = np.array(id, dtype='i'), now it works.

@TobiasWinchen I also have one very naive question, what is the unit of the output of the example here? 
for pid in M.getParticleIds():
    energies = M.getEnergies(int(pid))
    for i, energy in enumerate(energies):
        crMap += M.getMap(int(pid), energy * crpropa.eV )

One more thing, can you provide any reference for the extragalactic magnetic field implemented in CRPropa? Thanks a lot.

**Comment by TobiasWinchen** [comment]
The particle maps container just collects the number, respectively summed weights, of particles per pixel. Every pixel has the area 4pi / 49152 sr.

 I don't think there is a generic reference for  `the extragalactic magnetic field implemented in CRPropa', as  we provide only a generic turbulent field or facilities to load a user defined EGMF. For any specific models e.g. for the Galactic fields the appropriate reference should be given in the specific header.
