### ISSUE TITLE
Secondary neutrino propagation

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#154]
While propagating secondary neutrinos in a 4D simulation, the output yields minimum energy of detected neutrinos at a value same as the minimum energy of cosmic ray injection spectrum. Is this because the `MinimumEnergy( )` module is applicable to secondaries too and the simulation stops when the neutrinos reach this minimum energy? I am considering `PhotoPionProdction( )`, `NuclearDecay( )`, and `PhotoDisintegration( )` of heavier nuclei ( eg. Fe, O, C). So the expected neutrino spectrum should start at a value much lower than that of minimum cosmic ray energy. But why am I not able to obtain that?

**Comment by TobiasWinchen** [comment]
The MinimumEnergy module will act on all particles. You can either use the MinimumRigidity module instead or write a custom module as described in the [wiki](https://github.com/CRPropa/CRPropa3/wiki/Extending-CRPropa)
