### ISSUE TITLE
Using magnetic fields

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#156]
Suppose, I want to use the Pshirkov field as the magnetic field through which the cosmic rays propagate. What should be the correct syntax for that? Should I have,

```
Bfield = PshirkovField( )
m = ModuleList( )
m.add(PropagationCK(Bfield))
```

Is this correct, or I need to have an argument in `PshirkovField( )` ? Also, is the `PeriodicBox` boundary condition applicable while using any magnetic field in a 4D scenario?

Saikat

**Comment by lukasmerten** [comment]
Hi
This sytax will work. So you don't need any arguments for the Pshirkov field but you can specify the details of the Pshirkov field (see [here](https://github.com/CRPropa/CRPropa3/blob/master/src/magneticField/PshirkovField.cpp)).
In addition you can also specify the tolerance and the minum and maximum step length for the propagation module:
```
Bfield = PshirkovField( )
tolerance = 1e-3
minStep = 10*pc
maxstep = 1*kpc
m = ModuleList( )
m.add(PropagationCK(Bfield, tolerance, minStep, maxStep))
```
If the periodic boundary is applicable or not depends on the magnetic field and on the way you want to interpret the data. If you are using a galactic magnetic field (e.g. Pshirkov or JF12) you would not expect a cosmic ray leaving the magnetic field in the North to reenterthe simulation box in the South. In this case I would avoid using both reflective and/or periodic boundaries. 
If you have instead a purely turbulent field where the magnetic field is likely to look the same on large scales it is convient to use reflective or periodic boundaries simply to reduce the simulation volume (see also [here](https://github.com/CRPropa/CRPropa3-notebooks/blob/master/sim4D/sim4D.v3.ipynb)).

**Comment by saikat8018** [comment]
Okay. Thank you very much for the information. I am closing this issue for now.
