### ISSUE TITLE
seperate output files for various channels

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#158]
Hi,

What is the correct way to write the output from various channels of secondary particle production in different output files? For eg., while propagating secondary neutrinos, is there a way I can separate out the neutrinos from beta-decay and pion decay in two different output files?

**Comment by saikat8018** [comment]
Also, is there a separate beta-decay module, or does NuclearDecay( ) takes care of it?

**Comment by lukasmerten** [comment]
Beta decay is included in NuclearDecay().

**Comment by saikat8018** [comment]
Thank you. Can you say something about my 1st question? How does one separate the various channels of neutrino production in separate output files? @lukasmerten

**Comment by avvliet** [comment]
It is at the moment not possible to separate the various channels of neutrino production in separate output files. But the type of neutrino that you get is given in the output file (12 = electron neutrino, 14 = muon neutrino), with a '-' in case of the anti-particles. You can use that to separate the various channels after the simulation.

**Comment by saikat8018** [comment]
Okay. Thank you. That suffices to answer my query. Thank you very much

Saikat

**Comment by avvliet** [comment]
You're welcome. Arjen
