### ISSUE TITLE
some photons in secondary neutrino output 

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#159]
In the example for [secondary neutrinos](https://github.com/CRPropa/CRPropa3-notebooks/blob/master/secondaries/neutrinos.v3.ipynb), I am keeping all other modules same and change the particle type for propagation to iron nuclei. 
`source.add(SourceParticleType(nucleusId(56,26)))`
Thus the output file for neutrino should store only neutrinos & antineutrinos. But in the output, I obtain few but a certain number of particles with ID 22, i.e. photons. What can be the possible reason? Is `ElectronPairProduction( )` causing the trouble? Should I use `ObserverPhotonVeto( )` too in case of propagating heavier nuclei? There is no issue with protons.

Can you please look at it?

**Comment by avvliet** [comment]
This was also due to the missing electrons in `m.add(NuclearDecay(electrons, photons, neutrinos))`. I've fixed the example. It should be correct now.

**Comment by saikat8018** [comment]
Okay. Thank you very much for the response. Yes now it's working completely fine. 
Thank you once again
