### ISSUE TITLE
No secondary output with NuclearDecay( )

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#160]
I am running a script (1D simulation) to save the neutrinos from nuclear decay (beta decay) only, for injected iron nuclei with 10000 primaries, but there is no output. Here is a minimal script:

```
from crpropa import *

neutrinos = True
photons = False

# module setup
m = ModuleList( )
m.add(SimplePropagation(10*kpc, 10*Mpc))
m.add(Redshift( ))
m.add(NuclearDecay(photons, neutrinos))
m.add(MinimumEnergy(10**13 * eV))

# observer for neutrinos
obs = Observer( )
obs.add(ObserverPoint( ))
obs.add(ObserverNucleusVeto( ))
obs.add(ObserverPhotonVeto( ))
output = TextOutput('neutrinos.txt', Output.Event1D)
obs.onDetection(output)
m.add(obs)

# defining the source
source = Source()
source.add(SourceUniform1D(3 * Mpc, 1000 * Mpc) )
source.add(SourceRedshift1D() )
source.add(SourcePowerLawSpectrum(1 * EeV, 1000 * EeV, -1))
source.add(SourceParticleType(nucleusId(56, 26)))
print source

m.setShowProgress(True)
m.run(source, 10000, True)
```
The output file neutrinos.txt is empty. Why is this so? The neutrinos due to `NuclearDecay( photons, neutrinos )` is not getting saved. Can anyone please see it?

**Comment by avvliet** [comment]
Well, if you start with a stable particle (iron in this case) and no other interactions are included at all you will never get an unstable particle, so no nuclear decay will ever happen. Try adding photodisintegration in the module list, you should get some neutrinos from nuclear decay then.

**Comment by saikat8018** [comment]
Okay, I have added 

```
m.add(PhotoDisintegration(CMB))
m.add(PhotoDisintegration(IRB))
```
Still, there are no neutrinos. Should I add secondaries in the argument for `PhotoDisintegration( )` ? Like this:

`PhotoDisintegration(CMB, photons, neutrinos)
`

**Comment by avvliet** [comment]
For nuclear decay you should add the electrons:
`m.add(NuclearDecay(electrons, photons, neutrinos))`

This should work:
```
from crpropa import *

neutrinos = True
photons = False
electrons = False

# module setup
m = ModuleList( )
m.add(SimplePropagation(10*kpc, 10*Mpc))
m.add(Redshift( ))
m.add(PhotoDisintegration(CMB))
m.add(PhotoDisintegration(IRB))
m.add(NuclearDecay(electrons, photons, neutrinos))
m.add(MinimumEnergy(10**13 * eV))

# observer for hadrons
obs1 = Observer( )
obs1.add(ObserverPoint( ))
obs1.add(ObserverNeutrinoVeto( ))
output1 = TextOutput('nucleons.txt', Output.Event1D)
obs1.onDetection(output1)
m.add(obs1)
# observer for neutrinos
obs = Observer( )
obs.add(ObserverPoint( ))
obs.add(ObserverNucleusVeto( ))
obs.add(ObserverPhotonVeto( ))
output = TextOutput('neutrinos.txt', Output.Event1D)
obs.onDetection(output)
m.add(obs)

# defining the source
source = Source()
source.add(SourceUniform1D(3 * Mpc, 1000 * Mpc) )
source.add(SourceRedshift1D() )
source.add(SourcePowerLawSpectrum(1 * EeV, 1000 * EeV, -1))
source.add(SourceParticleType(nucleusId(56, 26)))
print source

m.setShowProgress(True)
m.run(source, 10000, True)
```

I see this is not correct in the example, I'll fix it there.

**Comment by saikat8018** [comment]
Okay. Thank you so very much for correcting me with the syntax error that I have been doing till now. 

But in case of propagating Protons only, there is no point in adding `PhotoDisintegration( )`. So, in that case, how does one calculate the spectrum of neutrinos from beta decay? Adding only `NuclearDecay( )` in case of protons gives no output for neutrinos.

Is there a way one can separate the various channels of secondary production into different output files, in one run?

**Comment by saikat8018** [comment]
HI,
Before closing can you please tell me how to get the neutrino spectrum from beta decay only in case of propagating Protons.

Adding `NuclearDecay(electrons, photons, neutrinos)` only doesn't work.

**Comment by avvliet** [comment]
If you only have nuclear decay on as interaction and you start with protons no beta decays will occur as protons are stable. If you, for instance, start with neutrons instead of protons you will get neutrinos from beta decay out in this way. Or if you want the beta-decay neutrinos from neutrons created in photo-pionproduction you should add the photo-pionproduction interaction to the module list. This, for example, would give you the neutrinos from beta-decay only:

```
from crpropa import *

neutrinos = True
photons = False
electrons = False

# module setup
m = ModuleList( )
m.add(SimplePropagation(10*kpc, 10*Mpc))
m.add(Redshift( ))
m.add(PhotoPionProduction(CMB))
m.add(PhotoPionProduction(IRB))
m.add(NuclearDecay(electrons, photons, neutrinos))
m.add(MinimumEnergy(10**13 * eV))

# observer for hadrons
obs1 = Observer( )
obs1.add(ObserverPoint( ))
obs1.add(ObserverNeutrinoVeto( ))
output1 = TextOutput('nucleons.txt', Output.Event1D)
obs1.onDetection(output1)
m.add(obs1)
# observer for neutrinos
obs = Observer( )
obs.add(ObserverPoint( ))
obs.add(ObserverNucleusVeto( ))
obs.add(ObserverPhotonVeto( ))
output = TextOutput('neutrinos.txt', Output.Event1D)
obs.onDetection(output)
m.add(obs)

# defining the source
source = Source()
source.add(SourceUniform1D(3 * Mpc, 1000 * Mpc) )
source.add(SourceRedshift1D() )
source.add(SourcePowerLawSpectrum(1 * EeV, 1000 * EeV, -1))
source.add(SourceParticleType(nucleusId(1, 1)))
print source

m.setShowProgress(True)
m.run(source, 10000, True)
```

**Comment by saikat8018** [comment]
Okay. Thank you once. You have helped a lot.
