### ISSUE TITLE
HDF5Output

### ISSUE THREAD

**Issue by teresakarolin** [CRPropa/CRPropa3#161]
I am using CRPropas HDF5Output(outfile, crp.Output.Everything) to produce my output and experience 2 different errors, which could be related.

The first thing is that this sometimes (but randomly) gives an output named "Event3D" although it should always give "CRPROPA3".  If I try to open it with the wrong keyword, I get:

---------------------------------------------------------------------------------------------------------
In [4]: pandas.HDFStore("/tmp/GMF_prop_0_A4_B1.0_L8_272_0.hdf5").get("CRPROPA3")
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-e547a92d4188> in <module>()
----> 1 pandas.HDFStore("/tmp/GMF_prop_0_A4_B1.0_L8_272_0.hdf5").get("CRPROPA3")

/usr/lib/python2.7/site-packages/pandas/io/pytables.pyc in get(self, key)
    668         group = self.get_node(key)
    669         if group is None:
--> 670             raise KeyError('No object named %s in the file' % key)
    671         return self._read_group(group)
    672 

KeyError: 'No object named CRPROPA3 in the file'
---------------------------------------------------------------------------------------------------------

**The second thing is that it sometimes produces broken output, which gives me an error:**

---------------------------------------------------------------------------------------------------------
In [3]: pandas.HDFStore("/tmp/GMF_prop_0_A4_B1.0_L8_272_0.hdf5").get("Event3D")
---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
<ipython-input-3-0b039e9e01ee> in <module>()
----> 1 pandas.HDFStore("/tmp/GMF_prop_0_A4_B1.0_L8_272_0.hdf5").get("Event3D")

/usr/lib/python2.7/site-packages/pandas/io/pytables.pyc in get(self, key)
    669         if group is None:
    670             raise KeyError('No object named %s in the file' % key)
--> 671         return self._read_group(group)
    672 
    673     def select(self, key, where=None, start=None, stop=None, columns=None,

/usr/lib/python2.7/site-packages/pandas/io/pytables.pyc in _read_group(self, group, **kwargs)
   1347         s = self._create_storer(group)
   1348         s.infer_axes()
-> 1349         return s.read(**kwargs)
   1350 
   1351 

/usr/lib/python2.7/site-packages/pandas/io/pytables.pyc in read(self, where, columns, **kwargs)
   4132     def read(self, where=None, columns=None, **kwargs):
   4133 
-> 4134         if not self.read_axes(where=where, **kwargs):
   4135             return None
   4136 

/usr/lib/python2.7/site-packages/pandas/io/pytables.pyc in read_axes(self, where, **kwargs)
   3332         # create the selection
   3333         self.selection = Selection(self, where=where, **kwargs)
-> 3334         values = self.selection.select()
   3335 
   3336         # convert the data

/usr/lib/python2.7/site-packages/pandas/io/pytables.pyc in select(self)
   4731         elif self.coordinates is not None:
   4732             return self.table.table.read_coordinates(self.coordinates)
-> 4733         return self.table.table.read(start=self.start, stop=self.stop)
   4734 
   4735     def select_coords(self):

/usr/lib/python2.7/site-packages/tables/table.pyc in read(self, start, stop, step, field, out)
   1924                                                 warn_negstep=False)
   1925 
-> 1926         arr = self._read(start, stop, step, field, out)
   1927         return internal_to_flavor(arr, self.flavor)
   1928 

/usr/lib/python2.7/site-packages/tables/table.pyc in _read(self, start, stop, step, field, out)
   1838             # This optimization works three times faster than
   1839             # the row._fill_col method (up to 170 MB/s on a pentium IV @ 2GHz)
-> 1840             self._read_records(start, stop - start, result)
   1841         # Warning!: _read_field_name should not be used until
   1842         # H5TBread_fields_name in tableextension will be finished

tables/tableextension.pyx in tables.tableextension.Table._read_records (tables/tableextension.c:8035)()

HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 171, in H5Dread
    can't read data
  File "H5Dio.c", line 544, in H5D__read
    can't read data
  File "H5Dchunk.c", line 2050, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 3405, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1374, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 123, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace

Problems reading records.
---------------------------------------------------------------------------------------------------------

**The broken data files can be fixed by copying them to another folder. After that they can be opened in a normal way and with varying keys Event3d or CRPROPA3. The error message is from pandas version 0.21.0. With an older version of pandas I get a different error for the second problem:**

---------------------------------------------------------------------------------------------------------
HDF5 error back trace

  File "../../../src/H5F.c", line 579, in H5Fopen
    unable to open file
  File "../../../src/H5Fint.c", line 1168, in H5F_open
    unable to lock the file or initialize file structure
  File "../../../src/H5FD.c", line 1821, in H5FD_lock
    driver lock request failed
  File "../../../src/H5FDsec2.c", line 939, in H5FD_sec2_lock
    unable to flock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace
---------------------------------------------------------------------------------------------------------

**Comment by TobiasWinchen** [comment]
Hi, this could be (at least partly) a problem with the filesystem you are using for the /tmp directory and not CRPropa, which file system are you using?
This also might be a bug in pandas, can you use the file with h5py, h5dump and/or e.g. hdfview. 
Could you also post your simulation script?

**Comment by teresakarolin** [comment]
The tmp directory was just to try this at a different computer. I normally write the files on another folder, which gives the same problems. I also already tried to open the file with hdfview, which gives the error:

'Filter not available exception: Unable to initialize object'

Again, after copying the file once (but only within the VISPA server, if I copy it to my private computer only it is still broken), it is repaired and can be opened with hdfview. 

The simulation script is attached.
[propagationGMF.txt](https://github.com/CRPropa/CRPropa3/files/1615014/propagationGMF.txt)

**Comment by TobiasWinchen** [comment]
**Regarding the datasetname:** 
Since Dec 7. , commit  9ec850f3778de2e1b06dfc5691ac177cadae90da the dataset name is no longer CRPROPA3 but the outputtype, i.e. Event3D, Event1D, TRajectory, etc.. I am not sure it we will keep this as I think that might be confusing. A better  solution would be having the outputtype as an attribute of the dataset. @adundovi , any opinion?

**Regarding opening the file:**
I need some  more information:
 * How big is the file?
 * Can you open the file with h5dump (use -H option to abbreviate the output)? In which directories?
 * Does the `copy trick' work also if you copy the file in the same directory?
 * What are the filesystems of the directories you can open the file?

**Comment by teresakarolin** [comment]
The file is smaller than 100 kbyte. 
It cannot be opened with h5dump, this gives an error: 'unable to open file'.
The trick does not work within the same directory and also not if I cut and insert it somewhere else. The filsesystem is ext4 mounted via nfs4 (local cluster).

**Comment by adundovi** [comment]
I've been rewriting HD5 module, but generally I'm still not satisfied in which state it is. Nevertheless, the current status should work.

Since I'm not a regular user of HDF5s, could you please elaborate what is expected behaviour of this output module?

@TobiasWinchen OK, the outputtype can be be an attribute.

**Comment by teresakarolin** [comment]
Actually, @adundovi, the current version does not work. I just realised this a few minuttes ago when I updated because I do not get an error, but also no output at all. I am currently still testing to see which commit is a problem, but the newest version of HDFOutput does not give any output at all.
I dont really know what you are asking, I am just expecting to get a working hdf5 file in the end and currently I get none and with an older version of crpropa I get one, which is broken 30% of the time.

**Comment by teresakarolin** [comment]
[test.txt](https://github.com/CRPropa/CRPropa3/files/1619403/test.txt)


This is a very basic example of the script I am running to test the output. It should produce the file 'events.hdf5', which it did on an older version, but not anymore.

**Comment by TobiasWinchen** [comment]
@teresakarolin: Do I understand you correctly that you actually have to copy the file (via cp  command) to a different folder. A cp command in the same folder does not work. A move command to a different folder also does not work?

**Comment by TobiasWinchen** [comment]
@teresakarolin: In the script you send around the observer is missing a property like `obs.add( ObserverPoint() )` . Adding this output is created.

**Comment by teresakarolin** [comment]
I copy it via cp in another folder, remove the original data and copy it back: then it is repaired.
If I move it via mv to another directory and move it back, it is not repaired. Just renaming it in the same folder does not repair it either.

**Comment by TobiasWinchen** [comment]
And a copy in the same folder: cp foo.h5 bar.h5, can bar.h5 be opened then? Can the data be opened in the new folder after mv ?

**Comment by teresakarolin** [comment]
@TobiasWinchen , sorry, the obs.add( ObserverPoint() ) must have gone missing. Nevertheless it still does not produce any output.

The cp within the same folder repairs the data. 
The moved file cannot be opened.

**Comment by teresakarolin** [comment]
I do not know what you mean by level, do you mean the version number?

**Comment by teresakarolin** [comment]
The HDF5_USE_FILE_LOCKING=FALSE does not change anything, h5dump still cannot open the file.

**Comment by TobiasWinchen** [comment]
Yes sorry, I mean the version number of course.

**Comment by teresakarolin** [comment]
After an intensive day of testing it became clear that the problem was not CRPropa, but two cpus on the used VISPA cluster had a broken cache, which also explains, why the problem only occured sometimes. Sorry for the inconveniences and thanks for the help anyways!
