### ISSUE TITLE
EMCascade( ) module

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#162]
Is the `EMCascade` module usable? To propagate the secondaries (electrons and photons), is it necessary to add this module separately? 

While propagating secondaries (electrons and photons) using CRPropa, the new electromagnetic interaction processes included in CRPropa3.1 will account for the various energy loss mechanisms. Also, more secondaries will be produced in this interactions too. So, where do we use the separate module for electromagnetic cascade?

Also, how do I change the IRB model to other available options?

**Comment by cheiter** [comment]
The EMCascade module supplies a framework which easily collects photons and electrons from a running CRPropa simulation and prepares them for further propagation with DINT.

It can be used directly in the simulation which results in a pure DINT propagation of photons and electrons or for the combined CRPropa-DINT usecase, a file with photon and electron data in which the cascade is driven to a certain threshold energy with the CRPropa EM interaction modules can be loaded.  

So it depends on your simulation if you need to add the module:
If you are interested only in photon and electron spectra above 0.01 EeV -> not needed
If you are interested in photon and electron spectra at lower energies -> needed 

For the DINT propagation you can change the IRB model using the IRB flag in the runCascade function.

**Comment by saikat8018** [comment]
I am saving the cascade data in `PhotonOutput1D` format and then passing it to DINT. How is the cascade driven to a certain threshold energy? Is this the same as crossover energy for combined EleCa-DINT or, CRPropa-DINT propagation?

**Comment by cheiter** [comment]
I think this is answered in #163
