### ISSUE TITLE
HDF5 

### ISSUE THREAD

**Issue by teresakarolin** [CRPropa/CRPropa3#164]
I installed CRPropa for testing purposes without hdf5 (DENABLE_HDF5=False + checked with ldd that hdf5 is not linked to libcrpropa.so). Then I tried to run a file producing hdf5 output, this finsihed normally without a warning but did not produce output. The latter was expected of course, the former not.

**Comment by TobiasWinchen** [comment]
I cannot reproduce this Compilation with -DENABLE_HDF5=False behaves as expected:

```
In [1]: import crpropa

In [2]: f  = crpropa.HDF5Output()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-08c349c250fa> in <module>()
----> 1 f  = crpropa.HDF5Output()

AttributeError: 'module' object has no attribute 'HDF5Output'
```
