### ISSUE TITLE
Cannot import crpropa without data files

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#166]
Import crpropa without datafiles is not possible, even though we allow compilation. CRPropa should only crash if a module requiring the datafiles is accessed.

**Comment by adundovi** [comment]
It is probably to expensive to open files every time when one needs an access. That means that we require some sort of initialization method during the first access.

Let's look at one example: '''nuclearMass(int A, int Z)'''. It calls nuclearMassTable.table[] which is initialized at the start of CRPropa. To load the data later one would at least have to check if the file has already been opened or not.

Do we really need this? I would implement this mechanism only for those modules which already have or require initialization in any case. Maybe to split data files to the required ones and those "optional" (for modules with init)? The case of nuclearMass is a clear example why to avoid any additional overhead introduced by additional checks - it is called almost constantly in every simulation in every step.

**Comment by TobiasWinchen** [comment]
Of course we should not read the data files more than once, but only on the first access. However, if you currently don't have them because you are e.g. in a train you cannot do anything with crpropa.

This has low priority of course.
