### ISSUE TITLE
Swig not found during compilation

### ISSUE THREAD

**Issue by crpropagithub** [CRPropa/CRPropa3#171]
Hi, I got the following error, when I tried to build CRPropa3.
Please see the output below:

cmake -DCMAKE_INSTALL_PREFIX=/home/CRPropa3_02022018 ..

-- The Fortran compiler identification is GNU 5.4.0
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use --as-needed linker flags!
-- Build Type: Release
-- CRPropa version: 3.1-200-ga3d4138 a3d413809332efdd5c6bd161655a6cf9775fffc2 refs/heads/master
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
Using provided EIGEN
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP Fortran flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Google perftools: Found!
--   Include: /usr/include
-- FFTW3 with single precision (FFTW3F): Found!
--   Include:     /usr/include
--   Library:     /usr/lib/x86_64-linux-gnu/libfftw3f.so
-- Quimby: NOT Found!
--   Include:     QUIMBY_INCLUDE_DIR-NOTFOUND
--   Library:     QUIMBY_LIBRARY-NOTFOUND
-- SAGA: NOT Found!
--   Include:     SAGA_INCLUDE_DIR-NOTFOUND
--   Library:     SAGA_LIBRARY-NOTFOUND
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- muParser: Found!
--   Include:     /usr/include
--   Library:     /usr/lib/x86_64-linux-gnu/libmuparser.so
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.16") 
-- Use absolute RPATH /home/CRPropa3_02022018/lib
-- Downloading data file from crpropa.desy.de ~ 50 MB
-- Extracting data file
-- Found PythonInterp: /home/Python-2.7.14/bin/python (found version "2.7.14") 
-- Found PythonLibs: /home/Python-2.7.14/lib/libpython2.7.so (found version "2.7.14") 
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
-- Python: Found!
--   Version:     2.7/27
--   Executeable: /home/Python-2.7.14/bin/python
--   Include:     /home/Python-2.7.14/include/python2.7
--   Library:     /home/Python-2.7.14/lib/libpython2.7.so
--   Site-package directory: /home/CRPropa3_02022018/lib/python2.7/site-packages
-- Found numpy headers in /home/Python-2.7.14/lib/python2.7/site-packages/numpy/core/include
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/software/CRPropa3_02022018/build

user@pc:~/software/CRPropa3_02022018/build$ make install
Scanning dependencies of target HepPID
[  0%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleIDMethods.cc.o
[  1%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleName.cc.o
[  2%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/Version.cc.o
[  2%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateEvtGen.cc.o
[  3%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateGeanttoPDT.cc.o
[  4%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateHerwig.cc.o
[  4%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateIsajet.cc.o
[  5%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDG.cc.o
[  6%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDTtoGeant.cc.o
[  6%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePythia.cc.o
[  7%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateQQ.cc.o
[  8%] Linking CXX static library libHepPID.a
[  8%] Built target HepPID
Scanning dependencies of target sophia
[  9%] Building Fortran object libs/sophia/CMakeFiles/sophia.dir/sophia_interface.f.o
[  9%] Linking Fortran static library libsophia.a
[  9%] Built target sophia
Scanning dependencies of target dint
[ 10%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/advance.cpp.o
[ 10%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/background.cpp.o
[ 11%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/binfread.cpp.o
[ 12%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/check.cpp.o
[ 13%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/cvector.cpp.o
[ 13%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/decay.cpp.o
[ 14%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/deriv.cpp.o
[ 15%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/error.cpp.o
[ 15%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/final.cpp.o
[ 16%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/fold.cpp.o
[ 17%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/frag.cpp.o
[ 17%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/gauleg.cpp.o
[ 18%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/inject.cpp.o
[ 19%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/io_util.cpp.o
[ 19%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/load.cpp.o
[ 20%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/math_util.cpp.o
[ 21%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prepare.cpp.o
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp: In function ‘void GetModeOfInput(FILE*, int*)’:
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:72:36: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     scanf("%i", pInputMethodSwitch);
                                    ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:81:23: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%s", fileName);
                       ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp: In function ‘void BasicParameterInput(FILE*, int, int*, int*, double*, double*, double*)’:
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:97:36: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pMinEnergyExp);
                                    ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:99:44: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(input, "%i", pNumSmallSteps);
                                            ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:101:49: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(input, "%lf", pConvergeParameter);
                                                 ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:104:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(input, "%lf", pStartingRedshift);
                                                ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:109:53: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(input, "%lf", pStartingDistanceInMpc);
                                                     ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:125:28: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pMinEnergyExp);
                            ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:127:36: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%i", pNumSmallSteps);
                                    ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:129:41: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%lf", pConvergeParameter);
                                         ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:132:40: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%lf", pStartingRedshift);
                                        ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:135:45: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%lf", pStartingDistanceInMpc);
                                             ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp: In function ‘void InteractionParameterInput(FILE*, int, int*, double*, int*, int*, int*, int*, int*, int*, int*, int*, int*, int*)’:
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:171:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(input, "%i", pSynchrotronSwitch);
                                                ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:172:28: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%lf", pB_0);
                            ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:182:45: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pTauNeutrinoMassSwitch);
                                             ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:190:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pICSSwitch);
                                 ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:193:32: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pPPSwitch);
                                ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:196:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pTPPSwitch);
                                 ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:199:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pDPPSwitch);
                                 ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:202:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pPPPSwitch);
                                 ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:205:33: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pNPPSwitch);
                                 ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:208:42: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pNeutronDecaySwitch);
                                          ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:211:48: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pNucleonToSecondarySwitch);
                                                ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:214:46: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pNeutrinoNeutrinoSwitch);
                                              ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:223:40: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%i", pSynchrotronSwitch);
                                        ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:227:31: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%lf", pB_0);
                               ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:235:37: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pTauNeutrinoMassSwitch);
                                     ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:240:25: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pICSSwitch);
                         ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:242:24: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pPPSwitch);
                        ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:244:25: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pTPPSwitch);
                         ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:246:25: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pDPPSwitch);
                         ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:248:25: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pPPPSwitch);
                         ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:250:25: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pNPPSwitch);
                         ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:252:34: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pNeutronDecaySwitch);
                                  ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:254:40: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pNucleonToSecondarySwitch);
                                        ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:256:38: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pNeutrinoNeutrinoSwitch);
                                      ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp: In function ‘void ModelParameterInput(FILE*, int, int*, double*, double*, int*)’:
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:277:47: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(input, "%i", pSourceTypeSwitch);
                                               ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:278:36: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%lf", pMinDistance);
                                    ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:279:39: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%lf", pBrightPhaseExp);
                                       ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:289:39: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  fscanf(input, "%i", pModelTypeSwitch);
                                       ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:302:39: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%i", pSourceTypeSwitch);
                                       ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:308:32: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
      scanf("%lf", pMinDistance);
                                ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:310:35: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
      scanf("%lf", pBrightPhaseExp);
                                   ^
/home/software/CRPropa3_02022018/libs/dint/src/prepare.cpp:315:31: warning: ignoring return value of ‘int scanf(const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
  scanf("%i", pModelTypeSwitch);
                               ^
[ 21%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prop_second.cpp.o
[ 22%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/rate.cpp.o
[ 23%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/spectrum.cpp.o
[ 23%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/sync.cpp.o
/home/software/CRPropa3_02022018/libs/dint/src/sync.cpp: In function ‘void LoadSyncTable(dCVector*, std::__cxx11::string)’:
/home/software/CRPropa3_02022018/libs/dint/src/sync.cpp:12:71: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
     fscanf(syncData, "%lf %lf", &temporary, &((syncTable->vector)[i]));
                                                                       ^
[ 24%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/vector.cpp.o
[ 25%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/DintEMCascade.cpp.o
[ 25%] Linking CXX static library libdint.a
[ 25%] Built target dint
Scanning dependencies of target eleca
[ 26%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Common.cpp.o
[ 26%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/EnergyLoss.cpp.o
[ 27%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Particle.cpp.o
[ 28%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Process.cpp.o
[ 28%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Propagation.cpp.o
[ 29%] Linking CXX static library libeleca.a
[ 29%] Built target eleca
Scanning dependencies of target healpix_base
[ 29%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/error_handling.cc.o
[ 30%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/geom_utils.cc.o
[ 31%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_base.cc.o
[ 31%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_tables.cc.o
[ 32%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/pointing.cc.o
[ 33%] Linking CXX static library libhealpix_base.a
[ 33%] Built target healpix_base
Scanning dependencies of target kiss
[ 33%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/logger.cpp.o
[ 34%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/path.cpp.o
[ 35%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/string.cpp.o
[ 35%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/uuid.cpp.o
[ 36%] Linking CXX static library libkiss.a
[ 36%] Built target kiss
Scanning dependencies of target crpropa
[ 36%] Building CXX object CMakeFiles/crpropa.dir/src/Candidate.cpp.o
[ 37%] Building CXX object CMakeFiles/crpropa.dir/src/Clock.cpp.o
[ 38%] Building CXX object CMakeFiles/crpropa.dir/src/Common.cpp.o
[ 38%] Building CXX object CMakeFiles/crpropa.dir/src/Cosmology.cpp.o
[ 39%] Building CXX object CMakeFiles/crpropa.dir/src/EmissionMap.cpp.o
[ 40%] Building CXX object CMakeFiles/crpropa.dir/src/GridTools.cpp.o
[ 40%] Building CXX object CMakeFiles/crpropa.dir/src/Module.cpp.o
[ 41%] Building CXX object CMakeFiles/crpropa.dir/src/ModuleList.cpp.o
[ 42%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleID.cpp.o
[ 42%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleMass.cpp.o
/home/software/CRPropa3_02022018/src/ParticleMass.cpp:17:21: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
  bool initialized = false;
                     ^
[ 43%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleState.cpp.o
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonBackground.cpp.o
/home/software/CRPropa3_02022018/src/PhotonBackground.cpp:14:21: warning: non-static data member initializers only available with -std=c++11 or -std=gnu++11
  bool initialized = false;
                     ^
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonPropagation.cpp.o
[ 45%] Building CXX object CMakeFiles/crpropa.dir/src/ProgressBar.cpp.o
[ 46%] Building CXX object CMakeFiles/crpropa.dir/src/Random.cpp.o
[ 46%] Building CXX object CMakeFiles/crpropa.dir/src/Source.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/Variant.cpp.o
[ 48%] Building CXX object CMakeFiles/crpropa.dir/src/module/Boundary.cpp.o
[ 48%] Building CXX object CMakeFiles/crpropa.dir/src/module/BreakCondition.cpp.o
[ 49%] Building CXX object CMakeFiles/crpropa.dir/src/module/DiffusionSDE.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMCascade.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMDoublePairProduction.cpp.o
[ 51%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMInverseComptonScattering.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMPairProduction.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMTripletPairProduction.cpp.o
[ 53%] Building CXX object CMakeFiles/crpropa.dir/src/module/ElasticScattering.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/ElectronPairProduction.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o
[ 55%] Building CXX object CMakeFiles/crpropa.dir/src/module/NuclearDecay.cpp.o
[ 56%] Building CXX object CMakeFiles/crpropa.dir/src/module/Observer.cpp.o
[ 56%] Building CXX object CMakeFiles/crpropa.dir/src/module/Output.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputShell.cpp.o
[ 58%] Building CXX object CMakeFiles/crpropa.dir/src/module/ParticleCollector.cpp.o
[ 58%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoDisintegration.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoPionProduction.cpp.o
[ 60%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonEleCa.cpp.o
[ 60%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonOutput1D.cpp.o
[ 61%] Building CXX object CMakeFiles/crpropa.dir/src/module/PropagationCK.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/Redshift.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/SimplePropagation.cpp.o
[ 63%] Building CXX object CMakeFiles/crpropa.dir/src/module/SynchrotronRadiation.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/TextOutput.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/AdiabaticCooling.cpp.o
[ 65%] Building CXX object CMakeFiles/crpropa.dir/src/module/Tools.cpp.o
[ 66%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/JF12Field.cpp.o
[ 66%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticField.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticFieldGrid.cpp.o
[ 68%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/PshirkovField.cpp.o
[ 68%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/ArchimedeanSpiralField.cpp.o
[ 69%] Building CXX object CMakeFiles/crpropa.dir/src/advectionField/AdvectionField.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/Version.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/MagneticLens.cpp.o
[ 71%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ModelMatrix.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/Pixelization.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ParticleMapsContainer.cpp.o
[ 73%] Linking CXX shared library libcrpropa.so
[ 73%] Built target crpropa
Scanning dependencies of target gtest
[ 74%] Building CXX object libs/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 74%] Linking CXX static library libgtest.a
[ 74%] Built target gtest
Scanning dependencies of target gtest_main
[ 75%] Building CXX object libs/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 76%] Linking CXX static library libgtest_main.a
[ 76%] Built target gtest_main
Scanning dependencies of target testPropagation
[ 77%] Building CXX object CMakeFiles/testPropagation.dir/test/testPropagation.cpp.o
[ 77%] Linking CXX executable testPropagation
[ 77%] Built target testPropagation
Scanning dependencies of target testDINT
[ 77%] Building CXX object CMakeFiles/testDINT.dir/test/testDINT.cpp.o
[ 78%] Linking CXX executable testDINT
[ 78%] Built target testDINT
Scanning dependencies of target testSource
[ 79%] Building CXX object CMakeFiles/testSource.dir/test/testSource.cpp.o
[ 80%] Linking CXX executable testSource
[ 80%] Built target testSource
Scanning dependencies of target testAdvectionField
[ 80%] Building CXX object CMakeFiles/testAdvectionField.dir/test/testAdvectionField.cpp.o
[ 81%] Linking CXX executable testAdvectionField
[ 81%] Built target testAdvectionField
Scanning dependencies of target testFunctionalGroups
[ 82%] Building CXX object CMakeFiles/testFunctionalGroups.dir/testFunctionalGroups.cpp.o
[ 82%] Linking CXX executable testFunctionalGroups
[ 82%] Built target testFunctionalGroups
Scanning dependencies of target testMagneticField
[ 83%] Building CXX object CMakeFiles/testMagneticField.dir/test/testMagneticField.cpp.o
[ 83%] Linking CXX executable testMagneticField
[ 83%] Built target testMagneticField
Scanning dependencies of target testModuleList
[ 84%] Building CXX object CMakeFiles/testModuleList.dir/test/testModuleList.cpp.o
[ 85%] Linking CXX executable testModuleList
[ 85%] Built target testModuleList
Scanning dependencies of target testVector3
[ 85%] Building CXX object CMakeFiles/testVector3.dir/test/testVector3.cpp.o
[ 86%] Linking CXX executable testVector3
[ 86%] Built target testVector3
[ 87%] Generating crpropa_wrap.cxx
make[2]: swig: Befehl nicht gefunden
CMakeFiles/crpropa-swig.dir/build.make:131: die Regel für Ziel „crpropa_wrap.cxx“ scheiterte
make[2]: *** [crpropa_wrap.cxx] Fehler 127
CMakeFiles/Makefile2:507: die Regel für Ziel „CMakeFiles/crpropa-swig.dir/all“ scheiterte
make[1]: *** [CMakeFiles/crpropa-swig.dir/all] Fehler 2
Makefile:138: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by TobiasWinchen** [comment]
Hi, apparently swig is not found by make, please check your installation. How did you install swig? What operating system are you using?

**Comment by crpropagithub** [comment]
Thank you for your reply!
OS: Ubuntu 16.04 LTS
I used Synaptic to install swig3.0 (the latest Version 3.0.8-0ubuntu3). 
Running ./configure (please see above) it finds the swig version ("Found SWIG: /usr/bin/swig3.0 (found version "3.0.8")). I also checked, that this is the only swig version on my PC.

**Comment by TobiasWinchen** [comment]
What is the output of `$which swig`

**Comment by crpropagithub** [comment]
Output of "which swig" is: 
/usr/bin/swig

**Comment by TobiasWinchen** [comment]
This is wired - I am speculating now, but it could be that your swig/python installation is messed up as you are using a custom python installation but default swig installation. Could you try using the default python installation instead?

**Comment by TobiasWinchen** [comment]
I assume that this problem has been fixed by now as there has not been an update for three month. Please reopen if this is not the case.
