### ISSUE TITLE
DeflectionCK module

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#173]
Should we drop DeflectionCK?
I see no reason to keep this in the new version and the examples in the wiki use  PropagationCK.
This alias was kept for historical reasons, but now we are dropping the support to older versions altogether anyways, so it might be a good idea to clean things up.
@TobiasWinchen @adundovi what do you think?

**Comment by adundovi** [comment]
This is fine with me - it can be dropped.

**Comment by rafaelab** [comment]
[This commit ](https://github.com/CRPropa/CRPropa3/commit/6c4c60217da11ef48ce6660f2ee0058b857027c3)removes DeflectionCK.
