### ISSUE TITLE
Density distribution of source

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#175]
For specifying source distribution having a uniform density in 3D, I am using
`SourceDensityGrid(scalar_grid)`

In this case, to have a density of 10^-3 Mpc^-3, I write the scalar grid as
`scalar_grid=ScalarGrid(Vector3d(0), 1, 1, 1, 10*Mpc)`

But this doesn't define the distance scale up to which I want the sources to contribute. How can I do that? Should I specify that by the number of grid points Nx, Ny, Nz?

Also what can be the possible spherical alternative to this cubic prescription?

**Comment by lukasmerten** [comment]
If you want to sample from a uniform source distribution you should use `SourceUniformBox`.
You can also use `SourceUniformCyliner`, `SourceUniformShell` and `SourceUniformSphere` for different geometries. See the [`Source`-module](https://github.com/CRPropa/CRPropa3/blob/master/src/Source.cpp)

**Comment by saikat8018** [comment]
Thank you very much for the reply.

**Comment by saikat8018** [comment]
Hi,
I am confused with how to specify the density of sources in a specified distance range? Using `SourceUniformBox( )`, `SourceUniformCylinder( )`, `SourceUniformShell( )` & `SourceUniformSphere( )` doesnt provide me with the option to declare a particular density.

But when I use a scalar grid as an argument for source density, the grid point density gives the source density. But how do I specify the spatial extent of that density? Is it determined by the number of grid points Nx, Ny, Nz in the argument of `ScalarGrid`?

**Comment by TobiasWinchen** [comment]
I assume the issue was resolved as there hasn't been activity here for some time. Please reopen if I am wrong.
