### ISSUE TITLE
Source Redshift Distribution

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#176]
Specifying the redshift distribution of sources by `SourceUniformRedshift( )` implies a random time of emission from a uniform distribution of sources. But does it also specify the distance of the sources according to redshift? Or, do we need to define the spatial distribution separately?

**Comment by rafaelab** [comment]
Hi
Following the [documentation](http://crpropa.github.io/CRPropa3/group__SourceFeatures.html#classcrpropa_1_1SourceUniformRedshift), this function and all other redshift-related classes members of the Source class sets the redshift only. 
In 1D simulations it suffices setting the source distribution with the usual methods and then calling SourceRedshift1D(), but for 3D (actualy 4D) simulations the distribution of sources and redshift are decoupled from each  other.

**Comment by saikat8018** [comment]
Okay, thank you.
