### ISSUE TITLE
Propagation of EM particles as part of the CRPropa simulation chain

### ISSUE THREAD

**Issue by rattallah** [CRPropa/CRPropa3#178]
I would like to propagate EM particles (photons, electrons, positrons) as part of the CRPropa simulation chain (instead of using DINT and/or EleCa).
 I am very interested in the photon code presented in your recent paper  "Production and propagation of ultra-high energy photons using CRPropa 3" (arXiv:1710.1406).
I have found nothing on this in CRPropa examples and tutorials.
I am certainly missing something!?
Regards.

**Comment by cheiter** [comment]
I think we should add some examples like this:

`from crpropa import *`
`sim = ModuleList()`
`sim.add(SimplePropagation())`
`sim.add(Redshift())`
`sim.add(EMPairProduction(CMB,True))`
`sim.add(EMPairProduction(IRB_Gilmore12,True))`
`sim.add(EMPairProduction(URB_Protheroe96,True))`
`sim.add(EMDoublePairProduction(CMB,True))`
`sim.add(EMDoublePairProduction(IRB_Gilmore12,True))`
`sim.add(EMDoublePairProduction(URB_Protheroe96,True))`
`sim.add(EMInverseComptonScattering(IRB_Gilmore12,True))`
`sim.add(EMInverseComptonScattering(CMB,True))`
`sim.add(EMInverseComptonScattering(URB_Protheroe96,True))`
`sim.add(EMTripletPairProduction(CMB,True))`
`sim.add(EMTripletPairProduction(IRB_Gilmore12,True))`
`sim.add(EMTripletPairProduction(URB_Protheroe96,True))`
`sim.add(MinimumEnergy(0.01 * EeV))`
`obs = Observer()`
`obs.add(ObserverPoint())`
`obs.add(ObserverInactiveVeto())`
`t = TextOutput("photon_electron_output.txt",Output.Event1D)`
`obs.onDetection(t)`
`source = Source()`
`source.add(SourcePosition(Vector3d(4,0,0)*Mpc))`
`source.add(SourceRedshift1D())`
`source.add(SourceParticleType(22))`
`source.add(SourceEnergy(1000*EeV))`
`sim.add(obs)`
`sim.run(source,10000,True)`

optional plotting:

`from pylab import *`
`a = loadtxt("photon_electron_output.txt")`
`E = logspace(16,23,71)`
`idx = a[:,1] == 22`
`photons = a[idx,2] * 1e18`
`print photons, E, EeV`
`idx = fabs(a[:,1]) == 11`
`electrons = a[idx,2] * 1e18`
`data,bins = histogram(photons,E)`
`bincenter = (E[1:] -E[:-1])/2 + E[:-1]`
`plot(bincenter, data,label="photons")`
`data,bins = histogram(electrons,E)`
`plot(bincenter, data, label="electrons / positrons")`
`grid()`
`loglog()`
`legend(loc="lower right")`
`xlabel("Energy [eV]")`
`ylabel("Number of Particles")`
`show()`

**Comment by TobiasWinchen** [comment]
Thank you Christopher for the example, I[ added](https://github.com/CRPropa/CRPropa3-notebooks/blob/master/secondaries/photons.v3.ipynb) it to the wiki.
