### ISSUE TITLE
Installation fails at - Linking CXX shared module _crpropa.so

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#179]
Hi,

I am trying to install CRPropa3-3.1 on a server account. Somehow, the installation fails near 88% with the following message:

```
Linking CXX shared module _crpropa.so
/usr/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): 
relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making 
a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: *** [_crpropa.so] Error 1
make[1]: *** [CMakeFiles/crpropa-swig.dir/all] Error 2
make: *** [all] Error 2
```

Can someone please indicate to me what the problem is and how to resolve it since I do not have administrative privileges on the server

**Comment by TobiasWinchen** [comment]
You  are trying to statically link with libpython2.7.a, but this library is not compiled with position-independent code. This is presumably a problem with the python installation as it as not compiled with -fPIC as the error message says. Try linking dynamically with libpython27.so if available or ask the administrator to fix their python installation. Is the dynamic library not available?   Did you decide to use static linking here, or did cmake automatically select the static library?

**Comment by saikat8018** [comment]
I did not decide to use static linking, it was automatically selected by cmake. After I check whether libpython2.7.so is present, how can I try to link it dynamically? It automatically proceeds according to CmakeLists.txt

**Comment by TobiasWinchen** [comment]
You can use  the standard cmake flags to handle such things. In this case it is ```cmake -DPYTHON_LIBRARY=/path/to/lib/you/want/to/link/against``` Manually using this to use the .a lib on my system reproduces the error as expected, see https://bugs.python.org/issue589429

**Comment by saikat8018** [comment]
This issue is solved. Thank you very much for the help
