### ISSUE TITLE
Cannot activate python virtual environment through script

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#183]
Hi,

I am trying to submit a job script for CRPropa simulation in a cluster account. It uses a queuing system for running the scripts. How am I supposed to write a script to activate the python virtual environment?

It fails to run the following command when I add this line in a bash script
`source $CRPROPA_DIR"/bin/activate"`
without any error or output.

But I can activate the virtual environment by including this command 
`/bin/bash -c ". /home/staff/phy/phyroy/.virtualenvs/crpropa/bin/activate; exec /bin/bash -i"`
in the bash script.

But it doesn't go to the next line which contains the .py file for python simulation (eg. 'filename.py'). Only after I enter `exit` (which deactivates the virtual environment), it moves to the next line and fails (as expected). So how can I execute the python script while being inside the virtual environment?

Here is the minimal bash script I am using
```
#!/bin/bash
/bin/bash -c ". /home/staff/phy/phyroy/.virtualenvs/crpropa/bin/activate; exec /bin/bash -i"
python test.py
```

Thank you
saikat

**Comment by adundovi** [comment]
Hi,
check details of your batch system since for me this works just fine:
```bash
#!/bin/bash
source ~/.virtualenvs/crpropa/bin/activate
python -c 'import crpropa; print(dir(crpropa))'
```

**Comment by saikat8018** [comment]
Okay, it is working fine now. Thank you.
