### ISSUE TITLE
Run CRPropa on multiple nodes

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#191]
I am running CRPropa using PBS job scheduler on a cluster computer. It has multiple nodes, each with 32 cores. But, whatever number of nodes I specify in the job script, CRPropa always runs on a single node. It uses all the available cores in a single node but doesn't run over several nodes.

How can I make the code run over multiple nodes? Does OpenMP allow that?

saikat

**Comment by TobiasWinchen** [comment]
If needed, you can e.g. build your own [MPI](https://en.wikipedia.org/wiki/Message_Passing_Interface) application calling CRPropa. [OpenMP](https://en.wikipedia.org/wiki/OpenMP) as we use it does not allow for that.  However, for a lot of use cases it is easier to just start multiple jobs and merge their output.
