### ISSUE TITLE
Cannot store redshift data

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#193]
I want to store the redshift value at the source of injected particles in the output file. I have set the observer as follows, where I have enabled the redshift column.
```
sim = ModuleList()
obs = Observer()
obs.add(ObserverPoint())
output=TextOutput('events.txt', Output.Event1D)
output.enable(output.RedshiftColumn)
obs.onDetection(output)
sim.add(obs)
```
I have defined the source in the following manner
```
source = Source()
source.add(SourceUniform1D(0, redshift2ComovingDistance(5)))
source.add(SourceRedshift1D())
source.add(SourcePowerLawSpectrum(1*EeV, 1000*EeV, -1))
source.add(SourceParticleType(nucleusId(1,1)))
```
But in the output, the redshift column has value zero for all detected events. Why is that? What am I doing wrong? Is this redshift at detection?

**Comment by rafaelab** [comment]
You are running a 1D simulation. 
The output refers to redshift at _detection_. In a 1D setup, this is 0.
You can obtain the redshift of the sources using the source distance stored in the output.
