### ISSUE TITLE
CRpropa installation

### ISSUE THREAD

**Issue by liuwei840305** [CRPropa/CRPropa3#196]
Dear all,
When I installed CRpropa, the process stalled, which shows 

 Using provided EIGEN

 -- Downloading data file from crpropa.desy.de ~ 50 MB

 CMake Error at CMakeLists.txt:264 (file):
   file DOWNLOAD HASH mismatch

     for file:
 [/home/liuwei/Research/PROGRAM/CRPropagation/UHECR/CRPropa3-3.1/build/data.tar
 .gz]
       expected hash: [44aa223904fd896887672b32cead2d65]
         actual hash: [d41d8cd98f00b204e9800998ecf8427e]
              status: [22;"HTTP response code said error"]

 -- Extracting data file

Errors occurred during the last pass                                            
                                                            CMake Version 3.10.2
Press [e] to exit help

Do you know how to solve this problem?
Thank you very much for your reply.

**Comment by rafaelab** [comment]
Hi!
This has  been addressed in issue #153 and supposedly solved.
Do you have the latest version of CRPropa?

**Comment by TobiasWinchen** [comment]
I assume that this issue is resolved by now, if not, please reopen and add more informations.
