### ISSUE TITLE
Absolute normalisation DINT

### ISSUE THREAD

**Issue by Mattver** [CRPropa/CRPropa3#199]
Hi,

I am trying to have an absolute normalisation of the photon flux as given by the DINT module.
However, I don't seem to get the correct result.

Given a local injection of Q = 10^46 erg Mpc^-3 yr^-1, an E^-2 spectrum and a redshift evolution rho(z), I need to convert the number of injected photons into the real number of photons. After interaction, this same number should rescale the output flux to the physical flux. For this, I use
c/4pi  Integral[dz rho(z) / (H(z) (1+z)^2) Q / ln(Emax/Emin) * 1/E^2]
(comoving volume * comoving density * flux from a source at D_L)
with H(z) the Hubble factor and Emin and Emax the minimum and maximum energy at the source.

However, this does not give the correct result, which I can find by comparing with the result without interactions, which is
E^2 dN/dE = c/4pi t_H Q/ln(Emax/Emin)
for no evolution and ignoring the subtleties at the edges.

But, if I replace (1+z)^2 by (1+z), the result is correct using a crpropa simulation without interactions, although I don't really get why. Am I double counting a redshift effect because I use the first formula together with what happens in crpropa?

On the other hand, if I turn off all interactions inside DINT, the total flux is still several orders of magnitude below the correct result or crpropa without interactions alone, even with this change. Ignoring the total normalisation, the relative change between 'without interactions' and 'with interactions' seems to be correct however.

Am I missing something?

Thanks!

**Comment by rafaelab** [comment]
We have dropped the support for DINT and EleCa.  Deprecation warnings were added with #374 .
We encourage users to migrate to the CRPropa-native EM* modules (EMPairProduction, EMInverseComptonScattering, ...) to perform simulations of electromagnetic cascades.
Examples are available in the [documentation](https://crpropa.github.io/CRPropa3). A simple one that can be used to replace DINT/EleCa is [this](https://crpropa.github.io/CRPropa3/pages/example_notebooks/secondaries/photons.v4.html).
