### ISSUE TITLE
Source position in 4D simulations

### ISSUE THREAD

**Issue by tfitoussi** [CRPropa/CRPropa3#201]
Hello,

I'm currently running 4D simulations in which I try to set a specific position of the source. It seems that the position of the source particle is not the same as the source position. To debug my script, I started back from the example given for 4D simulation and adapted it to see what happen when I launch only one candidate. 

here is the [small test script](https://github.com/tfitoussi/test_CR/blob/master/test.py) I wrote. The output is the following: 

source position: 5 0 0 Mpc
CosmicRay at z = -0.050002
  source:  Particle 1000010010, E = 200 EeV, x = 220.04 0 -30.72 Mpc, p = -1 0 0
  current: Particle 1000010010, E = 51.7072 EeV, x = 0.830947 -0.451267 9.70357 Mpc, p = -0.94752 -0.0487481 0.315957
source position: 10 0 0 Mpc
CosmicRay at z = -0.0500093
  source:  Particle 1000010010, E = 200 EeV, x = 225.04 30.72 30.72 Mpc, p = -1 0 0
  current: Particle 1000010010, E = 60.0006 EeV, x = 5.19953 7.16512 -0.10524 Mpc, p = -0.971491 -0.224709 -0.075575
source position: 15 0 0 Mpc
CosmicRay at z = -0.0500049
  source:  Particle 1000010010, E = 200 EeV, x = 230.04 0 -30.72 Mpc, p = -1 0 0
  current: Particle 1000010010, E = 43.2876 EeV, x = 9.24905 13.7151 -14.3594 Mpc, p = -0.93999 0.19678 0.27874
source position: 20 0 0 Mpc
CosmicRay at z = -0.0500018
  source:  Particle 1000010010, E = 200 EeV, x = 204.32 0 -61.44 Mpc, p = -1 0 0
  current: Particle 1000010010, E = 31.6685 EeV, x = -10.9215 8.18949 -9.41742 Mpc, p = -0.959807 0.220502 -0.173634
source position: 1 1 1 Mpc
CosmicRay at z = -0.0500094
  source:  Particle 1000010010, E = 200 EeV, x = 185.32 62.44 31.72 Mpc, p = -1 0 0
  current: Particle 1000010010, E = 49.0076 EeV, x = -13.4574 -2.13831 14.8622 Mpc, p = -0.538332 -0.8415 -0.0455767

Apparently whatever the source position I set, the source particle does not have the same one. Is there something I misunderstood or I did not do correctly in my code?

Thank you for the answer.

Thomas Fitoussi

**Comment by TobiasWinchen** [comment]
Hi Thomas,

the final source positions are adapted by the periodic boundary conditions you choose, see the 
[documentation](http://crpropa.github.io/CRPropa3/group__Condition.html#classcrpropa_1_1PeriodicBox). 

Bests,


Tobi

**Comment by tfitoussi** [comment]
Hi Tobias,

Thank you for the quick answer. 
Indeed, I didn't realize that the source can be moved so far to respect the periodic boundaries. 

Best,

Thomas
