### ISSUE TITLE
Let the run crash when output folder does not exists

### ISSUE THREAD

**Issue by avvliet** [CRPropa/CRPropa3#205]
Perhaps it might be an idea to give a warning message, or an error even, when someone is trying to save the output to a file in a folder that does not exists. At the moment, when this happens, the simulation runs through completely but the output is just lost.

**Comment by TobiasWinchen** [comment]
The simulation should IMO crash immediately in such cases.

**Comment by avvliet** [comment]
> The simulation should IMO crash immediately in such cases.

Yes, that would probably be best.
