### ISSUE TITLE
Add example on usage of EGMF models 

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#206]
On the webpage we write:
"The 'Miniati', 'Dolag' and 'Benchmark' extragalactic magnetic field models on regular grids are available here and the corresponding large-scale structure density fields can be downloaded here. Instructions on how to use them will be added to the examples page soon."

We should o this and update the website accordingly.

**Comment by avvliet** [comment]
Yes, absolutely. This has been on my to-do list for a long time already. I keep on pushing this back, but should really get this done. I will try to find some time to get this done in the next week or so.

**Comment by TobiasWinchen** [comment]
I guess the clues example is enough to close this.
https://github.com/CRPropa/CRPropa3-notebooks/blob/master/extragalactic_fields/MHD_models.v4.ipynb
