### ISSUE TITLE
Accounting for synchrotron emission

### ISSUE THREAD

**Issue by authule** [CRPropa/CRPropa3#207]
Hello,
I am trying to simulate an UHE photon initiated electromagnetic cascade, and when including Synchrotron radiation into the list of EM interactions, the job gets killed. Could you please suggest the way of avoiding the issue?

**Comment by rafaelab** [comment]
Hi,
This is probably a memory issue. 
Are you setting the second argument of SynchrotronRadiation() to false?
 
If this is a memory issue, there is no work around it as the number of secondaries increase exponentially exceeding the memory.

**Comment by authule** [comment]
Hi Rafael,
Thanks for the prompt response,

The situation I've described was for setting the second argument to True, because I wanted to account for the photons emitted via synchrotron as well. And you are right, the reason for killing the job is exceeding the memory at some point. Do I understand correctly, that nothing could be done with that at the moment and I have to skip accounting for synchrotron so far?

Best regards,
Alex

**Comment by rafaelab** [comment]
I don't know what is your specific problem, but often most of the synchrotron photons are in a region below what CRPropa can do (~10 GeV). For many problems this should be enough.

You may also run into problems if the number of UHE photons you are using is too high, even without accounting for synchrotron. 
There is nothing that you can do about it now. Perhaps, simulate one particle at a time. 

We are working on a thinning procedure to prevent this kind of issue. It'll be released in the future with CRPropa 3.2. For the time being, you might want to consider using DINT, a module that solves transport equations.

**Comment by authule** [comment]
Thank you very much, I will follow your suggestions!

**Comment by lukasmerten** [comment]
I close for now, when @rafaelab's are not working please reopen.
