### ISSUE TITLE
Preparation for pullrequest | Data-Files

### ISSUE THREAD

**Issue by JulienDoerner** [CRPropa/CRPropa3#208]
I prepare a pull request for gas density models of the Milky Way. 
There are several models for the distribution of hydrogen. To implement the Model of Pohl et al. (https://arxiv.org/abs/0712.4264) are 2 txt-Files needed. One for the H2 (described in the arXiv paper) and one for the HI component (private communication). 
How can I get these files in the data-folder?

**Comment by TobiasWinchen** [comment]
The data files/scripts to generate them are stored in a separate repository: https://github.com/CRPropa/CRPropa3-data

However, it might be better to distribute the datafiles separately as e.g. the magnetic field data. How large are the files?

**Comment by JulienDoerner** [comment]
The files have together 57 MB. This should not take to long in download. Therefore it should be no problem to include them.

**Comment by adundovi** [comment]
We could put them in our data web location, but I would still like to keep them as an optional addition (not included by default). Are they required for the basic functionality?

**Comment by lukasmerten** [comment]
They are not required for the basic functionality but only for one specific (Pohl et al.) model of the Galactic mass distribution.

@adundovi Could explain (via e-mail) me how to upload the files to the weblocation?

**Comment by TobiasWinchen** [comment]
As these data files are larger then the total current download I would prefer also to have them as additional download.

**Comment by lukasmerten** [comment]
As we have decided to have the data files as an optional/manual download, I close this issue. When the Pohl field is implemented I will take care of the upload of the data into our desycloud.
