### ISSUE TITLE
some thing is wrong with calc_photodisintegration.py 

### ISSUE THREAD

**Issue by zhucr** [CRPropa/CRPropa3#209]
when I use the calc_photodisintegration.py , the output will be like this:
CMB
/CRPropa3-data-master/photonField.py:30: RuntimeWarning: overflow encountered in exp
  return 8*np.pi / c0**3 / h**3 * eps**2 / (np.exp(eps/(kB*T_CMB)) - 1)
Traceback (most recent call last):
  File "calc_photodisintegration.py", line 90, in <module>
    B1[s] /= sum(B1[s], axis=0)
TypeError: sum() takes no keyword arguments
how can I fix it?

**Comment by adundovi** [comment]
The runtime warning is not related to the type error which interrupted the execution of the script. One should add only np. in front of those two sum() functions and it should work. I'll do the same it in the repository so you can just pull changes.

**Comment by zhucr** [comment]
Thanks very much.
