### ISSUE TITLE
GMF and EGMF simultaneously

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#212]
Hi,

Can someone please tell me whether it is possible to add galactic and extragalactic magnetic fields simultaneously in the same 3D simulation? If so, how should I define the propagation module argument? For example, if I have,
```
Bfield1 = PshirkovField()
Bfield2 = MagneticFieldGrid(random_turbulent)
```
Then how can I define the argument of `PropagationCK` module in the simulation? Also, what will be the periodic boundary conditions in this case?

**Comment by adundovi** [comment]
In principle you can implement a custom field which combines those two, and provide it to `PropagationCK`. For example, something like this:
```
class MyCustomField(MagneticField):
    def __init__(self, first, second):
        MagneticField.__init__(self)
        first_field = first
        seconf_field = second
        
    def getField(pos):
        return (first.getField(pos) + second.getField(pos))
    
field = MyCustomField(JF12Field(),
                      UniformMagneticField(Vector3d(1*nG, 0, 0)))
m = PropagationCK(field)
```
Boundaries are defined on the level of original fields, i.e., they are property of magnetic fields, thus you should take care of boundaries before putting those two fields together.

**Comment by adundovi** [comment]
Doh, I totally forgot - there is already [`MagneticFieldList`](http://crpropa.github.io/CRPropa3/group__MagneticFields.html#classcrpropa_1_1MagneticFieldList) that combines magnetic fields just like I described above.

**Comment by saikat8018** [comment]
Okay. Thank you very much. This helps
