### ISSUE TITLE
Implementing new TF17 GMF model

### ISSUE THREAD

**Issue by MRCWirtz** [CRPropa/CRPropa3#214]
Philippe Terral and Katia Ferriere recently developed a new galactic magnetic field model and improved the halo X-field of the large scale component, by testing 4 different analytical models against RM data:
https://arxiv.org/abs/1611.10222

I am about to implement this field in CRPropa. It should give much better comparison than e.g. the PT11 field, which is implemented so far...

**Comment by adundovi** [comment]
@MRCWirtz Did you implement the TF17 GMF model? We have PR #258 with it...

**Comment by MRCWirtz** [comment]
@adundovi in my version there was still something faulty and I stopped developing it when I noticed about the really high field amplitudes in the vicinity of the center (see also in Thomas PR). As the new PR have all versions of the field model implemented, I deleted my active branch now.

**Comment by TobiasWinchen** [comment]
Closed by https://github.com/CRPropa/CRPropa3/pull/259
