### ISSUE TITLE
Different spectrum from different methods to apply redshift evolution

### ISSUE THREAD

**Issue by saikat8018** [CRPropa/CRPropa3#217]
Hi,

I want to have sources at distances, which equals their redshift taken from a distribution (1+z)^m. I have been applying a weight factor of (1+z)^m to output events of uniform source distribution while putting them in energy bins post-simulation. I convert the 1D trajectory length to redshift for the purpose. But this produces a spectrum different from the one obtained by direct implementation of SourceRedshiftEvolution in the simulation. The latter uses a custom module according to the suggestion in #134 :
```
class MySourceFeature(SourceFeature):
    """ Set the distance according to the redshift """
    def prepareCandidate(self, candidate):
        z = candidate.getRedshift()
        d = redshift2ComovingDistance(z)
        candidate.source.setPosition(Vector3d(d, 0, 0))
        candidate.created.setPosition(Vector3d(d, 0, 0))
        candidate.current.setPosition(Vector3d(d, 0, 0))
        candidate.previous.setPosition(Vector3d(d, 0, 0))

source = Source()
source.add(SourceParticleType(nucleusId(1, 1)))
source.add(SourcePowerLawSpectrum(0.1*EeV, 1000*EeV, -1.0))
source.add(SourceRedshiftEvolution(3.0, 0.0, 2.0))
f = MySourceFeature()
source.add(f)
```
I have attached a plot showing the disparity between the two. Can someone please tell me what can be the reason for this?
![proton_spectrum](https://user-images.githubusercontent.com/28901533/50326467-8c1f7c00-0510-11e9-9d59-ec644eb3b654.png)

**Comment by rafaelab** [comment]
Hi!
I tried it and I cannot reproduce the discrepancy at low energy.
In the first case (blue), I reweight the result of the simulation (assuming uniform distribution of sources) by (1+z)^3, without calling the function SourceRedshiftEvolution. In the second case (orange), I call this function with your custom module.
How are you obtaining the weighted curve in your example?

![image](https://user-images.githubusercontent.com/3259791/56085879-baa7c680-5e21-11e9-8f11-718d878d83a7.png)

**Comment by saikat8018** [comment]
While putting the detected events in energy bins, I apply weight to the events according to (1+z)^m. I calculate the redshift from the distance traveled by the cosmic rays from the source to the observer in the 1D simulation.

```
z = redshift2ComovingDistance(D*Mpc)
J1 = histogram(lEf1[idx1], bins = lEbins, weights =(1+z1[idx1])**m)[0]/dE
```

**Comment by rafaelab** [comment]
Can you check if using ```z = lightTravelDistance2Redshift(D*Mpc)``` improves the agreement?

**Comment by saikat8018** [comment]
With `z = lightTravelDistance2Redshift(D*Mpc)` I get the following error:
`RuntimeError: Cosmology: d>dmax`

**Comment by rafaelab** [comment]
You are doing:
```J1 = histogram(lEf1[idx1], bins = lEbins, weights =(1+z1[idx1])**m)[0]/dE```
Is z1 obtained from the output using lightTravelDistance2Redshift or comovingDistance2Redshift?
Is z1 the same as z?

**Comment by saikat8018** [comment]
Hi Rafael,

z1 is obtained using comovingDistance2Redshift. z1 is the same as z

**Comment by rafaelab** [comment]
Either way, I am failing to reproduce the problem.

What I did: I ran the simulation using
```
	source.add(SourceUniform1D(0, redshift2ComovingDistance(2.)))
	source.add(SourceRedshift1D())
```
and then multipled by (1+z)^3.

The other way is using the piece of code you sent, without weighting by (1+z)^3, as the output is already weighted accordingly.

**Comment by saikat8018** [comment]
Dear Rafael,

I defined the source in a similar way. When you multiply by (1+z)^3, do you use `lightTravelDistance2Redshift(D*Mpc)` 
or 
`comovingDistance2Redshift(D*Mpc)` ?

**Comment by rafaelab** [comment]
Hi again,

It should be the comoving distance.

I'm checked what's going on in your case and now I can reproduce your issue if I go to high redshifts. 

I don't know what the issue is, but my guess is that there is an inconsistency in the way things are done. If you take a look at [Source.cpp](https://github.com/CRPropa/CRPropa3/blob/master/src/Source.cpp), line 624, you'll see how a uniform distribution of sources in 1D is generated using SourceUniform1D. After the positions are defined, SourceRedshift1D is called to assign the redshifts. The function SourceRedshiftEvolution is more adequate for 3D/4D simulations when the source positions are decoupled from the redshift distribution.

Because the uniform distribution in the former case is obtained in the physical (not the comoving) volume, then converted to comoving, and then assigned the corresponding redshifts, similar procedure should be applied. The reason for this is that the comoving distance is the intergral of H(z), whereas the light-travel distance is the integral of H(z)/(1+z). Therefore, computing the redshift before and after the position of the sources are defined do make a difference because they don't commute (z is inside the integral).
Only for small z will you obtain a match.

This is just a guess, but I think it makes sense. 
Therefore, if you really want to have the evolution in the simulations instead of using an a posteriori reweighting, I recommend you to try first to compute the positions and only then assigning the redshifts. 

I will keep the ticket open until you check if a writing a new custom module from scratch solves the problem.

**Comment by saikat8018** [comment]
Hi Rafael,

Thank you very much for the clarification. How can I write a module that will first compute the position and then the redshift? Because when I define `source.add(SourceRedshiftEvolution(3.0, 0.0, 2.0))` the redshift will be defined first. Also, the problem disappears for m=0 in (1+z)^m.

**Comment by rafaelab** [comment]
Writing such a module is not as trivial as writing the module you did before. I don't know an easy way to do it. I would probably play around with the weights and follow the SourceUniform1D example, combined with the SourceRedshiftEvolution, in a single module. The weights of the random numbers in the SourceUniform1D would need to change to include the (1+z)^m  behaviour.

If the problem disappears for m=0, then I think what I'm saying might be the case, although I'm not sure.

May I ask why can you not reweight it a posteriori? IT's simpler and we know it works.

**Comment by saikat8018** [comment]
Dear Rafael,

Yes, I can obviously reweight the events a posteriori and I have been doing so. But while propagating photons using DINT, the events cannot be reweighted afterward. This is the reason I asked how can I implement redshift evolution in the simulation itself.

**Comment by rafaelab** [comment]
I see.
Then I can suggest a solution that's probably easier than writing the module and faster than running the simulations for every spectral index.
The produced photons can be written in an intermediate output which is then passed to DINT. You can  store this file and generate files in the exact same format. Just sample the events in this file according to a given acceptance law (generate a random number, compare with weight, accept or reject event); this will mimick the distribution you want.
Unfortunately, I don't have any example to provide.

**Comment by saikat8018** [comment]
Hi Rafael,

I have the intermediate output before passing it to DINT. I may sound foolish but I didn't understand the acceptance procedure - to what way should I compare the random numbers?

**Comment by rafaelab** [comment]
Essentially, you should compare the random numbers with the weights of a given event.
Look for the acceptance-rejection sampling method (or simply [rejection sampling](https://en.wikipedia.org/wiki/Rejection_sampling)). This is a widely used Monte Carlo technique.

**Comment by saikat8018** [comment]
Okay, Rafael. Thank you very much. I will look into this method. Does the normalization constant obtained from the corresponding CR spectrum remain the same by this, i.e. to say is the same normalization applicable to the obtained photon spectrum?

**Comment by rafaelab** [comment]
When you apply this procedure to the photon output only, the normalisation changes with respect to the CR output. I don't know what the best way to normalise is. 
(I'm not sure) If all the weights that you use in the reweighting of the CR data are in the 0-1 interval, than the reweighting and rejection  are approximately the same and you get the same normalisation. But you should check it.

**Comment by saikat8018** [comment]
Thank you, Rafael, for the help. I will try this
