### ISSUE TITLE
DINT energy conservation

### ISSUE THREAD

**Issue by Vossmax** [CRPropa/CRPropa3#219]
Hi,

I tried to reproduce the photon flux calculated by the ELMAG code with CRPropa using DINT propagation. Since ELMAG and DINT don"t share an identical EBL model, I implemented the model by Gilmore (2012) in the background.cpp file of DINT. In the following plot you see my result.
![cr-elm2](https://user-images.githubusercontent.com/47029650/51746175-82f07480-20a5-11e9-975c-7d18f554e2cf.png)
The Normalisation is not the same, so I just fitted the lines manually. However, the shapes of the fluxes differ significantly. Both are simulated without magnetic field.

Could I have made a mistake in the implementation or is there a general energy conservation issue in DINT?

Thanks!

**Comment by rafaelab** [comment]
We dropped the support for DINT and EleCa in previous releases. Deprecation warnings were added with #374. 
We encourage users to migrate to the CRPropa-native EM* modules (EMPairProduction, EMInverseComptonScattering, ...) to perform simulations of electromagnetic cascades.
Examples are available in the documentation. A simple script that can be used to replace DINT/EleCa for extragalactic propagation is available [here](https://crpropa.github.io/CRPropa3/pages/example_notebooks/secondaries/photons.v4.html).
