### ISSUE TITLE
Bug in beta decay

### ISSUE THREAD

**Issue by MichaelUnger** [CRPropa/CRPropa3#22]
Dear CRPropa3 devels,

I think at the end NuclearDecay::betaDecay() instead of 
```
    if (haveElectrons)
	// add electron/positron boosted to lab frame
        candidate->addSecondary(electronId, gamma * E * (1 + p * cosTheta));
```
it should be 
```
    if (haveElectrons)
        // add electron/positron boosted to lab frame
        candidate->addSecondary(electronId, gamma * (E + p * cosTheta));
```
(wrong Lorentztransformation, even units don't make sense).

Similar for neutrinos, where you currently have 
```
	candidate->addSecondary(neutrinoId, gamma * (Q - E) * (1 - p * cosTheta));
```
please change the Lorentz transformation. Moreover, I would not use p_e but T_nu for the momentum and finally (Q-E) is not the neutrino kinetic energy, but (Q- T), since Q here is m_n - m_p - m_e:
```
        candidate->addSecondary(neutrinoId, gamma * (Q - T) * (1 - cosTheta));
```
Makes quite some difference :)

The bug would probably have been spotted earlier if you did not silently ignore negative energies in ParticleState::setEnergy() where
```
        energy = std::max(0., newEnergy); // prevent negative energies
```
Maybe you should add a warning output here?

Cheers,
Michael

**Comment by DavidWalz** [comment]
Thanks for spotting!
