### ISSUE TITLE
Memory requirements for photon-initiated EM cascade

### ISSUE THREAD

**Issue by authule** [CRPropa/CRPropa3#223]
Dear all,

I am trying to propagate a 10^20 eV photon in a turbulent magnetic field to study the distribution of product particles, cutting their energy at 1 TeV (8 decades margin), aiming at 9 decades (10^21 eV photon). At propagation distances over 50 Mpc it starts running out of memory. Currently I am limited with 120 Gb of memory. Could anyone provide any estimations (or ideas) of memory needed to run the job successfully, please? 

Thanks in advance and sorry for too naive question,
Alex

**Comment by adundovi** [comment]
Hi Alex, your question is certainly not naive, but only hard to answer (and estimate). You could use `ParticleCollector`, for example, to save the state of your simulation (all particles) at some point earlier and then continue with it using only a portion of them from it...

**Comment by authule** [comment]
Thank you very much for the response, Andrej, I will try to
