### ISSUE TITLE
lack of secondary protons or neutrons in the PhotoPionProduction?

### ISSUE THREAD

**Issue by Froehliche-Kernschmelze** [CRPropa/CRPropa3#225]
Dear all,

from the current implementation of the treatment of secondary particles in the `PhotoPionProduction` it seems that there would no secondary non-antinucleons be added shall they be created in SOPHIA. My concerns evolve around

https://github.com/CRPropa/CRPropa3/blob/bd39f844217a02c7b5f4d3f6a67d88d22617650a/src/module/PhotoPionProduction.cpp#L235-L269

**How this part of the code (currently) works:**

* `double nParticles`, `particleList[2000]`, and `double momentaList[5][2000]` are return values of SOPHIA. The first is the number of out-going particles from the SOPHIA event generator **including** the primary proton or neutron. The second contains the SOPHIA-intern particle IDs of these particles. The third contains each their x,y,z momentum, energy and rest mass. These arrays have the size of 2000 to account for very large secondary outputs as variable array sizes may not have been implementable when the SOPHIA/C++ junction was written.
* Each time SOPHIA was called, there is a loop of length `nParticles` over these lists checking in a switch for the corresponding particle ID. 13 and 14 correspond to protons and neutrons respectively whereas -13 and -14 denote their anti-particles
* in each branch of the switch that is not among (13,14,-13,-14), i.e. the secondary leptons and photons, there will the corresponding particle be added as a secondary unless the user opts these out.
* For hadrons this treatment discriminates between whether the incoming hadronic particle was a nucleus with mass number >1 or a single nucleon.

**what I think where the bug is (if any)**
For simplicity assume that there is an incoming very-high-energy proton undergoing photo-hadronic interactions in the PPP. The CM energy is sufficiently high to produce a single proton/anti-proton pair. The SOPHIA output therefore looks something like:
* `nParticles = 1337`
* `particleList = [13, 13, -13, (lots of non-hadrons)]` where the first 13 is the primary and the second belongs to the hadron pair.
* `momentaList = [ [px0, py0, pz0, E0, m], [px1, py1, pz1, E1, m], [px2, py2, pz2, E2, m], [all the rest] ]`
The switch `case 13:` at line 239 therefore triggers the if statement `if (A == 1)` at line 241 (as the primary was a proton) which directly, and this is where I see the bug, leads to  `candidate->current.setEnergy(Eout);`. **Problem:** the candidate's energy would be overwritten as many times as there are non-antinucleonic particles in the output particles of SOPHIA and therefore only gain the energy of the last non-antinucleonic particle in SOPHIA's output list (which in this example is the second 13). In this example this would be the value of E1.

**what the scope of this bug would be (if it's real)**
1) This is only relevant if the CM energy is sufficient to produce nucleon/anti-nucleon pairs in SOPHIA
2) If so, the primary's energy will be overwritten as many time as there are 13's or 14's in the output list and hence only be assigned the energy of the last of these IDs' energy values. This may lead to significant energy leakages as the energies of the nucleon/anti-nucleon pairs usually is not in the order of the primary particle
3) As a consequence of the very same architecture, there is always only one non-antinucleonic particle being produced by the PPP, i.e. one proton or one neutron (and possibly several anti-nucleons). That suggest that the vast amount of data produced so far should not be affected except for where anti-nucleons were produced
4) Despite it's severity, there is almost no occasion where the CM energy is sufficient for nucleon/anti-nucleon interactions as SOPHIA only samples photons from the CMB or the IRB_Kneiske04 as pointed out in #220. Photons here lie in the order of 1e-4 to 1 eV which requires very high hadron energies for nucleon/anti-nucleon production (but I do not have precise numbers on the exact likeliness of this to occur)
5) However, if we move towards photon fields of higher energies, this effect becomes more prominent if not dominant

**what I suggest doing**
* I observe that the first proton or neutron listed in `particleList` corresponds to the primary particle whereas all further 13's and 14's belong to the corresponding -13 and -14 counterparts.
* A fix could be as easy as to have a `bool isPrimary = True` flag in the output treatment that flips if the first 13 or 14 has been found. If true, the candidate's energy is set equal to the out-going energy value (as currently implemented) whereas if false a corresponding secondary nucleus will be added.

Please let me know your thoughts. I am happy to provide any more information I have but this pretty much summarises the vast amount. All the best,

~ Mario

**Comment by Froehliche-Kernschmelze** [comment]
There is a minimal code example of how to reliably reproduce the bug. This script generates a nucleon output file in which there should be a handful of anti-nucleons. However, the total amount of output nucleons is always

N_nucleonsInjected + N_antiNucleons

as opposed to

N_nucleonsInjected + **2** * N_antiNucleons

Also, note that a neighbour entry of most anti-nucleons usually shows an energy lying in the order of the anti-nucleon (usually orders of magnitude lower than most other nucleons). This corresponds to the energy of the actual pair partner of the anti-nucleon and is a result of the process of repeatedly overwriting the primary's energy.

<pre>
from crpropa import *

neutrinos = True
photons = True
electrons = True
antiNucleons = True

# module setup
sim = ModuleList()
sim.add(SimplePropagation(1e1 * kpc, 1e2 * kpc))
sim.add(PhotoPionProduction(IRB_Stecker16_upper, photons, neutrinos, electrons, antiNucleons))

# observer for hadrons
obs1 = Observer()
obs1.add(ObserverPoint())
output1 = TextOutput("out-nucleons.txt", Output.Event1D)
obs1.onDetection(output1)
obs1.add(ObserverNeutrinoVeto())
obs1.add(ObserverPhotonVeto())
obs1.add(ObserverElectronVeto())
sim.add(obs1)

# all other particles
obs2 = Observer()
obs2.add(ObserverPoint())
output2 = TextOutput("out-rest.txt", Output.Event1D)
obs2.onDetection(output2)
obs2.add(ObserverNucleusVeto())
sim.add(obs2)

# source
source = Source()
source.add(SourcePosition(Vector3d(10 * Gpc, 0, 0)))
source.add(SourceParticleType(nucleusId(1, 1)))
source.add(SourceEnergy(1e13*GeV))

sim.setShowProgress(True)
sim.run(source, 1000, True)

**Comment by adundovi** [comment]
I'll look into this. BTW maybe referencing the [CRPropa2 implementation](https://github.com/CRPropa/CRPropa2/blob/master/src/Interactions/sophiainteractions.cc) could be of some help.

**Comment by adundovi** [comment]
Thanks Mario for a really detailed and easy-to-follow description of the issue. I've read your comments and run your example, also recalled some of the theory of hadronic interactions with photons.

I agree that this is a bug. If I remember the PPP mechanism correctly, for 1000 injected protons in your example we would have to record at least the comparable number of nucleons and anti-nucleons on top of injected protons (e.g. p + gamma -> p + p + \bar{p} + rest) . Which we don't. My output is 1385 nucleons, of which 378 are anti-nucleons, i.e.
> N_nucleonsInjected + N_antiNucleons + N_Nucleons (where N_antiNucleons == N_Nucleons)

I also agree with the suggested fix, although I don't know how can you be sure that the first 13 or 14 in the list is the primary particle? Is this evident from the SOPHIA code?

**Comment by adundovi** [comment]
As you already studied SOPHIA in great detail, I would recommend inserting more code comments in the source of the PPP module which would describe better how CRPropa interacts with SOPHIA. Otherwise, I presume that in a few years someone could again stumble on it trying to understanding what is going on. :-) Thanks again for your work!

**Comment by adundovi** [comment]
If the primary particle is always the first in the list, we don't need `bool isPrimary = True`, we need only to iterate from 1 to n in the for loop, while the zeroth case handle separately.

**Comment by Froehliche-Kernschmelze** [comment]
> As you already studied SOPHIA in great detail, I would recommend inserting more code comments in the source of the PPP module which would describe better how CRPropa interacts with SOPHIA. Otherwise, I presume that in a few years someone could again stumble on it trying to understanding what is going on. :-) Thanks again for your work!

Thanks :) I fully understand how CRPropa and SOPHIA interact with each other and I am happy to provide documentation on this (yet I do not fully understand all of SOPHIAs interiors up to this level). This will be included in the pull requests that follow this bug fix as I am about to introduce changes to this part of the code.

**Comment by Froehliche-Kernschmelze** [comment]
> I also agree with the suggested fix, although I don't know how can you be sure that the first 13 or 14 in the list is the primary particle? Is this evident from the SOPHIA code?

I have run analyses on the output behaviour and came to the conclusion that the primary is not always on the zeroth position of the output lists, although in the very vast majority of the cases. There are exceptions where even a non-hadronic particle assumes this position.

I achieved these insights by wrapping SOPHIA to a custom python script via f2py, generating files of SOPHIA raw output data. The data consists of output particle lists of 100.000 events each at the input parameters E_in = {1e5, 5e5, 1e6, ... 5e11, 1e12} GeV (= 23 hadron energy values) each combined with an incident photon energy of eps = {1e-3, 5e-3, ..., 5e2, 1e3} eV (= 13 photon energy values). Among the possible 23x13=299 combinations there were 234 combinations where the CM energy was sufficient for PPP. Hence my observations are based on 234 x 100.000 events.

Nevertheless, it seems that the proton or neutron of the highest energy in the output list corresponds to the primary and therefore I suggest to follow this approach and apply this to the output treatment.

Current status of insights/summary:
* treat zeroth entry as primary: No, because this position is not even always hadronic
* treat first neutron or proton as primary: No, because in a few cases there are secondary protons or neutrons listed prior to the primary
* treat proton or neutron of highest energy as primary: Holds true in all runs of the setup listed above

Please let me know you thoughts on any of what has been described so far! Do you consider a check for max energy feasible?

**Comment by adundovi** [comment]
Thanks for these additional findings. If the zeroth entry were the primary, we would have an elegant solution on how to implement this (our current for-loop would just start from i=1, while the i=0 case would be handled separately). Unfortunately, if the only discriminating property is the highest energy, we need to proceed with your suggestion which means going through the list two times. First to find the highest energy particle (i.e. primary) and then looping over secondaries.

Actually, I'm a bit confused here. Why do we need to treat the primary as a primary after the interaction at all? Physically, all particles on the left-hand side of the interaction are by-products, i.e. secondaries, and the notion of the primary is lost.

**Comment by Froehliche-Kernschmelze** [comment]
I think the discrimination is that CRPropa can keep track of a candidate. The particle that leaves the process with a modified energy is modified by
`candidate->current.setEnergy(Eout);`
as opposed to any secondary that emerges from it:
`candidate->addSecondary(sign * nucleusId(1, 14 - pType), Eout, pos);`

If no discrimination were made one would lose the history of any candidate entering the PPP (at least as far as I understand that). Also one would have to deactivate every incoming candidate and inject nParticles x new candidates into CRPropa.

**Comment by adundovi** [comment]
Yes, that is true. But on the other hand, the fact that in essence there is no "original primary" after PPP could explain why SOPHIA does not give any special place to the highest energy particle. For the sake of consistency with the previous behaviour let's follow your suggestion of labeling the highest energy nucleon in the output list as the original particle.
