### ISSUE TITLE
Galactic + Extragalactic To earth Propagation

### ISSUE THREAD

**Issue by ToonLinkZ** [CRPropa/CRPropa3#227]
is it possible to simulate the propagation of UHECRs from a source with extragalactic distances(~100Mpc) all the way to a small observer (representing the earth) with ~pc radius.

Basically I'd like to find out the exact energy,arrival directions of cosmic rays as they reach the earth.

Is this too much for the software even if I have a cluster?

If this is not possible, what would be another method to get the arrival directions, energies of extragalactic comiscrays as they reach the earth?

**Comment by lukasmerten** [comment]
Hi @ToonLinkZ , 
of course it is in principle possible to use such a small observer (~pc size). However, this will probably be computationally very expensive. A good solution for your problem might be to use the so called Galactic lenses (have a look at this [example](https://github.com/CRPropa/CRPropa3-notebooks/tree/master/galactic_lensing)). Here, the particles are mapped from a large(r) observer sphere to arrival direction on Earth, assuming that no further losses occur on this _last mile_.
Best Lukas

**Comment by adundovi** [comment]
@ToonLinkZ, like @lukasmerten said, in practice, simulating an extragalactic scenario with a single parsec-size observer will not give you enough events (if any) independent of the size of a cluster. Imagine if you injected CRs homogeneously everywhere in a 100Mpc simulation box, you would need to put 10^23 particles to observe by chance one within your observer:

    >>> (100*Mpc)**3/(4./3.*M_PI*(pc)**3)
    2.38732414637843e+23

CRPropa can process approx. 10^5 particles/s/thread on modern hardware without any interactions added. As you can see, there is many orders of magnitude difference.
