### ISSUE TITLE
1D Simulation with Trajectory

### ISSUE THREAD

**Issue by rprechelt** [CRPropa/CRPropa3#230]
I *slightly* modified the 1D example [here](https://github.com/CRPropa/CRPropa3-notebooks/blob/master/sim1D/sim1D.v4.ipynb) to support neutrino generation/detection (using the code below). I place a source at 1Mpc, an observer at x=0, and only detect neutrinos. Since this is in 1D, I (perhaps naively) expect all trajectories to be ~1Mpc in length. When I histogram the trajectory length of the detected neutrinos, the vast majority are exactly 1Mpc in length but I also get trajectory lengths up to 14Gpc (plot [here](https://ibb.co/748R0bt)). 

In my understanding of the CRPropa 1D methodology, sources are propagated towards the origin from the source and hence they should all be detected after ~1Mpc - I fail to see how the 1D physics can generate a path length 10^4 larger (>14Gpc).

Am I missing something? Is this the expected behaviour? 

<details><summary>Code to reproduce</summary>

    def simulate(filename: str, N: int, distance: float, min_energy: float = 1, power: float = -1):

        # we don't simulate electrons or photons, only neutrinos
        photons = False
        neutrinos = True
        electrons = False
        antinucleons = False
    
        # simulation setup
        sim = ModuleList()
        sim.add(SimplePropagation(1*kpc, 10*Mpc)) # these are minimum and maximum step sizes
        sim.add(Redshift()) 

        # add physics 
        sim.add(PhotoPionProduction(CMB, photons, neutrinos, electrons, antinucleons))
        sim.add(PhotoPionProduction(IRB, photons, neutrinos, electrons, antinucleons))
        sim.add(PhotoDisintegration(CMB))
        sim.add(PhotoDisintegration(IRB))
        sim.add(NuclearDecay(electrons, photons, neutrinos))
        sim.add(ElectronPairProduction(CMB))
        sim.add(ElectronPairProduction(IRB))
        sim.add(MinimumEnergy(min_energy*EeV)) # minimum energy cut
    
        # create a source at a specified distance
        source = Source()
        source.add(SourcePosition(distance*Mpc))
        source.add(SourceParticleType(nucleusId(1, 1))) # protons!
        source.add(SourcePowerLawSpectrum(min_energy*EeV, 1000*EeV, power))
        source.add(SourceRedshift1D())

        # create the output format
       output = TextOutput(filename, Output.Event1D)
       output.enable(output.RedshiftColumn)

        # create an observer at Earth
        obs = Observer()
        obs.add(ObserverPoint())
        obs.add(ObserverNucleusVeto()) # we only want to detect neutrinos
        obs.onDetection(output)
        sim.add(obs)

        # run simulation
        sim.setShowProgress(True)
        sim.run(source, N, True)

        # and explicitly close the output file
        output.close()

    simulate('test.dat', 100, 1, 1, -1)

</details>

**Comment by rafaelab** [comment]
Hi!
Thanks for reporting this. I confirm this odd behaviour. It is a bug. 
There seems to be something going on with the vetoes. If you remove the ObserverNucleusVeto, then  the problem doesn't occur.
While this bug is fixed, I recommend you to remove the veto and separate neutrinos and cosmic rays in your post-processing script.

**Comment by TobiasWinchen** [comment]
The issue is here that in this setup the protons continue to propagate after passing x=0 (as they are not detected). If they then create a secondary neutrino, this is immediately detected as the condition for ObserverPoint is x < 0 ... . The solution for the setup would be to remove the particles from the simulation with a second observer, but without output.
