### ISSUE TITLE
Problems with synchrotron process

### ISSUE THREAD

**Issue by authule** [CRPropa/CRPropa3#232]
Hello,
I came across several problems while performing some simulations that involves synchrotron process among others. 

1) The energy lost in each step (dE, in the source code) which sometimes can be much more than the energy of a parent electron. The same dE is "spent" to produce synchrotron photons and as a result, one gets much more total energy of the emitted synchrotron photons than the parent electron. Is there a way to avoid this situation?

2) The text output I get from the simulations. At some cases, I see a parent electron of zero energy producing a bunch of synchrotron photons (with non zero energies). Is there something that I am missing here?

3) The existence of the secondaries with energies less than the cut one (MinimumEnergy) in the output file, though I am not 100% sure this resulted from synchrotron.

Thanks in advance,
Alex

**Comment by rafaelab** [comment]
Hi!
Could you please provide a minimal working example that I can use to reproduce the problem?

**Comment by authule** [comment]
Hi, here you are:

from crpropa import *
E_0= 1 
E_br= 0.000001 
r= 0.002 
B = JF12Field()
randomSeed = 691342
B.randomStriated(randomSeed)
B.randomTurbulent(randomSeed)
sim = ModuleList()
sim.add(PropagationCK(B,1e-4, 0.1 * parsec, 100 * parsec)) 
sim.add(Redshift()) 
sim.add(EMPairProduction(CMB,True)) 
sim.add(EMPairProduction(IRB_Stecker05,True))
sim.add(EMPairProduction(URB_Protheroe96,True))
sim.add(EMDoublePairProduction(CMB,True)) 
sim.add(EMDoublePairProduction(IRB_Stecker05,True))
sim.add(EMDoublePairProduction(URB_Protheroe96,True))
sim.add(EMTripletPairProduction(CMB,True)) 
sim.add(EMTripletPairProduction(IRB_Stecker05,True))
sim.add(EMTripletPairProduction(URB_Protheroe96,True))
sim.add(EMInverseComptonScattering(IRB_Stecker05,True)) 
sim.add(EMInverseComptonScattering(CMB,True))
sim.add(EMInverseComptonScattering(URB_Protheroe96,True))
synch = SynchrotronRadiation(B,True)
synch.setSecondaryThreshold(1*TeV)
sim.add(synch) 
sim.add( MinimumEnergy( E_br * EeV) ) 
obs = Observer()
obs.add(ObserverLargeSphere(Vector3d(0.,0.,0.),r * Mpc))
t = TextOutput( "path/myOutput.txt",Output.Everything) 
t.setLengthScale(1e3*meter)
t.setEnergyScale(TeV)
obs.onDetection(t)
sim.add(obs)
source = Source()
source.add(SourceParticleType(11)) 
source.add(SourceEnergy(E_0 * EeV)) y
source.add(SourcePosition(Vector3d(0.,0.,0.))) 
source.add(SourceRedshift1D()) 
source.add(SourceDirection(Vector3d(0.,1.,0.)))
sim.run(source, 1, True) 
t.close()

Thank you!

**Comment by lukasmerten** [comment]
Due to inactivity for about two years I am closing this issue.

A few notes for people searching the issues:

to 1) When the energy loss per propagation step dE is larger than the (minimum) propagation step is likely too large. Depending on the magnetic field strength and Lorentz factor of the particles a very small propagation might be needed.
to 3) Particles are deactivated when their energy is below the minimum. Therefore, particles with energies below the minimum energy are always expected.
