### ISSUE TITLE
New details of turbulent magnetic fields

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#234]
Hi all!

I'm studying turbulent magnetic field models, and I would like to introduce "less-naive" models (*) in CRPropa, but without breaking the previous results. However, I would also introduce some clean up of the original functions.

First, I split GridTools into two files: **GridTools** and **GridTurbulence**. In the former, I left general grid functions, while in the latter, I put everything related to turbulent fields. The main reason is that the original GridTools source file was way too long, hence, hard to navigate, and overview. Moreover, initTurbulence() had too many parameters which cluttered the interface (especially when used through python which has dynamic typing); thus, I changed the interface by isolating the helical turbulence field into the separate function `initHelicalTurbulence` with the following interface ( @rafaelab ):

```c++
initHelicalTurbulence(ref_ptr<VectorGrid> grid, double Brms, double lMin, double lMax, double alpha, int seed, double H)
```
The original interface for `initTurbulence` stayed the same, so those who didn't use helicity shouldn't notice a difference:

```c++
initTurbulence(ref_ptr<VectorGrid> grid, double Brms, double lMin, double lMax, double alpha, int seed)
```

(*) Although, all so-called synthetic turbulence models could be called naive, by the less naive models, I mean those which comply with known results of homogeneous turbulence (Batchelor, 1953). For example, there is no abrupt cut-off in power of the largest scale eddies. I will submit also comparisons between the naive and less naive models.

**Comment by adundovi** [comment]
See, for example, ref: [Sonsrettee2014](https://iopscience.iop.org/article/10.1088/0004-637X/798/1/59/meta), or [Subedi2017](https://iopscience.iop.org/article/10.3847/1538-4357/aa603a).

**Comment by lukasmerten** [comment]
Hi @adundovi 
In Bochum also some people (@eicheB, @reichherzerp, @antoniusf, and @LeanderSchlegel) are working on new models for the turbulence implementation. Maybe you should get in touch with each other to not do some work twice.

**Comment by adundovi** [comment]
Hi @lukasmerten , OK, I will. Thanks for mentioning this!

**Comment by antoniusf** [comment]
Hi everyone, and thanks for tagging us in. My apologies for chiming in so late; there's been a lot going on.

I can only really talk about the technical side, though I'm sure there are some interesting topics on the physics side as well. As for the former:

I've been working on an implementation that computes the field on-the-fly and is therefore completely independent of `initTurbulence`. The implemention currently lives [here](https://github.com/antoniusf/CRPropa3/blob/field-perf/src/magneticField/TD13Field.cpp), though I hope to have a PR up soon™. How this implementation interacts with other turbulence models is a question that I think we can safely push down the road for a bit.

@LeanderSchlegel has been working on alternative methods for interpolation, which reside in `Grid.h`. Since the interpolation methods technically work on arbitrary grids, they should just plug into any other turbulence generation methods.

So on the technical side I think you're clear. However, again, the physical side is probably more interesting here, since we have been testing all of these methods in physical scenarios, and all of this probably plays together in interesting ways that I absolutely don't understand.

**Comment by adundovi** [comment]
Hello @antoniusf . Thanks for the clarification. Fortunately, numerical simulations of particle propagation in synthetic turbulent fields are extensively covered in literature, both purely isotropic cases and with a background ordered component; thus, we have a lot of references to compare our implementations with. Just to name a few: [Candia 2004](https://arxiv.org/pdf/astro-ph/0408054), [De Marco 2007](https://arxiv.org/pdf/0705.1972.pdf), [Snodin 2016](https://arxiv.org/pdf/1509.03766.pdf). 

In this context, the quantity of interest is almost always the ratio of the particle gyroradius and the correlation length of a turbulent field. While details of a turbulent field implementation for r_g/l_c ~ 1 and > 1 are negligible and lead to similar, and well-understood results, the technical difficulties start for r_g/l_c < 0.1. At those ratios, one hits the resolution of a field grid, thus enters in the non-physical regime, and the simulations results can no longer be trusted. Hence, various alternative approaches to investigate this regime are desirable.

If I understand correctly, what you do with on the fly method is an alternative to fixed grid methods? In that case, it would be interesting to see the results, especially with the well-tested CRPropa trajectory integrators. Regarding the interpolation, IMHO, a better interpolation method would allow peeking deeper in the r_g/l_c < 0.1 regime, but there is a danger of making the getField() method slower compared to the current trilinear interpolation, which the most called function in the diffusive regime of propagation, and that can be a big disadvantage of a better interpolation.

**Comment by antoniusf** [comment]
I am not sure how our tests relate to the r_g/l_c criterion you mention; @reichherzerp probably knows more about this, but I believe he is pretty busy at the moment. Also, we *are* currently finishing up the paper that describes everything we've done so far.

Yes, the on the fly method (nicknamed `TD13`) does not rely on any kind of grid, so it does seem to me that it might avoid the problem you've described. However, in the current implementation, this comes at the cost of providing significantly fewer wavemodes (100 to a few 1000s, if you want acceptable performance, compared to `Nx * Ny * Nz` for the grid-based methods).

I do not know how the interpolation methods fit into this, but I can tell you that performance is something we've been looking into and that we have concrete numbers on.

**Comment by reichherzerp** [comment]
Hello @adundovi, your work looks very useful and in any case complementary to what we do here in Bochum.

> In this context, the quantity of interest is almost always the ratio of the particle gyroradius and the correlation length of a turbulent field. While details of a turbulent field implementation for r_g/l_c ~ 1 and > 1 are negligible and lead to similar, and well-understood results, the technical difficulties start for r_g/l_c < 0.1.
> 
I agree with you, but I would like to add that the relationship between the amplitudes of turbulence and the background field b/B also has an important influence (because it is a differnece if we are in the quasilinear regime or the Bhom-limit). We are working on this right now with CRPopa (we will submit a paper covering this soon).

Exactly, the on the fly method is an alternative to the grid method, especially in the case of smaller ratios of r_g/l_c. With this 'new' method it is possible to guarantee resonant interactions even for these low ratios of r_g/l_c, which is not possible with the grid method (because of the limited RAM and all the conditions that have to be satisfied for l_min and l_max). Thanks to all the optimizations by @antoniusf , this alternative method is still 'relatively' fast even with many wave modes.

We have tested the various effects that falsify the calculations when the ratios of r_g/l_c become smaller. Soon we will be submitting at least 2 papers that examine exactly these effects.

In our opinion interpolation is not the biggest limiting factor to get lower ratios of r_c/l_c, but the lack of resonant interaction possibilities in accordance with the gyroresonance criteria. @adundovi: Do you have another impression? 

The whole topic is very complicated due to the many dependencies and correlations... so it is always good to cross validate as much as possible :)

**Comment by adundovi** [comment]
@reichherzerp I'm looking forward seeing on-the-fly method in CRPropa.

I can confirm the findings you mentioned: with the grid method one cannot go easily beyond the 2048^3 grid size, maybe 4k with 1.5TB RAM machines is still possible (on the AWS or similar), but that is still just three scales in k. Since the correlation length (l_c) for the currently implemented model of turbulence is maximally 1/5*L_box, roughly only two scales in power are left below l_c, i.e., 10^(-2)*r_g/l_c is the lowest ratio one can effectively push without missing the power. Here is a simple prototype plot made with CRPropa, which shows the saturation for low r_g/l_c ratios:
![Diffusion_coeff_vs_gyroradius_over_Lc_naivemodelB_1024_Lmax=8fold_Lbox](https://user-images.githubusercontent.com/8830248/60590970-9f53b400-9d9d-11e9-8aec-638c921183d0.png)
We know from theoretical arguments that the R^(1/3) dependence should be satisfied for turbulence with the zero mean-field further than r_g/l_c < 0.01, thus the saturation is a numerical artifact of the grid resolution. My impression is that changing the interpolation method cannot fix this result much because the interpolation itself cannot introduce more power below grid scales.

The (b/B) case is of course the more interesting one, and harder to numerically model.

**Comment by reichherzerp** [comment]
@adundovi Thanks for sharng this plot! This looks really good. I have recently created a similair plot that also shows this saturation. I have concluded that FLRW is the reason for this energy independece of the diffusion coefficient, even thought [Subedi 2017](https://iopscience.iop.org/article/10.3847/1538-4357/aa603a) has written that they don't observe this behaviour, right?

For my master's thesis I have compared simulations with CRPropa and all other papers that I have found at that time (without looking at the low ratios of r_g/l_c that are more difficult to simulate)...

![kappa_turbulence](https://user-images.githubusercontent.com/31761331/60605200-5c073e80-9db9-11e9-8482-8ce013832678.png)

> We know from theoretical arguments that the R^(1/3) dependence should be satisfied for turbulence with the zero mean-field further than r_g/l_c <  0.01, 

> 
I have also read this in [Subedi 2017](https://iopscience.iop.org/article/10.3847/1538-4357/aa603a), but in [Snodin (2016)](https://arxiv.org/pdf/1509.03766.pdf) for example it is argued, that the dependency should be rather \kappa \propto r_g/l_c for the case of a zero mean-field (Figure 2 and 3 and Equation (20)). 
[Srinivasan (2014)](http://adsabs.harvard.edu/abs/2014Ap%26SS.350..197S) derive this relation from theoretical arguments and they call it the modifyed Bohm diffusion. I would be very happy to read about these theoretical arguments you mention.

But isn't the R^(1/3) dependency actually only valid in the quasilinear limit: b/B << 1 (b amplitude of turbulence and B amplitude of background field)?

**Comment by adundovi** [comment]
@reichherzerp In Subedi 2017, the authors commented on page 7 that for small Larmor radius compared to L_c the simulation does not numerically resolve the resonant scales, what can especially be seen for the 512^3 grid. Thus, they observe the behaviour, but declare it as being non-physical.

Your plot is particularly useful for comparing different plots (though, you have to capture all those points from their plots!), and now I find it surprising how Harari et. al. 2014 managed to go to such low ratios! Now I'm even more interested in the wave-method for the construction of a turbulent field.

About the explanation of R^(1/3). The idea behind the Subedi 2017 derivation is that below the l_c scale there is a local mean field on scale of l_c (B), while smaller mods act as the perturbation (b), thus you can apply the quasilinear approach.

**Comment by adundovi** [comment]
@reichherzerp BTW, in your plot, which points from the Subedi 2017 plot did you take?

**Comment by adundovi** [comment]
I'm quite convinced from my investigation that there shouldn't be new physical features, and slope changes for << r_g/l_c in a fully isotropic (synthetic) turbulent field. All that is observed in simulations are numerical artefacts. The field itself by construction is self-similar (a power low), thus, there is no reason that something would magically appear at small scales well below l_c.

Although it is not a quantitative method, I still find convincing to plot trajectories, at least to double-check what is going on.

In CRPropa you can easily "collect" a trajectory of a particle. Here is a simple example:
```python
    sim = ModuleList()
    prop = PropagationCK(Bfield, 1e-4, 1e-2*r_g, r_g)
    sim.add(prop);
    sim.add(MaximumTrajectoryLength(100*r_g));
    collector = ParticleCollector()
    collector.setClone(True)
    sim.add(collector);
    
    p = ParticleState()
    p.setId(nucleusId(1, 1))
    p.setEnergy(E)
    p.setPosition(Vector3d(0, 0, 0))
    p.setDirection(Vector3d(1, 0, 0.2))
    
    c = Candidate(p)
    sim.setShowProgress()
    sim.run(c)
```

And one can use vispy to (pip install vispy) plot millions of points instantly using GPU:
```
import sys
import numpy as np
import vispy.scene
from vispy.scene import visuals

def show_points(view, points, size=5, face_color=(1,1,1,.5)):
    """ Scatter data given by the list of (x,y,z) coodinates
    """
    scatter = visuals.Markers()
    scatter.set_data(points, edge_color='white', face_color=face_color, size=size)
    view.add(scatter)
    return scatter

def load_trajectory(filename):
    raw_data = np.genfromtxt(filename, names=True)
    return raw_data[["X","Y","Z"]], raw_data[["E"]]

def main():
    canvas = vispy.scene.SceneCanvas(keys='interactive', show=True)
    view = canvas.central_widget.add_view()

    filename = sys.argv[1]
    points, energies = load_trajectory(filename)
    points_transformed = np.array([np.array([X,Y,Z]) for X,Y,Z in points])
    show_points(view, points_transformed)
    view.camera = 'turntable'

if __name__ == '__main__':
    main()
    if sys.flags.interactive != 1:
        vispy.app.run()
```
One can observe when r_g is close to the grid resolution particles start spiraling around interpolated field lines which are, of course, smooth.

This is still physical r_g/l_c ~ 0.1:
![trajectory-ratio-0 1-naiveB](https://user-images.githubusercontent.com/8830248/60655538-34ae8100-9e4e-11e9-9627-ed7a7940072c.png)

While this is not (0.01):
![trajectory-ratio-0 01-naiveB](https://user-images.githubusercontent.com/8830248/60655845-bd2d2180-9e4e-11e9-9aca-f09a845ad6da.png)

**Comment by adundovi** [comment]
The discussion is now continued in PR #287. Closing this one.
