### ISSUE TITLE
Problem in installing in Mac

### ISSUE THREAD

**Issue by Adiolph** [CRPropa/CRPropa3#235]
I get some problem when installing CRPropa3 in Mac OS 10.14.5.
After `make` the file, I run `make test` and it turns out `11 tests failed out of 19`.
I don't kown why it faild.
[CMakeCache.txt](https://github.com/CRPropa/CRPropa3/files/3365567/CMakeCache.txt)

**Comment by adundovi** [comment]
Hi @Adiolph, can you run the individual tests that failed in your case and c/p the output?

**Comment by Adiolph** [comment]
Here is the running result of testCore:
`Last login: Sun Jul  7 20:21:03 on ttys000
/Users/hu_fan/CRPropa3/build/testCore ; exit;
(base) Hu-FandeMacBook-Pro:~ hu_fan$ /Users/hu_fan/CRPropa3/build/testCore ; exit;
Running main() from /Users/hu_fan/CRPropa3/libs/gtest/src/gtest_main.cc
[==========] Running 49 tests from 15 test cases.
[----------] Global test environment set-up.
[----------] 11 tests from ParticleState
[ RUN      ] ParticleState.position
[       OK ] ParticleState.position (0 ms)
[ RUN      ] ParticleState.energy
[       OK ] ParticleState.energy (0 ms)
[ RUN      ] ParticleState.direction
[       OK ] ParticleState.direction (0 ms)
[ RUN      ] ParticleState.velocity
[       OK ] ParticleState.velocity (0 ms)
[ RUN      ] ParticleState.momentum
[       OK ] ParticleState.momentum (0 ms)
[ RUN      ] ParticleState.id
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] ParticleState.id (0 ms)
[ RUN      ] ParticleState.idException
[       OK ] ParticleState.idException (0 ms)
[ RUN      ] ParticleState.Charge
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] ParticleState.Charge (0 ms)
[ RUN      ] ParticleState.Rigidity
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] ParticleState.Rigidity (0 ms)
[ RUN      ] ParticleState.Mass
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] ParticleState.Mass (1 ms)
[ RUN      ] ParticleState.lorentzFactor
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] ParticleState.lorentzFactor (0 ms)
[----------] 11 tests from ParticleState (1 ms total)

[----------] 4 tests from ParticleID
[ RUN      ] ParticleID.nucleusId
[       OK ] ParticleID.nucleusId (0 ms)
[ RUN      ] ParticleID.chargeNumber
[       OK ] ParticleID.chargeNumber (0 ms)
[ RUN      ] ParticleID.massNumber
[       OK ] ParticleID.massNumber (0 ms)
[ RUN      ] ParticleID.isNucleus
[       OK ] ParticleID.isNucleus (0 ms)
[----------] 4 tests from ParticleID (0 ms total)

[----------] 2 tests from HepPID
[ RUN      ] HepPID.consistencyWithReferenceImplementation
[       OK ] HepPID.consistencyWithReferenceImplementation (0 ms)
[ RUN      ] HepPID.charge
[       OK ] HepPID.charge (0 ms)
[----------] 2 tests from HepPID (0 ms total)

[----------] 6 tests from Candidate
[ RUN      ] Candidate.currentStep
[       OK ] Candidate.currentStep (0 ms)
[ RUN      ] Candidate.limitNextStep
[       OK ] Candidate.limitNextStep (0 ms)
[ RUN      ] Candidate.isActive
[       OK ] Candidate.isActive (0 ms)
[ RUN      ] Candidate.property
[       OK ] Candidate.property (0 ms)
[ RUN      ] Candidate.addSecondary
testCore(4622,0x10fd445c0) malloc: can't allocate region
*** mach_vm_map(size=18446744073709518848) failed (error code=3)
testCore(4622,0x10fd445c0) malloc: *** set a breakpoint in malloc_error_break to debug
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] Candidate.addSecondary (0 ms)
[ RUN      ] Candidate.serialNumber
[       OK ] Candidate.serialNumber (0 ms)
[----------] 6 tests from Candidate (0 ms total)

[----------] 4 tests from common
[ RUN      ] common.digit
[       OK ] common.digit (0 ms)
[ RUN      ] common.interpolate
[       OK ] common.interpolate (0 ms)
[ RUN      ] common.interpolateEquidistant
[       OK ] common.interpolateEquidistant (0 ms)
[ RUN      ] common.pow_integer
[       OK ] common.pow_integer (0 ms)
[----------] 4 tests from common (0 ms total)

[----------] 3 tests from Random
[ RUN      ] Random.seed
[       OK ] Random.seed (0 ms)
[ RUN      ] Random.bigSeedStorage
[       OK ] Random.bigSeedStorage (4 ms)
[ RUN      ] Random.base64Seed
[       OK ] Random.base64Seed (3 ms)
[----------] 3 tests from Random (7 ms total)

[----------] 1 test from base64
[ RUN      ] base64.de_en_coding
[       OK ] base64.de_en_coding (2 ms)
[----------] 1 test from base64 (2 ms total)

[----------] 1 test from Grid
[ RUN      ] Grid.PeriodicClamp
[       OK ] Grid.PeriodicClamp (0 ms)
[----------] 1 test from Grid (0 ms total)

[----------] 3 tests from ScalarGrid
[ RUN      ] ScalarGrid.SimpleTest
[       OK ] ScalarGrid.SimpleTest (0 ms)
[ RUN      ] ScalarGrid.TestVectorSpacing
[       OK ] ScalarGrid.TestVectorSpacing (0 ms)
[ RUN      ] ScalarGrid.ClosestValue
[       OK ] ScalarGrid.ClosestValue (0 ms)
[----------] 3 tests from ScalarGrid (0 ms total)

[----------] 5 tests from VectorGrid
[ RUN      ] VectorGrid.Interpolation
[       OK ] VectorGrid.Interpolation (0 ms)
[ RUN      ] VectorGrid.Periodicity
[       OK ] VectorGrid.Periodicity (0 ms)
[ RUN      ] VectorGrid.DumpLoad
[       OK ] VectorGrid.DumpLoad (0 ms)
[ RUN      ] VectorGrid.DumpLoadTxt
[       OK ] VectorGrid.DumpLoadTxt (0 ms)
[ RUN      ] VectorGrid.Speed
[       OK ] VectorGrid.Speed (6 ms)
[----------] 5 tests from VectorGrid (6 ms total)

[----------] 1 test from VectordGrid
[ RUN      ] VectordGrid.Scale
[       OK ] VectordGrid.Scale (0 ms)
[----------] 1 test from VectordGrid (0 ms total)

[----------] 1 test from CylindricalProjectionMap
[ RUN      ] CylindricalProjectionMap.functions
[       OK ] CylindricalProjectionMap.functions (0 ms)
[----------] 1 test from CylindricalProjectionMap (0 ms total)

[----------] 2 tests from EmissionMap
[ RUN      ] EmissionMap.functions
[       OK ] EmissionMap.functions (0 ms)
[ RUN      ] EmissionMap.merge
[       OK ] EmissionMap.merge (2 ms)
[----------] 2 tests from EmissionMap (2 ms total)

[----------] 2 tests from Variant
[ RUN      ] Variant.copyToBuffer
[       OK ] Variant.copyToBuffer (0 ms)
[ RUN      ] Variant.stringConversion
[       OK ] Variant.stringConversion (0 ms)
[----------] 2 tests from Variant (0 ms total)

[----------] 3 tests from Geometry
[ RUN      ] Geometry.Plane
[       OK ] Geometry.Plane (0 ms)
[ RUN      ] Geometry.Sphere
[       OK ] Geometry.Sphere (0 ms)
[ RUN      ] Geometry.ParaxialBox
[       OK ] Geometry.ParaxialBox (0 ms)
[----------] 3 tests from Geometry (0 ms total)

[----------] Global test environment tear-down
[==========] 49 tests from 15 test cases ran. (18 ms total)
[  PASSED  ] 43 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] ParticleState.id
[  FAILED  ] ParticleState.Charge
[  FAILED  ] ParticleState.Rigidity
[  FAILED  ] ParticleState.Mass
[  FAILED  ] ParticleState.lorentzFactor
[  FAILED  ] Candidate.addSecondary

 6 FAILED TESTS
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Complete]

`

**Comment by adundovi** [comment]
Seems like an unhandled case of the data file reading. The data files could be either missing or are placed in an unknown location. Can you try `make install` and run the tests again?

**Comment by Adiolph** [comment]
Wow, after `make install`, `testCore` succeed.
But when runing `make test`, there are still 4 tests failed: 

> 	 16 - testMagneticLensPythonInterface (SEGFAULT)
	 17 - testSimulationExecution (SEGFAULT)
	 18 - testDiffusionSDE (SEGFAULT)
	 19 - testPythonExtension (SEGFAULT)
I guess I have missed some dependent packages.

**Comment by adundovi** [comment]
OK. This is still a bug (not recognising data files when in the build directories), however, those other tests that failed are of a different origin, can you c/p the individual output of them, too?

**Comment by Adiolph** [comment]
Sorry, but I don't know how to run thoes last 4 tests.
Is that run the python file?

**Comment by adundovi** [comment]
```bash
python testSimulationExecution.py
```

**Comment by Adiolph** [comment]
It just return: 
`Segmentation fault: 11`

**Comment by adundovi** [comment]
Sounds like a python version mismatch. Which Python version do you use?

**Comment by Adiolph** [comment]
I have Python 3.7.3 and Python 2.7 in my computer.
This time, I run `python2.7 testPythonExtension.py`, and it returns:

> *** CRPropa import failed
(<type 'exceptions.ImportError'>, 'dynamic module does not define init function (init_crpropa)')
>

**Comment by adundovi** [comment]
You should check which python `cmake` found during the ``cmake ..`` phase, and run python scripts with the same one.

**Comment by Adiolph** [comment]
In the CMakeCache.txt, I find some words:

> //Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/Users/hu_fan/anaconda3/bin/python

>//Path to a file.
PYTHON_H_FOUND:FILEPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Python.framework/Headers/Python.h

Does it mean it use Python 3.7?

**Comment by adundovi** [comment]
Not sure. I would say that the version of executable (from anaconda3) is not matching the version of python header files (from OS X SDK), and that could be the source of SEGFAULTs. You should force cmake to find exactly the python paths which you want to use. See my comment [here](https://github.com/CRPropa/CRPropa3/issues/229#issuecomment-482589451).

**Comment by Adiolph** [comment]
I run `ccmake ..` again and set following paramaters when ccmake:
`PYTHON_EXECUTABLE                /Users/hu_fan/anaconda3/bin/python`
`PYTHON_H_FOUND                   /Users/hu_fan/anaconda3/include/python3.7m/pytime.h`
`PYTHON_INCLUDE_DIR               /Users/hu_fan/anaconda3/include/python3.7m`
`PYTHON_LIBRARY                   /Users/hu_fan/anaconda3/lib/libpython3.7m.dylib`
But the results are the same: 4 SEGFAULTs

**Comment by adundovi** [comment]
I don't have OS X available at the moment to test it myself. However, [here](https://travis-ci.org/CRPropa/CRPropa3/jobs/549014843) we have a continuous integration test for OS X, and it works with the current master. Notice that it uses python2 so try maybe you should try python2 first.

**Comment by Adiolph** [comment]
Thanks for your help, I will continue to try it tomorrow.

**Comment by Adiolph** [comment]
I changed a command in the CMakeLists.txt file:

delete two lines:
`find_package(PythonInterp)`
`find_package(PythonLibs)`

add one line:
`find_package (Python3 COMPONENTS Interpreter Development)`

Then all tests pass.
But I can not import crpropa in python: `No module named 'crpropa'`.

BTW, I use Install from source method (though I am not a experienced users orz

**Comment by TobiasWinchen** [comment]
> In the CMakeCache.txt, I find some words:
>
>   //Path to a program.
>    PYTHON_EXECUTABLE:FILEPATH=/Users/hu_fan/anaconda3/bin/python
>
>    //Path to a file.
>    PYTHON_H_FOUND:FILEPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Python.framework/Headers/Python.h

I am not a mac expert, but this looks to me as if you are using two different python installs for CRPropa. You should probably not modify the CMakeLists,txt but fix the variables to use the anaconda python version.

**Comment by Adiolph** [comment]
I am a layman in programing, how can a fix the variables to use the anaconda python version?

**Comment by TobiasWinchen** [comment]
> OK. This is still a bug (not recognising data files when in the build directories), however, those other tests that failed presumably failed due to a different origin, can you c/p the individual output of them, too?

I would not consider this a bug as we should not load data from too many locations. The default order is 
1. Environment variable CRPROPA_DATA_PATH
2. Install directory
3. ../data refering to the executeable
4. data refering to the CWD

we should stick with this, but improve documentation.

**Comment by TobiasWinchen** [comment]
> I am a layman in programing, how can a fix the variables to use the anaconda python version?

Use ccmake .. to get a TUI for the options and point the  variables as e.g. PYTHON_H_FOUND:FILEPATH to the path within the anaconda installation. 

Please note that I have no direct experience with anaconda and just guessing here.

**Comment by Adiolph** [comment]
Now I am trying "Install from source in python virtualenv"

In the forth step "Compile and install CRPropa", should I use `ccmake ..` instead?

**Comment by adundovi** [comment]
> I would not consider this a bug as we should not load data from too many locations. The default order is
>     1. Environment variable CRPROPA_DATA_PATH 
>     2. Install directory
>     3. ../data refering to the executeable
>     4. data refering to the CWD
> 

I agree, but in this case, something is not working as expected as the test executeables should find the data files according to the 3rd and 4th option, and they don't. We almost never encounter this issue by running `make test` as we have the data files in the install directory from previous installations. I encountered this problem once before, when installing CRPropa on a computer for the first time. However, then I didn't have time to debug. I'll look into this again.

**Comment by adundovi** [comment]
> In the forth step "Compile and install CRPropa", should I use `ccmake ..` instead?

Yes, use:
```
CMAKE_PREFIX_PATH=$CRPROPA_DIR ccmake -DCMAKE_INSTALL_PREFIX=$CRPROPA_DIR ..
```

**Comment by Adiolph** [comment]
When I run `make`, it returns errors:
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`
`make[2]: *** [_crpropa.so] Error 1`
`make[1]: *** [CMakeFiles/crpropa-swig.dir/all] Error 2`
`make: *** [all] Error 2`

The full output is copied in the txt file.


[make_error.txt](https://github.com/CRPropa/CRPropa3/files/3367308/make_error.txt)

**Comment by Adiolph** [comment]
At last, I succeed to install it in conda environment, and can run the example file.

**Comment by adundovi** [comment]
@Adiolph can you please write which library/python paths did you use in the end?

**Comment by Adiolph** [comment]
I ues `conda creat --name crpropa3 python=2.7` to creat a python 2.7 environment.
Then activate it by `conda activate crpropa3`.
I set the path: `export CRPROPA_DIR=$HOME"anaconda3/envs/crpropa3"`

And Compile and install CRpropa as usual:
`git clone https://github.com/CRPropa/CRPropa3.git`
`cd CRPropa3`
`mkdir build`
`cd build`
`CMAKE_PREFIX_PATH=$CRPROPA_DIR cmake -DCMAKE_INSTALL_PREFIX=$CRPROPA_DIR ..`
`make`
`make install`
`make test`

When running `cmake`, I find:
`-- Python: Found!`
`--   Version:     2.7/27`
`--   Executeable: /Users/hu_fan/anaconda3/envs/crpropa3/bin/python`
`--   Include:     /Users/hu_fan/anaconda3/envs/crpropa3/include/python2.7`
`--   Library:     /Users/hu_fan/anaconda3/envs/crpropa3/lib/libpython2.7.dylib`
`--   Site-package directory: /Users/hu_fananaconda3/envs/crpropa3/lib/python2.7/site-packages`

So I suppose I ues the new created conda python2 environment.

BTW, when I repeat above process with conda python3 environment, the last 4 tests gets SEGFAULT. I don't know why that happen.

**Comment by adundovi** [comment]
This could be a solution for the python 3 issue on Mac OS X:
https://github.com/CRPropa/CRPropa3/wiki/Installation#mac-os-x-specifics
