### ISSUE TITLE
Conda and CRPROPA environment conflicts

### ISSUE THREAD

**Issue by jleagle94** [CRPropa/CRPropa3#238]
Hello,

I would like to use CRPropa in helping me simulate CR diffusion with a particular SNR. I have it downloaded and without any other environments activated except for my CRPROPA (sourcing /Users/myname/CRPROPA_DIR/bin/activate), I can access crpropa package fine within python but not numpy. If I use jupyter notebook (through anaconda2 environment) then I can access numpy fine but then crpropa is blocked. I'm sure it has to do with the having an environment within an environment (big no no, I know) but I'm not sure how to circumvent this. Any help/suggestions? Thanks!

**Comment by adundovi** [comment]
You have two options: either to install required packages into the crpropa virtualenv via pip, or install crpropa in the anaconda2 path. In the first case, after activating the crpropa environment, you just hit: pip install jupyter numpy matplotlib scipy ... and all packages should be importable from the python where crpropa is present. For the second case you have to find the library path of anaconda2 (where are its libs and include directories, and use these for paths for cmake).

**Comment by jleagle94** [comment]
Ah I see. I don't know why I didn't think to do that to begin with! Thank you!
