### ISSUE TITLE
Introducing kill conditions in simulations 

### ISSUE THREAD

**Issue by wilson-2015** [CRPropa/CRPropa3#241]
Hi,
I have created the Probability Distribution Function and indent to simulate cosmic ray particles leaving the source (Cen A Core) within this source direction: theta(2.1750 - 2.3104) rad and phi(1.8810 - 1.9660) rad. I am still new with python programming can anyone help on how to write a code to loop within this angle range. A sample script that I indent to insert this code is in the link below.
[extragalactic_field_wilson.txt](https://github.com/CRPropa/CRPropa3/files/3579713/extragalactic_field_wilson.txt)

**Comment by lukasmerten** [comment]
Hi, 
you may have a look at this [SourceEmissionCone](https://github.com/CRPropa/CRPropa3/blob/master/src/Source.cpp) (l. 774-790) feature. This allows to inject particles within a user specified cone. So maybe you do not even have to write new code. Anyway, looping in python to inject the particles into the simulation is probably not a very efficient way.
Best, 
Lukas

**Comment by wilson-2015** [comment]
Thanks Lukas for a prompt response and sorry for my late comments. I had trouble on how to get the openning angle of the cone from theta and phi. So, I resorted to an alternative method that worked although still interested on how this method works too! 
Thank you,
Wilson

**Comment by TobiasWinchen** [comment]
I assume that this issue is closed now - please reopen if I am mistaken.
