### ISSUE TITLE
Emission Map

### ISSUE THREAD

**Issue by cainaoliveira** [CRPropa/CRPropa3#242]
How can I create and use a Emission Map to optimize a 3D simulation from a point source?

**Comment by rafaelab** [comment]
Hi!
Could you provide more information?
What do you want to do? Is it a simulation of 3D point source?

**Comment by cainaoliveira** [comment]
Yes. I want propagate particles of a source to the earth in a magnetic field. I read in an article that is possible create a Emission Map to deactivate candidates that will not arrive to the observer, but I don't find any python notebook that can help with this.

**Comment by rafaelab** [comment]
I'm not sure what  you read, but I don't think this feature exists. 
In general, if the particles don't reach the observer, there is no way of knowing whether they will arrive or not. Therefore, such a feature would not be possible, in principle.
EmissionMap does something else.

Essentially, the observer collects the particles that reach it. 
If you want to stop tracking some particles, you can add breaking conditions like MinimumEnergy or MaximumTrajectoryLength. There are a few examples like this in the wiki.
But there is presently no way of optimising the simulation like you are saying, if I understand you correctly.

**Comment by cainaoliveira** [comment]
Ok. Thank you so much!
