### ISSUE TITLE
Propagate particles from a txt file

### ISSUE THREAD

**Issue by cainaoliveira** [CRPropa/CRPropa3#243]
Hi,
I have created a .txt file with photons and electrons/positrons generated by propagation of nuclei. I want know if is possible propagate the photons and electrons/positrons of this file using CRPropa modules keeping in the output file the information about the primary particle (the nuclei in case).

**Comment by adundovi** [comment]
Hi @cainaoliveira ,
if I understood your intention correctly, you can use [`ParticleCollector`](https://github.com/CRPropa/CRPropa3/blob/ab11dbb0de1f663ab128d247c6fec912e5761912/include/crpropa/module/ParticleCollector.h) for this purpose. It is an Output module with which you can dump/save particles to a file and then load them again and propagate further. Before saving or after loading, you can select only portions of particles with desired properties.

An (pseudo)example (which I didn't test):
```python
c = Candidate() # a candidate with some properties
output = ParticleCollector()
output.process(c) # the candidate is saved in-memory,
# but in principle, you would like to save it when certain conditions are met (see .onAccept(), .onReject() and similar methods in `BreakCondition.h`) ...
# ...and in that case you add the collector module to the simulation with sim.add(output)
output.dump("particles.txt.gz")
```
A new simulation would look like
```python
input = ParticleCollector()
input.load("particles.txt.gz")
for c in input: # to continue propagating partiles
   sim.run(c) # one more detail: one should re-activate a particle state if it was deactivated when detected / met a break condition, otherwise the ModuleList will not propagate it
```

**Comment by cainaoliveira** [comment]
Thank you so much @adundovi. I modified this to my simulation. Just one question more, is possible use the ParticleCollector() as an output method to an observer?

**Comment by adundovi** [comment]
Yes, it is. Personally, I use it as the default storage when I run simulations within Jupyter notebooks.
```python
sim = ModuleList()
...
obs = Observer()
...
output = ParticleCollector()
obs.onDetection(output)
sim.add(obs)
...
```

**Comment by cainaoliveira** [comment]
I tried this

#Neutrino Observer
obs = Observer()
obs.add( ObserverDetectAll() )
obs.add( ObserverNucleusVeto() )
obs.add( ObserverPhotonVeto() )
obs.add( ObserverElectronVeto() )
output = ParticleCollector()
obs.onDetection( output )
output.dump("particles.txt.gz")
sim.add( obs )

but the generated file is empty.

**Comment by adundovi** [comment]
If it works with `TextOutput`, it should work with `ParticleCollector`, too. Please, check those imposed conditions.

BTW You could immediately see if the collector is empty by printing its size from Python: `print(len(output))`.

**Comment by cainaoliveira** [comment]
Thank you @adundovi. I put the output.dump("particles.txt.gz") after run simulation and it works!
