### ISSUE TITLE
Keyword arguments are not always recognized

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#244]
Reported by Jörg Rachen, CRPropa meeting October 2019. We should derive an example case when this happen and develop checks that all kwargs are passed correctly.

**Comment by TobiasWinchen** [comment]
This is clearly a bug:
```
p = crpropa.PhotoDisintegration(havePhotons=True)

In [7]: p.getDescription()
Out[7]: 'PhotoDisintegration: CMB'

In [8]: p = crpropa.PhotoDisintegration(havePhotons=True, photonField=crpropa.IRB_Dominguez11)

In [9]: p.getDescription()
Out[9]: 'PhotoDisintegration: CMB'

In [10]: p = crpropa.PhotoDisintegration(photonField=crpropa.IRB_Dominguez11)

In [11]: p.getDescription()
Out[11]: 'PhotoDisintegration: CMB'

```

**Comment by TobiasWinchen** [comment]
Apparently, swig cannot handle keyword arguments for overloaded functions. So they cannot be used here. However, sadly no error is created, even on
```
p = crp.PhotoDisintegration(nonExistingKeywordArguemntShouldRaiseException=True)
```

This needs to be fixed ASAP as this is highly dangerous.

**Comment by TobiasWinchen** [comment]
I created a pull request #250 to disable swig -builtin option as a default. Without -builtin the code works as expected. As we already have a test, we can close this feature for now. The main issue will be that pure python extensions will be somewhat slower due to the additional proxy layer.

**Comment by adundovi** [comment]
OK. However, as soon as the issue is solved in the upstream we should switch back to builtin.
