### ISSUE TITLE
Frequent confusion about the "discovery" of virtual dipoles

### ISSUE THREAD

**Issue by MRCWirtz** [CRPropa/CRPropa3#246]
As a lot of people are anyways thinking about CRPropa right now at the workshop, I have here some issue:

In recent times there was a lot of confusion in the community about the formation of anisotropies after forward tracking a seemingly isotropic distribution from outside the Galaxy to the observer (I know, for most of you this means more annoying discussions about Liouville's theorem ;-) ) in CRPropa3. The mistake was probably (at least in one case I know it) the following setup of the source:

```
source = crp.Source()
source.add(crp.SourceUniformShell(crp.Vector3d(0, 0, 0) * crp.kpc, 20 * crp.kpc))
source.add(crp.SourceIsotropicEmission())
```

The user assumed in this context that the "SourceIsotropicEmission()" set directions in a way as they would arrive (on the surface of the 20kpc Galactic sphere) after isotropic propagation in the Extragalactic space. Please note, that this is not the case as the arrival directions on each surface element of the Galactic sphere should be Lamberts distributed (https://en.wikipedia.org/wiki/Lambert%27s_cosine_law)... you know, flat angles have lower "hit probabilities". 

As a lot of research time was already dedicated to this issue, I was wondering if we should implement a new source model with an intuitive name like "SourceGalacticSphere" or "SourceGalacticArrival", which set up positions and directions as expected from isotropic extragalactic propagation. If there is already something like this implemented please let me know, otherwise I will work on that soon.

If you want to discover your own virtual dipole you can execute the following script:

```
import numpy as np
import matplotlib.pyplot as plt
import crpropa as crp

n = 100000000

output = crp.ParticleCollector()

# Simulation setup
sim = crp.ModuleList()
sim.add(crp.SimplePropagation())

# collect cosmic rays at Earth
obs = crp.Observer()
pos_earth = crp.Vector3d(-15, 0, 0) * crp.kpc
obs.add(crp.ObserverSurface(crp.Sphere(pos_earth, 0.1 * crp.kpc)))
obs.onDetection(output)
sim.add(obs)

# collect outwards going cosmic rays
obs_trash = crp.Observer()
obs_trash.add(crp.ObserverSurface(crp.Sphere(crp.Vector3d(0), 21 * crp.kpc)))
sim.add(obs_trash)

# source setup
source = crp.Source()
source.add(crp.SourceUniformShell(crp.Vector3d(0, 0, 0) * crp.kpc, 20 * crp.kpc))
source.add(crp.SourceIsotropicEmission())
source.add(crp.SourceParticleType(-crp.nucleusId(1, 1)))
source.add(crp.SourceEnergy(100 * crp.EeV))

sim.run(source, n)

print("Number of hits: %i" % len(output))
lons = []
for c in output:
    v = c.current.getDirection()
    lons.append(v.getPhi())

plt.hist(np.array(lons), bins=30, color='k', histtype='step')
plt.xlabel('lon', fontsize=20)
plt.ylabel('counts', fontsize=20)
plt.savefig('lon_distribution.png', bbox_inches='tight')

```

**Comment by adundovi** [comment]
Hi Marcus! A nice and practical addition to the code. And the confusion is well known to me :-)

Although, I would generally argue that motivation in introducing new modules/features like this shouldn't be led by the idea to stop/discourage people of doing conceptual mistakes in their simulation scenarios. That would lead to an endless list of very specific features which would be hard to maintain and track. Or to be more concrete, if you find that this feature has a wide practical usage for galactic scenarios I'm totally for it; however, if you just want to stop people of finding a virtual dipole due to misunderstanding the concept of isotropic arrival directions, well, better to write one line more in documentation about this concern than introducing a new feature...

**Comment by MRCWirtz** [comment]
Hi Andrej. 

I agree that adding documentation about this issue is the most crucial point and should be done anyways; in this sense everybody is better advised to perform backtracking for Galactic propagation! Forwardtracking just slows everything down and is getting more inaccurate due to the finite observer issue. 

Nevertheless, people that are starting typically want to do the direct crosscheck that it yields the same results, and for this stage I think that there is a practical usage.

**Comment by adundovi** [comment]
OK. Fine with me. :-) I'm closing now this issue.

**Comment by MRCWirtz** [comment]
@adundovi Do you actually know why the notebooks view of the examples are just randomly working?

**Comment by adundovi** [comment]
I don't know... probably because of [this](https://nbviewer.jupyter.org/github/crpropa/crpropa3-notebooks/tree/master/):
```
503 : Service Unavailable
GitHub API rate limit exceeded. Try again soon.
```

Maybe we should generate static HTML files and upload them next to the ipython files.

**Comment by adundovi** [comment]
See the following GitHub [note](https://help.github.com/en/articles/working-with-jupyter-notebook-files-on-github).
