### ISSUE TITLE
Extragalactic Deflection

### ISSUE THREAD

**Issue by Laruku25** [CRPropa/CRPropa3#251]
I'm trying to calculate extragalactic deflections with CRPROPA using magnetic field models given in the download section: "Dolag" "Miniati" etc.

The problem is that the deflections are too high and the particle seems to be moving all over the place instead of being almost rectiliniar. According to Dolag it should be at most 5-7 degrees...at these high energies but I'm not getting nothing near that.

Am I missing something? Do I have to modify the grid files? I'm kind of newb with physics simulations so I apologize if it's a simple issue...maybe the wrong file...who knows.

Here's one example:

```
from crpropa import *
import math
import numpy as np
import matplotlib.pyplot as plt
from pylab import *
from mpl_toolkits.mplot3d import axes3d




position=Vector3d(-1,0,0)*Mpc
lat = 0.96
lon = 1.95
direction = Vector3d()
direction.setRThetaPhi(1, lat, lon)
particle=-nucleusId(1,1)
energy=50*EeV
p=ParticleState(particle,energy,position,direction)


file="Dolag.raw"
gridOrigin=Vector3d(0,0,0)
gridSize=440
size=186*Mpc
b_factor=1.
spacing=size/(gridSize)
vgrid=VectorGrid(gridOrigin,gridSize,spacing)
loadGrid(vgrid,file,b_factor)
EGMF=MagneticFieldGrid(vgrid)

sim=ModuleList()
sim.add(PropagationCK(EGMF,1e-2,10*kpc,.1*Mpc))
obs=Observer()
obs.add(ObserverLargeSphere(Vector3d(0),10*Mpc))
sim.add(obs)
output = TextOutput('shizzle.txt', Output.Trajectory3D)
sim.add(output)
c=Candidate(p)
sim.run(c)

output.close()
data = np.genfromtxt('shizzle.txt', names=True)
x, y, z = data['X'], data['Y'], data['Z']
fig = plt.figure(figsize=(12, 5))
ax = fig.gca(projection='3d')
ax.scatter(x,y,z, 'o')
ax.set_xlabel('x / Mpc', fontsize=18)
ax.set_ylabel('y / Mpc', fontsize=18)
ax.set_zlabel('z / Mpc', fontsize=18)
ax.set_xlim((-10, 10))
ax.set_ylim((-10, 10))
ax.set_zlim((-5, 5))
ax.xaxis.set_ticks((0, 5, 10, 15))
ax.yaxis.set_ticks((0, 5, 10, 15))
ax.zaxis.set_ticks((0, 5, 10, 15))

show()

```

Here's the graph 

![Figure_4](https://user-images.githubusercontent.com/56370773/66598574-ebfe1680-eb66-11e9-831b-47aa136e48c2.png)

**Comment by avvliet** [comment]
The problem is probably the 'b_factor' that you are using. This should be 'gauss' instead of '1.' as this is the unit of the Dolag magnetic field values.

**Comment by Laruku25** [comment]
Thanks that's what I thought the lower the value the more rectilinear the path. By Gauss u mean 1e-4? There's almost zero deviation with that value.

.05 seems to give reasonable results but i'm just throwing that out randomly....

**Comment by adundovi** [comment]
Hi @Laruku25, try to calculate the Brms value of the field file you have (check `meanFieldStrength(grid)` in CRPropa), and compare it with an original reference of the field you use. That is the safest method to get the field normalization right. And as @avvliet wrote, this should be the place where the issue is. All propagation aspects of CRPropa in this context are so many times tests by now that there is hardly a chance that there is a bug in propagation code that deflects particles way too much :-)
