### ISSUE TITLE
Enormous amount of secondary neutrinos from UHECR

### ISSUE THREAD

**Issue by mnogoslov** [CRPropa/CRPropa3#253]
Hi! 
I'm analyzing UHE photon predictions from GZK process, i.e. simulating primary nuclei from a 3-d source distribution and looking at the secondary particles at the observer. We expect to observe about the same order amount of photons and neutrinos, yet the simulation results in nearly 1000 time more neutrinos than photons. 
I'm attaching the working code of the simulation. Several simulation modules are plugged in, UniformBox is used as a source of protons with power law spectrum, x=0 plane is an observer. Small magnetic field perpendicular to the CR is plugged in as well. 
I'm not sure whether this strange result is my mistake or propagation bug, could you please look at it and say if you see any explanation?

**Comment by mnogoslov** [comment]
Sorry, failed with attaching the file. Here's the code

from crpropa import *

sim = ModuleList()

photons=True
electrons=True
neutrinos=True
nucleons=True

BField = Vector3d(0, 0.34*nG, 0)
B = UniformMagneticField(BField)

sim = ModuleList()
sim.add( PropagationCK(B) )
sim.add( FutureRedshift() )
sim.add( PhotoPionProduction(CMB, photons, neutrinos, electrons, nucleons) )
sim.add( PhotoPionProduction(IRB, photons, neutrinos, electrons, nucleons) )
sim.add( NuclearDecay(electrons, photons, neutrinos) )
for background in (CMB, IRB, URB_Protheroe96):
    sim.add( EMPairProduction(background, electrons) )
    sim.add( EMDoublePairProduction(background, electrons) )
    sim.add( EMTripletPairProduction(background, electrons) )
    sim.add( EMInverseComptonScattering(background, photons) )
sim.add( SynchrotronRadiation(B, False) )
sim.add( MinimumEnergy( 0.1 * EeV ) )

# periodic boundaries
sim.add(PeriodicBox(Vector3d(-1*Mpc, 0*Mpc, 0*Mpc), Vector3d(2801 * Mpc, 100 * Mpc, 100 * Mpc)))

obs = Observer()
obs.add( ObserverSurface( Plane(Vector3d(0, 0, 0), Vector3d(0, 5, 3), Vector3d(0,1,1)) ) ) # plane x=0 as observer surface
output = TextOutput('events.txt', Output.Event3D)
obs.onDetection(output)
sim.add(obs)

source = Source()
source.add( SourceUniformBox(Vector3d(4*Mpc, 0, 0), Vector3d(2796*Mpc, 100*Mpc, 100*Mpc)) )
source.add( SourceParticleType(nucleusId(1,1)) )
source.add( SourcePowerLawSpectrum(0.1 * EeV, 400 * EeV, -1) )

sim.setShowProgress(True)  
sim.run(source, 20000)

**Comment by Froehliche-Kernschmelze** [comment]
Hi,
thanks for your enquiry. When there is no process to absorb gamma-rays there should be a similar amount of neutrinos to photons being produced by PhotoPionProduction. Hence, EMPairProduction may reduce the absolute numbers of photons in your setup.

**Comment by avvliet** [comment]
Your minimal energy threshold of 0.1 EeV also plays an important role here. Any photon with a lower energy than that will not appear in your output.

**Comment by rafaelab** [comment]
This is not a CRPropa bug. Therefore, I will close the issue. Please reopen it if some rigorous sanity checks indicate otherwise.
