### ISSUE TITLE
Redshift evolution in PhotoPionProduction

### ISSUE THREAD

**Issue by lukasmerten** [CRPropa/CRPropa3#254]
**Description**

It seems that the redshift evolution is ignored in the current implementation of the PhotoPionProduction. Even for non CMB target fields the redshift dependence is turned off as for intended for the CMB. 

`void PhotoPionProduction::setPhotonField(PhotonField field) {
photonField = field;
if (haveRedshiftDependence) {
std::cout << "PhotoPionProduction ... " << std::endl;
haveRedshiftDependence == false;
}
...
}`

**To Reproduce**
from crpropa import *
EBL = IRB_Finke10
PPP = PhotoPionProduction(EBL, True, True, True, True, 0.1, True)

**Expected behavior**
No output

I have not checked any simulation results. However, the file rate_IRBz_Finke10.txt is not opened as I would have expected when including the redshift evolution.

**Comment by Froehliche-Kernschmelze** [comment]
Thanks for bringing this up, your findings are correct. See #255 for details.
