### ISSUE TITLE
1D simulation with magnetic field

### ISSUE THREAD

**Issue by mnogoslov** [CRPropa/CRPropa3#257]
Hi!

I'm trying to reproduce the paper in which it is said "For simulations presented in this work, we use the 1D-mode of CRPropa, where no deflections in magnetic fields are taken into account, and particles propagate rectilinear. In spite of that, energy losses of the electromagnetic cascades due to synchrotron radiation in IGMF are still considered."

Could you please recommend, which propagation module should I use to achieve such a result? SimplePropagation does not work with magnetic fields, and PropagationCK takes deflections into account. Is there any way to neglect the deflection? 

Thanks in advance for considering the issue!

**Comment by rafaelab** [comment]
I suppose the work to which you are referring was done CRPropa 2, whose structure is completely different from CRPropa 3.

In any case, you can take a look at the [documentation](http://crpropa.github.io/CRPropa3/) and the  [examples](https://github.com/CRPropa/CRPropa3-notebooks). 
For a 1D simulation you can use the SimplePropagation module, as described in the [wiki](https://github.com/CRPropa/CRPropa3/wiki), in combination with the SynchrotronRadiation module. 

Please refer to the documentation for further details.
