### ISSUE TITLE
Reenable swig --builtin

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#264]
builtin is broken with current swig versions (See https://github.com/swig/swig/issues/1595 and https://github.com/CRPropa/CRPropa3/pull/250). As soon as this is fixed we should:
- Create tests for the issue
- Enable builtin depending on the swig version

For swig 4.0.2 this issue will be apparently fixed: https://github.com/swig/swig/commit/cb5d7398b562e77436e5766fb17a40bfe8c4f973

**Comment by lukasmerten** [comment]
As Swig 4.0.2 is now released one year ago, we might again take a look at this issue.

**Comment by adundovi** [comment]
Is the issue fixed in the upstream?

**Comment by lukasmerten** [comment]
I have no idea. I was just quickly checking if Swig 4.0.2 was already released as @TobiasWinchen suggested that this swig version might solve the issue.

**Comment by TobiasWinchen** [comment]
The upstream bug is closed: https://github.com/swig/swig/issues/1595, but we have to test this of course

**Comment by adundovi** [comment]
OK, I'll test it with the newest Swig.

**Comment by TobiasWinchen** [comment]
4.0.2 is default in upcoming debain:bullseye, now in testing.
