### ISSUE TITLE
Quimby Includes Not Found

### ISSUE THREAD

**Issue by jplundquist** [CRPropa/CRPropa3#271]
Hello developers,

I have problems installing CRPropa with Quimby enabled on my system
**System Information:**
 - Operating system: Ubuntu Linux 18.04
 - Laptop or computing cluster? Desktop
 - Python version: 3.7.4
 - Swig version: 3.0.12
 - Cmake version: 3.10.2

**Did you install CRPropa from git or download a release?**
Installed from git release. Version 3.1.6-21

**Things that I checked:**
Compiling without Quimby works. All tests passed. Installed Quimby with no errors. CMakeLists.txt shows QUIMBY_INCLUDE_DIR:PATH=/usr/local/include/quimby/ and QUIMBY_LIBRARY:FILEPATH=/usr/local/lib/libQuimby.a. I have verified that Referenced.h, Vector3.h, and MagneticField.h, are all in /usr/local/include/quimby/ and the Quimby library path is correct.

**When installing with Quimby enabled I receive the following output:**
[ 86%] Generating crpropa_wrap.cxx
~/CRPropa3/python/2_headers.i:16: Error: Unable to find 'quimby/Referenced.h'
~/CRPropa3/python/2_headers.i:17: Error: Unable to find 'quimby/Vector3.h'
~/CRPropa3/python/2_headers.i:18: Error: Unable to find 'quimby/MagneticField.h'
CMakeFiles/crpropa-swig.dir/build.make:163: recipe for target 'crpropa_wrap.cxx' failed
make[2]: *** [crpropa_wrap.cxx] Error 1
CMakeFiles/Makefile2:462: recipe for target 'CMakeFiles/crpropa-swig.dir/all' failed
make[1]: *** [CMakeFiles/crpropa-swig.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TobiasWinchen** [comment]
Hi, it appears you found a bug in our CMake setup. Apparently, the optional parts such as Quimby, muParser and SAGA are not correctly included in the python interface. I created a fix in my [fork](https://github.com/TobiasWinchen/CRPropa3/tree/fix_cmake) you can try before the corresponding pull request https://github.com/CRPropa/CRPropa3/pull/272 is merged. Thank you for reporting.

**Comment by jplundquist** [comment]
Hello, thanks for the assist. I am now able to compile with no errors but make test fails for 16 through 19. The output is "*** CRPropa import failed
<class 'AttributeError'> module 'quimby' has no attribute 'MagneticField'"

**Comment by adundovi** [comment]
Looks to me like Quimby needs some updates to work with recent CRPropa versions. Where did you download Quimby? I notice that the original site and the repository is gone.

**Comment by jplundquist** [comment]
Doing a google search of quimby magnetic fields I found some way down this repository: https://git.rwth-aachen.de/3pia/forge/quimby
