### ISSUE TITLE
compile error at final steps

### ISSUE THREAD

**Issue by phobos17** [CRPropa/CRPropa3#28]
There seem to be some type-conversion errors in the generated file crpropa_wrap.cxx. Any idea which source file could be causing them? Thanks!

Error report:
...
[ 98%] Built target testModuleList
Scanning dependencies of target testSource
[ 99%] Building CXX object CMakeFiles/testSource.dir/test/testSource.cpp.o
Linking CXX executable testOutput
[ 99%] Built target testOutput
Scanning dependencies of target testVector3
[100%] Building CXX object CMakeFiles/testVector3.dir/test/testVector3.cpp.o
Linking CXX executable testPropagation
[100%] Built target testPropagation
/CRPropa3/build/crpropa_wrap.cxx:6810:27: error: 
      non-constant-expression cannot be narrowed from type 'size_t'
      (aka 'unsigned long') to 'npy_intp' (aka 'long') in initializer list
      [-Wc++11-narrowing]
      npy_intp dims[1] = {npix};
                          ^~~~
/CRPropa3/build/crpropa_wrap.cxx:6810:27: note: 
      insert an explicit cast to silence this issue
      npy_intp dims[1] = {npix};
                          ^~~~
                          static_cast<npy_intp>( )
/CRPropa3/build/crpropa_wrap.cxx:6815:24: error: 
      non-constant-expression cannot be narrowed from type 'size_type'
      (aka 'unsigned long') to 'npy_intp' (aka 'long') in initializer list
      [-Wc++11-narrowing]
      npy_intp size = {v.size()};
                       ^~~~~~~~
/CRPropa3/build/crpropa_wrap.cxx:6815:24: note: 
      insert an explicit cast to silence this issue
      npy_intp size = {v.size()};
                       ^~~~~~~~
                       static_cast<npy_intp>( )
/CRPropa3/build/crpropa_wrap.cxx:6822:24: error: 
      non-constant-expression cannot be narrowed from type 'size_type'
      (aka 'unsigned long') to 'npy_intp' (aka 'long') in initializer list
      [-Wc++11-narrowing]
      npy_intp size = {v.size()};
                       ^~~~~~~~
/CRPropa3/build/crpropa_wrap.cxx:6822:24: note: 
      insert an explicit cast to silence this issue
      npy_intp size = {v.size()};
                       ^~~~~~~~
                       static_cast<npy_intp>( )
/CRPropa3/build/crpropa_wrap.cxx:6835:24: error: 
      non-constant-expression cannot be narrowed from type 'size_t'
      (aka 'unsigned long') to 'npy_intp' (aka 'long') in initializer list
      [-Wc++11-narrowing]
      npy_intp size = {N};
                       ^
/CRPropa3/build/crpropa_wrap.cxx:6835:24: note: 
      insert an explicit cast to silence this issue
      npy_intp size = {N};
                       ^
                       static_cast<npy_intp>( )
Linking CXX executable testSource
Linking CXX executable testVector3
[100%] Built target testSource
[100%] Built target testVector3
4 errors generated.
make[2]: *** [CMakeFiles/crpropa-swig.dir/crpropa_wrap.cxx.o] Error 1
make[1]: *** [CMakeFiles/crpropa-swig.dir/all] Error 
make: *** [all] Error 2

**Comment by DavidWalz** [comment]
This looks like MagneticLens or ParticleMapsContainer (src/magneticLens/...)

**Comment by adundovi** [comment]
I suppose that these errors come when using clang as compiler (because there is no flag "-Wc++11-narrowing" in GCC). Clang is a default compiler on OS X, am I right?

The cause of these errors is in `python/crpropa.i`, in `*_numpyArray` extensions where we use constructions like these: `npy_intp size = {N};` which are not permitted, I presume, in C++11 in this way any more. If you use `-Wno-c++11-narrowing` in **CMAKE_CXX_FLAGS** I think that this can be avoided (as a workaround).

**Comment by adundovi** [comment]
I've noticed that for the same lines there are warnings in GCC5:
```
build/crpropa_wrap.cxx:6845:25: warning: narrowing conversion of ‘N’ from ‘std::size_t {aka long unsigned int}’ to ‘npy_intp {aka long int}’ inside { } is ill-formed in C++11 [-Wnarrowing]
       npy_intp size = {N};
```
So it should definitely be fixed. I can do it, but after PA Meeting next week.
