### ISSUE TITLE
Plotting large amount of data from CRPropa3 output

### ISSUE THREAD

**Issue by PrantikS** [CRPropa/CRPropa3#285]
The Examples of CRPropa3 use Python libraries for plotting. I have found that this method does not work for large amount of data. For example, I have simulated a source with 1 billion primary protons, which generates a huge amount of data after propagation. I am using similar code for plotting these data as given in examples. The code works perfectly for numbers of the order of 1 million, but fails when the number goes beyond. Is it a problem with Python plotting? Does using ROOT have a solution to this? Or any other way to resolve this issue, please suggest.

**Comment by rafaelab** [comment]
Hi!
Possible reasons are the limitation of memory of your computer, or the way python read files, which is very inefficient. 
Since this is not a question directly connected with CRPropa, I'll close the issue. But my suggestion is to change the way you read files in python, or try another package.

**Comment by rafaelab** [comment]
P.S.: If you decide to use ROOT, there is a plugin for CRPropa to generate outputs in that format: https://github.com/CRPropa/ROOTOutputPlugin

**Comment by TobiasWinchen** [comment]
You can plot large amounts of data with numpy, just bin the data in histograms (as ROOT does). Or just use ROOT. Of course if you store all data in a single txt file, this would probably be problematic - You are using hdf5, right?

**Comment by PrantikS** [comment]
I was using txt file, that might be the problem. This is really helpful. Thank you very much.





___________________
Best Regards,
Prantik Sarmah
________________________________

**Comment by lukasmerten** [comment]
@PrantikS, you might want to check python's library _pandas_, which is optimized for large data workflows. It works well together with numpy and matplotlib, too.
