### ISSUE TITLE
Possible problem with tabulated synchrotron data

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#288]
The file data/Synchrotron/spectrum.txt contains values above 1.0 for cumulative probabilities.

The header reads:
```
# x     : fraction synchrotron photon frequency to critical frequency
# log10(x)      CDF
#
```
And the last lines of the file are:
```
1.99000e+00     1.61326e+00
2.00000e+00     1.61326e+00
```
Therefore, there is a problem with either the comments (unlikely) or the data.  If the latter is true, this might affect the physics.

I will investigate this further.

**Comment by TobiasWinchen** [comment]
The code in randBin normalizes the distribution to 1, so probably only a normalization factor in generating the CDF from the spectrum has been ommitted in the table. I think to remeber that this is also the case in other tables. However, the number here should be in higher precision written to the file, as currently log10(x) is capped at 1.13 and not 2 as the file suggests - the resulting error is small though (and probably negligible).

**Comment by rafaelab** [comment]
Thanks, @TobiasWinchen.
I just checked that after posting this issue. 
Indeed the error is negligible, so there's nothing to worry about.  I will fix the calc_synchrotron.py script anyways, just for consistency.

**Comment by lukasmerten** [comment]
@rafaelab have you fixed the calc_synchrotron.py already? Let us know if you need some help with it. I marked the issue as a 3.2 milestone.

**Comment by rafaelab** [comment]
@lukasmerten 
There is no real problem here, but the precision of the table can be increased. This should be done together with the new version of CRPropa-data. 
Let's keep this issue open for control reasons, and close it once the data repo is updated.
