### ISSUE TITLE
LengthScale for Conditional Output

### ISSUE THREAD

**Issue by lukasmerten** [CRPropa/CRPropa3#29]
The new advanced TextOutput class has the possibility to choose the length scale for the outout file. Is there a similar option for the ConditionalOutput which I do not see? Or maybe the other way round: Is it possible to use the TextOutput with a condition argument? 
Best regards, Lukas

**Comment by DavidWalz** [comment]
There are no settings for units in ConditionalOutput and it will likely soon be dropped.
The following should work though:
```python
obs = Observer()
obs.add(ObserverSmallSphere(...))
t = TextOutput(...)
obs.onDetection(t)
```

**Comment by lukasmerten** [comment]
This might be a good solution in the case of one or more specified observer. However, for the development of the galactic diffusion module it would be really helpful to write out particles with a concrete trajectory length. To do so, I use the following procedure right now:

maxTra = MaximumTrajectoryLength(50*kpc)
maxtra.setRejectFlag("maxTrajectory", "Deactivated")
Out = ConditionalOutput("Output.txt", "maxTrajectory")

Since I need a better spatial resolution than the provided Mpc*10^-4 I changed the scaling in the OutputTXT.cpp file. This is of course not satisfactory.
If the ConditionalOutput is dropped I suggest to expand the TextOutput with a method similar to the conditional Output.

**Comment by DavidWalz** [comment]
Ok, the new way to do this is
```python
maxTra = MaximumTrajectoryLength(50*kpc)
maxTra.onReject(TextOutput(...))
```

**Comment by lukasmerten** [comment]
Works fine. Thanks a lot.
