### ISSUE TITLE
Simulations of cosmic rays for mixed compositions.

### ISSUE THREAD

**Issue by wilson-2015** [CRPropa/CRPropa3#295]
Hi,
I am looking for information(paper) that describes how to simulate UHECRs for mixed compositions i.e., H, He-4, N-14, Si-28, Fe-56. The example described on CRPropa webpage is not solving my problem. Any information will be much appreciated. 
Thank you.
Wilson.

**Comment by lukasmerten** [comment]
You can take a look at this https://ui.adsabs.harvard.edu/abs/2018JCAP...02..036E/abstract paper. There are quite some information on the re-weighting of the mixed compositions included. 

Since this is not directly related to the code, I'll close the issue.
