### ISSUE TITLE
fftw3 not found

### ISSUE THREAD

**Issue by PrantikS** [CRPropa/CRPropa3#297]
Dear developers,

I have problems installing CRPropa on my system
**System Information: (Please fill out the following information)**
 - Operating system: CentOS 6.6
 - computing cluster
 - Python version: 2.7.13
 - Swig version: 3.0.12
 - Cmake version: 3.9.6

**Did you install CRPropa from git or download a release?**
I installed version 3.1.6 from the releases.

**Things that I tried before asking for help:**
I read and followed the installation instructions at https://github.com/CRPropa/CRPropa3/wiki/Installation . Before writing this request I also checked previous installation issues at https://github.com/CRPropa/CRPropa3/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Ainstallation+ . However, this did not work. I receive the following output:

FFTW3 with single precision (FFTW3F): NOT Found!
--   Include:     /home/prantik/softwares/fftw3/include
--   Library:     FFTW3F_LIBRARY-NOTFOUND

I have installed fftw3 with single precision. Also set the path to libfftw3f.so library. But, it is still not working. Please tell  me why is it happening and what is the solution.

**Comment by rafaelab** [comment]
Dear Prantik,

This problem happens when libfftw3f.so is not being found by the system. This is not a CRPropa-related issue.

If you exported the directory wherein this file is in the LD_LIBRARY_PATH, it should work.
Alternatively, you can pass its path to cmake using the flag -DFFTW3F_LIBRARY=/path/to/libfftw3.so when running the command "cmake ..".

**Comment by PrantikS** [comment]
Thank you very much. It's working now with cmake flag. It's strange that it is not taking the LD_LIBRARY_PATH.



___________________
Best Regards,
Prantik Sarmah
________________________________
