### ISSUE TITLE
python wrapper: ModuleList, getModules 

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#30]
The method returns a swig object and not a list of modules as expected

**Comment by adundovi** [comment]
That's probably because of "-builtin" option in SWIG. A quick work-around would be to inherit ModuleList with a new ModuleList python class in `python/crpropa.i`. I'll try to do that, or revert to the old SWIG compilation if it won't work.

**Comment by adundovi** [comment]
@geromueller @DavidWalz 

I really don't know how to handle this actually (and it has nothing to do with -builtin, in both versions is the same).

The most elegant way (and probably the right way) would be to define `typemap(out)` for the function getModule():
```
%typemap(out) crpropa::ModuleList::module_list_t {
    $result = PyList_New(0);
    crpropa::ModuleList::module_list_t::iterator iter;
    for(iter = $1.begin(); iter != $1.end(); iter++){
        PyList_Append($result, SOMETHING(*iter));
    }
}
```

This doesn't work: I cannot match return value of the function with this typemap, and I don't know how to add Module() object to the list.

Second attempt is just awful, but we did this already in the lensing part:

```
%ignore crpropa::ModuleList::getModules() const;
%ignore crpropa::ModuleList::getModules();
%include "crpropa/ModuleList.h"

%extend crpropa::ModuleList{
    PyObject* getModules_new(){
        PyObject* list = PyList_New(0);
        crpropa::ModuleList::module_list_t::iterator iter;
        for (iter = $self->getModules().begin(); iter != $self->getModules().end(); ++iter) {
            PyList_Append( list, SOMETHING(*iter) );
        }
        return list;
    }
};

%pythoncode %{
class ModuleList(ModuleList):
    getModules = ModuleList.getModules_new
%}
```

This would work if I would know how to do this callback (SOMETHING) of C++ object to Python.

**Comment by adundovi** [comment]
Ok, I've made some progress, but now I don't understand what do we expect from this function in Python: to return list of pointers to included modules so we can change them on the fly? Wouldn't that be some violation of ownership?

```
%typemap(out) crpropa::ModuleList::module_list_t &crpropa::ModuleList::getModules() %{
    $result = PyList_New(0);

    for (crpropa::ModuleList::module_list_t::const_iterator it = $1->begin(); it != $1->end(); ++it){
        PyList_Append($result,
                      SWIG_NewPointerObj(SWIG_as_voidptr(*it),
                                         SWIGTYPE_p_crpropa__Module,
                                         SWIG_BUILTIN_INIT | 0)
                     );
        PyList_Append($result, PyInt_FromLong(0));
    }
%}
```
