### ISSUE TITLE
How to use Synchrotron radiation

### ISSUE THREAD

**Issue by PrantikS** [CRPropa/CRPropa3#306]
Hi,
I am using the following modules to propagate photons from protons:

sim = ModuleList()
sim.add( SimplePropagation(1*kpc, 100*Mpc) )
sim.add( Redshift() )
sim.add(PhotoPionProduction(CMB, photons, neutrinos))
sim.add(PhotoPionProduction(IRB, photons, neutrinos))
sim.add( EMPairProduction(CMB) )
sim.add(EMPairProduction(URB_Protheroe96,True))
sim.add(EMInverseComptonScattering(CMB,True))
sim.add(EMDoublePairProduction(CMB,True))
sim.add(EMDoublePairProduction(URB_Protheroe96,True))
sim.add(EMInverseComptonScattering(URB_Protheroe96,True))
sim.add(EMTripletPairProduction(CMB,True))
sim.add(EMTripletPairProduction(URB_Protheroe96,True))

How can I properly add Synchrotron radiation to this module list? Can you share a sample code on how to incorporate synchrotron radiation in 1D simulation?

**Comment by rafaelab** [comment]
Hi,

Synchrotron radiation is added just like any other interaction module. 
You can see how the function works in this [link](https://github.com/CRPropa/CRPropa3/blob/master/include/crpropa/module/SynchrotronRadiation.h). 

So the call is 
```sim.add(SynchrotronRadiation(bField, photons))```

The magnetic field is defined as those in the [examples](https://crpropa.github.io/CRPropa3/pages/example_notebooks/trajectories/trajectories.v4.html). 
Naturally, if you don't have magnetic fields, there is no synchrotron emission.

**Comment by PrantikS** [comment]
@rafaelab Thanks
