### ISSUE TITLE
printing Vector3d in python

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#31]
Vector3d is not printed correctly in python.
For example:
t = Vector3d(1, 2, 3)
print t returns Vector3d(1.0, 1.0, 1.0)
t.x, t.y,  and t.z display the correct values of the components. Operations such as t.dot or t.cross are also correct.

**Comment by adundovi** [comment]
This is embarrassing for me. I've made a mistake in `python/crpropa.i`:

From line 230 there should be:
```python
%extend classname {
        const std::string repr() {
            std::ostringstream buffer;
            buffer << "Vector( ";
            buffer << std::setiosflags(std::ios::fixed) << std::setprecision(3) << $self->x << ", ";
            buffer << std::setiosflags(std::ios::fixed) << std::setprecision(3) << $self->y << ", ";
            buffer << std::setiosflags(std::ios::fixed) << std::setprecision(3) << $self->z << " )";
            return buffer.str();
        }
}
```

I'll commit the fix.

**Comment by rafaelab** [comment]
The problem still persists in he newest version, according to Arjen's tests.
Also, when we do print vector it displays Vector3d(0.000, 0.000, 0.000). If we are dealing with number as small as 1e-9, the numbers are not displayed correctly. I think this is due to std::setprecision(3). Maybe you can change it to display 3 decimal digits in scientific notation.

**Comment by avvliet** [comment]
With Andrej's latest upload (of 3 hours or so ago) the first problem is fixed. The second one, showing "Vector3d(0.000, 0.000, 0.000)" for small values, is still there. But yes, it makes sense that this is due to std::setprecision(3)".

**Comment by adundovi** [comment]
Yes, setprecision(3) is unnecessary here. I put it because of pretty output, but with it I actually cut-off small values. I went through the code and saw that the usual practice is "%8.5f" for a formatted output (see OutputTXT.cpp), but it would be problematic too in this case, wouldn't it? So I've set-up scientific notation on 5 digits. Do you have any other suggestion?

**Comment by avvliet** [comment]
Yes, "%8.5f" wouldn't work in this case either. "%8.5e" would probably be okay in this case. Scientific notation on 5 digits probably gives the same output, should also be fine.
