### ISSUE TITLE
Galactic Lens - Correction with Rigidity?

### ISSUE THREAD

**Issue by cainaoliveira** [CRPropa/CRPropa3#310]
I have a question about the Lens for the Galactic Magnetic Field.

"The lens for the galactic magnetic field. Note that the energies refer to protons (Z=1). To be used with other particles with a different charge number please select the rigidity accordingly."

This means that I need to replace
              M.addParticles(Id, E, galactic_longitude, galactic_latitude, E0**-1)
by          M.addParticles(Id, E/Z, galactic_longitude, galactic_latitude, E0**-1)
?

Thanks

**Comment by cainaoliveira** [comment]
Someone can help me?

**Comment by TobiasWinchen** [comment]
Yes, `M.addParticles(Id, E/Z, galactic_longitude, galactic_latitude, E0**-1)` - so that the container will be filled based on rigidity rather than energy.
