### ISSUE TITLE
Issue with EMPairProduction and other EM modules 

### ISSUE THREAD

**Issue by ke-fang** [CRPropa/CRPropa3#317]
**Describe the bug**
`EMPairProduction` fails to run. Seems to be an issue related to SWIG wrapper. 

```
from crpropa import *
sim = ModuleList()
sim.add(SimplePropagation())
sim.add(Redshift())
sim.add(EMPairProduction(CMB,True))



Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "$home/CRPropa3/install/lib/python2.7/site-packages/crpropa/crpropa.py", line 7711, in __init__
    _crpropa.EMPairProduction_swiginit(self, _crpropa.new_EMPairProduction(photonField, haveElectrons, thinning, limit))
TypeError: Wrong number or type of arguments for overloaded function 'new_EMPairProduction'.
  Possible C/C++ prototypes are:
    crpropa::EMPairProduction::EMPairProduction(crpropa::ref_ptr< crpropa::PhotonField >,bool,double,double)
    crpropa::EMPairProduction::EMPairProduction(crpropa::ref_ptr< crpropa::PhotonField >,bool,double)
    crpropa::EMPairProduction::EMPairProduction(crpropa::ref_ptr< crpropa::PhotonField >,bool)
    crpropa::EMPairProduction::EMPairProduction(crpropa::ref_ptr< crpropa::PhotonField >)
```

**System (please complete the following information):**
 - Operating system: [iOS version 10.15.7] 
 - Desktop  
 - Python version: [2.7.18]
 - Swig version: [3.0.12]
 - Cmake version: [3.18.2]

**Comment by rafaelab** [comment]
Hi Ke,

This [change](https://github.com/CRPropa/CRPropa3/blob/master/CHANGELOG.md) was introduced in the 3.1.6 release.  
Now the photon fields should be called with parentheses:  CMB(), IRB_Gilmore12(), etc. 
The idea is to have a container that enables custom photon fields in the future.

Please let me know if this works.

**Comment by ke-fang** [comment]
That worked. Thanks, Rafa!
