### ISSUE TITLE
txt output modules not up-to-date and obsolet

### ISSUE THREAD

**Issue by kuempel** [CRPropa/CRPropa3#32]
txt output modules obsolet and not up-to-date. E.g. 1D example in wiki does not work (ObserverOutput1D). Should be fixed before release.

**Comment by DavidWalz** [comment]
Added TextOutput constructor argument for "1D events", "3D events", "1D trajectories" and "3D trajectories" and am updating the example notebooks.
Obsolete output modules now have deprecation warnings can be removed before publication.

**Comment by DavidWalz** [comment]
notebooks are updated

**Comment by geromueller** [comment]
Can i remove the obsolete modules?

**Comment by DavidWalz** [comment]
Yes.

**Comment by DavidWalz** [comment]
Example notebooks are changed
