### ISSUE TITLE
Can't find the Protheroe96 photon background.

### ISSUE THREAD

**Issue by PrantikS** [CRPropa/CRPropa3#325]
I have installed the latest version of CRPropa3 where the photon backgrounds are now classes. For Protheroe's 1996 radio background, I tried using the class URB_Protheroe96() but I am not able to find it. I have looked into the src and include but couldn't find it there. Did you remove this background, or if not what is the class name for it now?

**Comment by rafaelab** [comment]
The URB backgrounds were accidentally removed in a previous commit.
I have submitted a pull request (#315 ) which will hopefully soon be approved. In the mean time, you might want to use an earlier version which has this background available.

**Comment by PrantikS** [comment]
Okay. Thanks

**Comment by rafaelab** [comment]
Fixed with #315.
