### ISSUE TITLE
Data files for lenced GMF

### ISSUE THREAD

**Issue by wilson-2015** [CRPropa/CRPropa3#339]
Hi!,

I have done galactic lensing of extragalactic cosmic ray simulation and I would like to generate data files (scripts) for the lensed GMF simulations alongside the the sky maps. Any suggestion on how this can be done will be highly appreciated.

Regards,
Wilson.

**Comment by lukasmerten** [comment]
Hi Wilson 

I am not sure what exactly you are looking for, therefore I can only point you to our example page.
Take a look at our examples on lensing and backtracking to create lenses, e.g. [here ](https://crpropa.github.io/CRPropa3/pages/example_notebooks/galactic_backtracking/galactic_backtracking.v4.html). 

Please also note that we cannot offer specific support to analyse any simulation data. However, we will help with any concrete problems regarding your simulation itself. Reopen or open a new ticket for any specific problem.

Best, Lukas
