### ISSUE TITLE
Problems with Photon Fields in CRPropa 3.1.7+

### ISSUE THREAD

**Issue by ehlertd** [CRPropa/CRPropa3#340]
**Describe the bug**
I discovered two, possibly connected, problems with the background photon fields, in particular the EBL. These occur for CRPropa 3.1.7 and the latest github version but not for the older release 3.1.6. I have discussed this with @avvliet already and he has confirmed that he is getting the same problems/errors.

1. Insufficient production of cosmogenic neutrinos via interaction on the EBL, especially for UHE protons. For version 3.1.7+ the lower-energy bump in the cosmogenic neutrino spectrum is much smaller than expected from references in the literature. This effect occurs for all tested EBL models (Gilmore, Dominguez, Franceschini). Please compare:
![3](https://user-images.githubusercontent.com/41936305/119697039-539dce00-be3f-11eb-9aeb-c80f6e02ae00.png)
![4](https://user-images.githubusercontent.com/41936305/119697067-58fb1880-be3f-11eb-9e2f-9942c2309f48.png)
Left and middle column are results obtained with CRPropa 3.1.7. The change between different EBL models as well as the difference to no EBL at all is small but non-zero at the low-energy end.
Verification by @avvliet 
![NeutrinoComparison](https://user-images.githubusercontent.com/41936305/119697303-952e7900-be3f-11eb-9899-8a6fae64375f.png)
2. Misidentification of the photon fields if redshift depence is enabled in the PhotoPionProduction module. 
Setting `haveRedshiftDependence = True` for both CMB and EBL leads to errors in CRPropa 3.1.7+ but not in 3.1.6. If enabled for the CMB CRPropa fails to automatically disable the redshift dependence ( see `PhotoPionProduction.cpp` line 28+) but instead tries to look up the non-existent file of tabulated redshift dependence for the CMB.
![redshift_error_317_1](https://user-images.githubusercontent.com/41936305/119698659-facf3500-be40-11eb-93ef-bfe58d18d6bf.png)
On the other hand, after manually disabling redshift dependence for PPP on the CMB, in the next step there is a problem with CRPropa apparently mistaking the provided EBL field for the CMB and disabling the redshift dependence for the EBL.
![redshift_error_317_2](https://user-images.githubusercontent.com/41936305/119699416-ae382980-be41-11eb-8f9f-fd3a53f66318.png)

**To Reproduce**
The following script provides a minimal working version to reproduce the errors described above (rename from .txt to .py). Redshift dependence is enabled initially to showcase bug nr. 2. After removing the dependence it can be used to run the simulations for bug nr. 1. For CRPropa 3.1.6 the () behind the photon fields must of course be removed. Large differences in file-size of the cosmogenic neutrino output already indicate the difference between CRPropa 3.1.6 and 3.1.7+.
[crp_simulation_minimal.txt](https://github.com/CRPropa/CRPropa3/files/6548430/crp_simulation_minimal.txt)

**Expected behavior**
1. Correct production of cosmogenic neutrinos.
2. Correct identification of CMB and EBL fields when using `haveRedshiftDependence = True` for the PhotoPionProduction.

**System:**
 - Operating system: Scientific Linux release 7.8 (Nitrogen)
 - Laptop or computing cluster? cluster
 - Python version: 3.8.5
 - Swig version: 4.0.2
 - Cmake version: 2.8.12.2

**Comment by lukasmerten** [comment]
@ehlertd I hope we fixed this issue with #351. Please reopen this issue in case you still find some problems. Thanks again for detailed report.
