### ISSUE TITLE
Move CICD from travis-ci.org 

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#344]
travis-ci.org will close on June 15th, we need to move to keep our automated tests and builds of the documentation

Migration Guide:
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by lukasmerten** [comment]
I guess this has to be done by either you @TobiasWinchen  or @adundovi, because you are the organization owners.

**Comment by adundovi** [comment]
Hmm, I've moved it but now we have limited amount of credits... so maybe we should move it to GitHub Actions. [See this](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works).

**Comment by TobiasWinchen** [comment]
I also tried moving it, but it seems not to work and showing up 5yr old builds as most recent build. maybe a side effect for us both moving in parallel? I will keep my hands of this for now.

Reading the post, I think github actions are the way to go. However, as basically all other projects I am involved with are using gitlab.com or a private gitlab instance I am not that motivated to work on this.

**Comment by TobiasWinchen** [comment]
Note that also for github actions there is a a ressoruce limit of  2000 free minutes per month, but this can be easily extended with self-hosted shared runners if *somebody* is willing/can invest the ressources.

**Comment by lukasmerten** [comment]
I thought travis-ci.com was free for open source projects. But maybe I am mistaken. However, I can confirm that under "branches" the shown build for master is super outdated. Looking at "build history" seems to work.

**Comment by lukasmerten** [comment]
The last build #875 was already partially canceled since we ran out of credits. This means that we have no automated testing at the moment.
