### ISSUE TITLE
Missing online Documentation

### ISSUE THREAD

**Issue by lukasmerten** [CRPropa/CRPropa3#346]
**Describe the bug**
The link to the documentation gives a 404-page-not-found error.

**To Reproduce**
Try to follow the documentation link

**Expected behavior**
Find the latest documentation

**System (please complete the following information):**
-firefox

**Additional context**
Maybe related: I am also not able to build the documentation locally.
Seetings:
OS: Ubuntu 18.04
gcc: 7.5.0
python: 3.6.9
doxygen: 1.8.13
sphinx: 4.0.2
m2r2: 0.2.7 (I changed from m2r to m2r2 and updated the conf.py file accordingly as it was not working with m2r)
breathe: 4.30.0
ipython: 7.8.0

log file using m2r: [sphinx-err-gnw_s4lw.log](https://github.com/CRPropa/CRPropa3/files/6649665/sphinx-err-gnw_s4lw.log)

log file using m2r2: [sphinx-err-npxp4e6p.log](https://github.com/CRPropa/CRPropa3/files/6649636/sphinx-err-npxp4e6p.log)

**Comment by wilson-2015** [comment]
hi! I am not getting these instructions on how to access the documentation any further clarifications please? It appears I have to change the firefox configurations to the ones you have listed but I can't locate these options in my web browser. 
Thanks,
Wilson.

**Comment by bcmartinez38** [comment]
I am also unable to access the online documentation.

**Comment by lukasmerten** [comment]
Just a short update from my side:

Today I downgraded to the sphinx (and related modules) versions as given in  [travis configuration](https://github.com/CRPropa/CRPropa3/blob/master/.travis.yml). 
This leads at least on my system (see above) to many warnings and finally fails with something like "'nbformat.notebooknode.NotebookNode object' has no attribute 'widgets'". This made me think that the issue might be related to the ipython notebook parts of the documentation. 
Indeed, deleting all ipynb files allows to build the documentation (with several hundred warnings, but it is built). 

"Saving the notebook's widgets state" manually for a notebook (after it is has been restored) will also allow to build the documentation but gives the following warning:

"[...]/CRPropa3/doc/pages/galactic_cosmic_rays.rst:4: WARNING: toctree contains reference to document 'pages/example_notebooks/Diffusion/DiffusionValidationI.v4' that doesn't have a title: no link will be generated", e.g., if the DiffusionValidation.v4.ipynb file is restored and its widget state was manually stored.

"[...]Software/CRPropa3/doc/pages/example_notebooks/Diffusion/.ipynb_checkpoints/DiffusionValidationI.v4-checkpoint.ipynb: WARNING: document isn't included in any toctree" is also among the errors.

The corresponding page will not be included properly in the documentation.


From searching for this error in the web it seems that similar issues showed up in other projects but I could not transfer their solutions (see, e.g., https://github.com/pydata/xarray/issues/5299)

I am running out of ideas and appreciate any input.

**Comment by rafaelab** [comment]
I also failed to find a solution, @lukasmerten.

For the users (@wilson-2015, @bcmartinez38): In the meantime, you can access the notebooks with examples [here](https://github.com/CRPropa/CRPropa3/tree/master/doc/pages/example_notebooks).

If you need instructions of specific features, you can directly take a look at the [source code](https://github.com/CRPropa/CRPropa3/tree/master/include/crpropa). The header files should contain all information needed to make things work. In fact, the documentation is in large part generated from them.

**Comment by lukasmerten** [comment]
**Update**

It seems there were two independent issues with the documentation:

1) The widget state needs to be saved
2) The ipython/jupyter magic line `%matplotlib notebook` seems to be problematic. Changing to  `%matplotlib inline` seems to solve the problem. (Unfortunately, both problems were present in the notebooks I tested yesterday)

For the moment I am able to build a documentation locally. I will now take the chance to take a closer look at the documentation and do some smaller text updates etc. When this is finished I will try create a PR. Hopefully, the documentation will then be correctly build by travis-ci. Otherwise, I think about providing  a static version as a backup solution.
