### ISSUE TITLE
Extracted data-Folder Name Mismatch

### ISSUE THREAD

**Issue by ehlertd** [CRPropa/CRPropa3#354]
Hi,
I've encountered a minor problem in installing the latest CRPropa version from github (ed6f904) in the virtualenv approach. When running `make install` the command throws an error that the `.../build/data` directory does not exist. Looking at it in more detail the problem seems to be that the compressed data-yyyy-mm-dd.tar.gz file is not extracted to the folder data/ but rather to data-yyyy-mm-dd/
i.e. after the steps
```
CMAKE_PREFIX_PATH=$CRPROPA_DIR cmake -DCMAKE_INSTALL_PREFIX=$CRPROPA_DIR ..
make
```
the build directory looks like this
![Screenshot_20210805_095811](https://user-images.githubusercontent.com/41936305/128315510-1f579139-7c14-4a8e-b186-893437816998.png)

Simply renaming the data-yyyy-mm-dd/ folder to data/ fixes the issue and the installation runs successfully. However, the renaming causes a new problem: All the propagation modules are now installed into crpropa_xx/share/crpropa//data/... while in python apparently a structure of crpropa_xx/share/crpropa/... is expected. Simply removing one of the duplicate data depth-levels fixes the issue.

Conclusion: A simple band-aid fix of the issue is possible but a properly working installation process is probably preferable.

**System Information:**
 - Operating system: Scientific Linux release 7.8 (Nitrogen)
 - Laptop or computing cluster? cluster
 - Python version: 3.8.5
 - Swig version: 4.0.2
 - Cmake version: 2.8.12.2

**Did you install CRPropa from git or download a release?**
I installed version [ed6f904] from git/from the releases.

**Comment by lukasmerten** [comment]
Sorry for the late reply, but I think most of the CRPropa team was or still is on vacation. 

@ehlertd can you check if the linked PR fixes your problem?

**Comment by ehlertd** [comment]
Yes, after the change it works as intended.

**Comment by lukasmerten** [comment]
Perfect. As soon as someone officially approves the PR, I will merge it.
