### ISSUE TITLE
See progress bar in jupyter notebook?

### ISSUE THREAD

**Issue by cbadams2** [CRPropa/CRPropa3#356]
**Please describe what you want to do with CRPropa and you currently can't**
Currently the progress bar shows up when running python scripts using the CLI, but not in jupyter notebooks (assuming this is not a bug, and they are not expected to show up in notebooks - I'm not sure). Especially for people who are just getting started with CRPropa, this would be a great feature to allow more interactivity with the code upon first encountering it.

**Describe the solution you'd like**
Any way to get the progress bar to appear would be great. I came across [this](https://github.com/tqdm/tqdm/issues/394#issuecomment-384743637), which may be a possible solution, but am still trying to figure out how to implement it in my case.

**Describe alternatives you've considered**
CLI is a perfectly workable alternative, and this request is not at all a necessity.

**Comment by lukasmerten** [comment]
Is this still an issue?

On my machine with CRPropa 3.2+ and jupyter notebook version 6.5.2, I do get the progress bar automatically.

**Comment by lukasmerten** [comment]
I'll close it for now. Please reopen if that's still an issue.
