### ISSUE TITLE
Installation on Linux mint

### ISSUE THREAD

**Issue by wilson-2015** [CRPropa/CRPropa3#359]
Hi!

I have a problem installing crpropa on Linux mint version 19. I have installed from git using system path procedures and I have followed the instructions perfectly well.

I have installed all the necessary packages including swig version 3.0.12. All the tests also ran successfully after installation.

However, crpropa doesn't run when I import it and it gives this error:                                                                              
"""ModuleNotFoundError: No module named 'crpropa' """

Is there anything that I have left out? Below is a preview of the output when I run cmake::

wilson@wilson-HP-Laptop-14-bs1xx:~/CRPropa3/build$ cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/.local
-- The Fortran compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use --as-needed linker flags!
-- Build Type: Release
-- CRPropa version: 3.1.7-99-gdaacf7ab daacf7abaa8f4167a05007a1977e5f9d648a69d1 refs/heads/master
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
Using provided EIGEN
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Google perftools: NOT Found!
--   Include: GOOGLE_PERFTOOLS_INCLUDE_DIR-NOTFOUND
-- FFTW3 with single precision (FFTW3F): NOT Found!
--   Include:     FFTW3F_INCLUDE_DIR-NOTFOUND
--   Library:     FFTW3F_LIBRARY-NOTFOUND
-- Quimby: NOT Found!
--   Include:     QUIMBY_INCLUDE_DIR-NOTFOUND
--   Library:     QUIMBY_LIBRARY-NOTFOUND
-- SAGA: NOT Found!
--   Include:     SAGA_INCLUDE_DIR-NOTFOUND
--   Library:     SAGA_LIBRARY-NOTFOUND
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- muParser: NOT Found!
--   Include:     MUPARSER_INCLUDE_DIR-NOTFOUND
--   Library:     MUPARSER_LIBRARY-NOTFOUND
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /home/wilson/anaconda3/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/home/wilson/anaconda3/lib/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.2") found components:  C 
-- Use absolute RPATH /home/wilson/.local/lib
-- Downloading data file from crpropa.desy.de ~ 65 MB
-- Extracting data file
-- Build of documentation disabeled. Enable with BUILD_DOC=On
-- Found PythonInterp: /home/wilson/anaconda3/bin/python (found version "3.7.1") 
-- Found PythonLibs: /home/wilson/anaconda3/lib/libpython3.7m.so (found version "3.7.1") 
-- Found SWIG: /usr/bin/swig3.0 (found suitable version "3.0.12", minimum required is "3.0") 
-- Python: Found!
--   Version:     3.7/37
--   Executeable: /home/wilson/anaconda3/bin/python
--   Include:     /home/wilson/anaconda3/include/python3.7m
--   Library:     /home/wilson/anaconda3/lib/libpython3.7m.so
--   Site-package directory: /home/wilson/.local/lib/python3.7/site-packages
WARNING,The SWIG builtin option should not be used with SWIG version below 4.0.2 due to https://github.com/swig/swig/issues/1595
-- Found numpy headers in /home/wilson/anaconda3/lib/python3.7/site-packages/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wilson/CRPropa3/build

**Comment by TobiasWinchen** [comment]
From your output I see is that you use anaconda python next to the system python. Please make sure that the site package directory you are installing CRPropa into  (/home/wilson/.local/lib/python3.7/site-packages) is used by your anaconda python installation as module search path.

**Comment by wilson-2015** [comment]
Hi Tobias! 
Basically this is the problem I have been facing. I have been trying to make anaconda aware of the directory where crpropa is installed but it is not working, which is strange.

**Comment by TobiasWinchen** [comment]
Please note that our documentation so far does not cover the anaconda python case, and I have not used anaconda myself so far. Where does anaconda python put packages that are installed via pip / setuptools? From the CMake output I would guess that this is somewhere under /home/wilson/anaconda3 - possibly it makes sense to also install CRpropa under the anaconda directory using it as install prefix? Consider making a backup of the anaconda directory before trying this in case this damages the setup. You should probably check with the anaconda documentation on how to add 3rd party software to anaconda correctly.

**Comment by wilson-2015** [comment]
Hi Tobias!
Installing crpropa under anaconda has worked now running thank you very much.
