### ISSUE TITLE
multiple observers

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#37]
When using three observers only the one last added to the mode produces output.
Example:
```
obs1 = Observer()
obs1.add(ObserverSmallSphere(position, size1))
obs1.onDetection(TextOutput(out1))
obs2 = Observer()
obs2.add(ObserverSmallSphere(position, size2))
obs2.onDetection(TextOutput(out2))
...
m.add(obs1)
m.add(obs2)
``` 
Only out2 has non-zero size, even if the observers are identical. 

This might be related to the default option makeInactive=True, which renders a candidate inactive when crossing the sphere. Manually hard-coding `Observer::Observer() : makeInactive(false)` solves the problem, but is not elegant. Maybe a function to control it more easily should be implemented. In principle, the deprecated ConditionalOutput module would fix this, since outputs would be written depending on the flag.

**Comment by geromueller** [comment]
fixed
