### ISSUE TITLE
New feature in CRPropa 3.2: Targeting

### ISSUE THREAD

**Issue by wilson-2015** [CRPropa/CRPropa3#380]
The simulations of UHECRs are emitted isotropically from their sources and undergo deflections through IGMF before detection at the observer sphere. Obtaining enough statistics in this scenario is usually computationally intensive.  Personally I have been solving this problem by calculating the cosmic ray emission angle at the source and injecting particles through a small opening angle.

A new approach has been described in CRPropa 3.2 known as targeting method  that maximizes the number of cosmic ray hits, based on von Misses Fisher distribution. This method is also described in this paper POS(ICRC2019)447.  

I have looked around and could not get a way of implementing this in my simulation script. Any further guideline on how to do this or a snippet code will be highly appreciated.

**Comment by lukasmerten** [comment]
The CRPropa 3.2 has not yet been published but will contain a more detailed description of the targeting feature. In addition, there is already an example [ipython notebook](https://github.com/CRPropa/CRPropa3/tree/master/doc/pages/example_notebooks/targeting) included in the current master branch.

**Comment by wilson-2015** [comment]
Thanks Lukas, this is exactly what I was looking for.
