### ISSUE TITLE
Custom Photon Field - Problems in creating

### ISSUE THREAD

**Issue by cainaoliveira** [CRPropa/CRPropa3#381]
Hi

I am trying to create and implement a custom photon field following the steps of this wiki page
https://github.com/Froehliche-Kernschmelze/CRPropa3/wiki/How-to-create-and-use-custom-photon-fields
I already have a table in the format described.

Unfortunately, I am not able to find the helper file called generate_tabFiles.py, and did not find a clear answer in the last issues. I am using CRPropa3.1.7.

There is an (easy) way to create a custom photon field? I am particularly interested in the photodisintegration process, but the others energy loss processes must be important to me in future analysis.

Thank you so much
Cainã

**Comment by lukasmerten** [comment]
Hi @cainaoliveira 

The short answer is: There is not yet an easy option to implement custom photon fields in CRPropa 3.1.7. 

This option will be added in version 3.2. Most part of the functionality are already included in the current master branch, but we cannot offer support for the feature at this stage.

Already clear is that you will also need functionality (mainly computing pre-calculated data on interaction rates etc.) that is implemented in the crpropa-data repository. 

A more detailed documentation on how to use custom photon fields will be released with version 3.2 or shortly after.

So stay tuned and do hesitate to re-open this issues if things are unclear after the upcoming release.
