### ISSUE TITLE
CPropa3 installation make tests fail

### ISSUE THREAD

**Issue by VasundharaShaw** [CRPropa/CRPropa3#386]
Hello,

I am trying to install CRPropa3 on MacOs 12.1 (21C52).  I used both cmake and CMAKE_PREFIX_PATH=$CRPROPA_DIR cmake -DCMAKE_INSTALL_PREFIX=$CRPROPA_DIR \
-DPYTHON_EXECUTABLE=/usr/local/Cellar/python/3.7.4/bin/python3 \
-DPYTHON_LIBRARY=/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7.dylib \
..

"make" runs without bugs but "make tests" fails.

Any suggestions will be helpful. Thank you.

**Comment by JulienDoerner** [comment]
Hey @VasundharaShaw, 

could you give some more information which tests are failing? Or what is the output of `make test`?

**Comment by JulienDoerner** [comment]
hey @VasundharaShaw, 

could you check the output of the mentioned file
> /Users/frederikanderssohn/CRPropa3/build/Testing/Temporary/LastTest.log

and post it here. 

So that python can find crpropa it is neccessary to run first `make install`. Please try to run it and check if the errors of `make test` still exist.

**Comment by VasundharaShaw** [comment]
[LastTest.log](https://github.com/CRPropa/CRPropa3/files/7913583/LastTest.log)

Hi @JulienDoerner 

I have uploaded the Log file. And i did run make install afterwards make test. But the tests still fail. Its also in the log file.

Please let me know if this is the file you were asking.

**Comment by JulienDoerner** [comment]
Hi @VasundharaShaw, 

thanks for the log file. This is what I meant. I will have a look in it later on.

**Comment by lukasmerten** [comment]
@VasundharaShaw: I'll close this issue due to inactivity. Please reopen it in case the problem persists.
