### ISSUE TITLE
Simulation hangs on random position

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#39]
Sometimes I have an issue in which running simulation (for example benchmark scenario) stops without apparent reason and without any additional output. It looks like it's running but there is no advancement of progress bar or anything. Behaviour seems random and I cannot locate the cause. 

The same problem is having Stefan who has sent me an e-mail in which he writes:

> I've been doing some CRPropa runs using the updated version, the ouput is as expected, so everything seems to work fine. There's only one problem: some runs are terminated before they are finished (most times after he already did >90% of the work...). The output data we need has to be of roughly the same size for comparison, so we cannot use these runs and, as ~ every 5th run is terminated too early, much computation time is lost.
>
> The last status output of CRPropa is something like:
>
> Started Mon Jul 20 20:32:55 2015 : [=========>]  91%    Finish in: 01:18:55
>
> it prints this for every completed 1%, so he doesn't tell me any reason why it was terminated, nor does he even tell me, that it was terminated. (Usually, when I terminate a run manually, these lines appear much faster until he reached 100% so the status output is like that of a successful run. Here instead he just stops calculating so the status output stops at some point.)

and more...

> Well, the frequency of that error is pretty unstable, so it's hard to tell how often it happens (I didn't count the errors).
> I do runs with 10^7 particles per run and in the single thread case I got 4 runs without  errors but the fifth broke after 60%-70%.
> For the other runs, I sometimes loose runs pretty fast (e.g. run is lost, the next is good, but the over-next is lost again), but then sometimes I get 10 runs in a row, but I guess every fifth run is a good guess.
>  
> I cannot remember any such issues when I was using the old version. Back then I mostly produced runs with 10^5 or 10^6 particles and only 5 with 10^7, so maybe that can make a difference. Apart from that I do nothing different. 

First I thought that it has something to do with multi-threading when it encounters some thread conflicts, but apparently the same problem occurs in single-thread (even I still need to confirm this). 

Another possibility is that the problem lies PhotoPionProduction module because when it's skipped there is no evidence of these sudden stops of simulations.

I'll try to further investigate the issue myself but I'm wondering if anyone else has experienced the bug?

**Comment by geromueller** [comment]
Hi,

i have not encountered this behaviour. Try compiling with debug symbols,
and when it hangs, attach to the process unsing gdb. You can then see in
which function it hangs.

Gero

Am 20.08.2015 um 15:42 schrieb Andrej:

**Comment by geromueller** [comment]
Okay, i have the same behaviour. Random crashes without notice. I will look into it.

**Comment by geromueller** [comment]
In 7d3ab5d7c32cedc92e056144d9d4891648e5a689 i fixed a sophia bug. Maybe this solves your problem too. Closing for now.

**Comment by adundovi** [comment]
I don't know because it's hard to reproduce it, but I didn't encounter it for a long time by now. Maybe it's solved. :-)
