### ISSUE TITLE
ParticleMapsContainer::addParticlesFromFile broken

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#40]
ParticleMapsContainer::addParticlesFromFile is incompatible with the new TextOutput format.

I cannot import detected particles into ParticleMapContainer with addParticlesFromFile method because it differs from TextOutput(). I've got an empty list without any error message.

**Comment by adundovi** [comment]
The difference between old and the new format in "3D events":
new: D, z, ID, E, X, Y, Z, Px, Py, Pz, ID0, E0, X0, Y0, Z0, P0x, P0y, P0z, ID1, E1, X1, Y1, Z1, P1x, P1y, P1z
old: D, ID, ID0, E, E0, X, Y, Z, X0, Y0, Z0, Px, Py, Pz, P0x, P0y, P0z,z

**Comment by rafaelab** [comment]
TextOutput("3D events") generates the output in the "old" format (which is not deprecated).

**Comment by adundovi** [comment]
Ok, tnx. I didn't realize that... I've forgotten to put "outputtype" after filename so I've ended up with enableAll(). But, nevertheless, what is the purpose of enableAll()?

**Comment by rafaelab** [comment]
EnableAll keeps record of the points where particles were generated. It is useful when you need to identify common ancestors. 
Maybe this shouldn't be the default behaviour though.
