### ISSUE TITLE
README for premade lenses?

### ISSUE THREAD

**Issue by angelinapartenheimer** [CRPropa/CRPropa3#402]
Hello,

I was wondering if there is any information about how the premade lenses at https://www.desy.de/~crpropa/data/magnetic_lenses/ are created. The lens I made using the backtracking simulation and createlens.py codes listed here https://crpropa.github.io/CRPropa3/pages/example_notebooks/galactic_backtracking/galactic_backtracking.v4.html on the documentation page is not able to recreate the example at https://crpropa.github.io/CRPropa3/pages/example_notebooks/galactic_lensing/lensing_cr.v4.html. I was hoping that some information on how a premade lens was created could shed light on my issue.

Thanks so much,
Angelina Partenheimer

**Comment by rafaelab** [comment]
Hi Angelina,
Information on how to create a lens is available on the documentation, under [Galactic Backtracking](https://crpropa.github.io/CRPropa3/pages/example_notebooks/galactic_backtracking/galactic_backtracking.v4.html). At the end of the page there is a section on how to generalise the example provided. The [script](https://github.com/CRPropa/CRPropa3-data/blob/master/create_lens.py) linked on this page allows you to create the lens.
