### ISSUE TITLE
How to calculate secondary neutrinos?

### ISSUE THREAD

**Issue by kosmos0001** [CRPropa/CRPropa3#41]
I tried to write a source code NeutrinoOutput1D.cpp similar as PhotonOutput1D.cpp (also NeutrinoOutput1D.h) to calculate secondary neutrinos.  I changed  "if ((pid != 22) and (abs(pid) != 11))"  to  "if ((abs(pid) != 12) and (abs(pid) != 14))", then recompile the code, but it seems doesn't work.

**Comment by DavidWalz** [comment]
The standard output modules are suitable for neutrinos as well.
I added an example for a simulation with secondary neutrinos [here](http://nbviewer.ipython.org/github/CRPropa/CRPropa3-notebooks/blob/master/secondaries/neutrinos.v4.ipynb).
