### ISSUE TITLE
Neutrinos low energy

### ISSUE THREAD

**Issue by RodSasse** [CRPropa/CRPropa3#421]
Recently I've been working with simulations using neutrino propagation, as in the example (https://crpropa.github.io/CRPropa3/pages/example_notebooks/secondaries/neutrinos.v4.html). I realized that only high energy neutrinos are saved, as shown in the plot:
![PlotGitHub](https://user-images.githubusercontent.com/64110680/218557789-5165b97a-0bf5-4757-95d8-510dc6daafb9.png)

Is it possible to save low energy neutrinos (range of 10e8 eV to 10e15 eV) generated from the propagation of UHECR?

Best,
Rodrigo

**Comment by lukasmerten** [comment]
You can try to lower the MinimumEnergy of your simulations, which might help a bit.

However, I am not sure how photopion production with the CMB and EBL as your photon target fields will generate neutrinos with energies as low as 10^8 eV. As a rough estimate neutrinos from these interactions will receive an energy E=E_prim/20. So for a 10^14 eV neutrino you would expect the primary to have an energy ~20 PeV. However, primaries with such low energies cannot kinematically produce neutrinos for low energy target such as the EBL and CMB.
