### ISSUE TITLE
Regarding about the back tracking method.

### ISSUE THREAD

**Issue by KyleIm** [CRPropa/CRPropa3#425]
Hello my name is Kyle and I am a student working on an UHECR group. I appreciate for this open source software because I am relying on this a lot for my research.

So, I have a little confusion about the backtracking method using CRPropa.

https://crpropa.github.io/CRPropa3/pages/example_notebooks/galactic_backtracking/galactic_backtracking.v4.html#Backtracking-a-single-cosmic-ray

In a single-cosmic ray backtracking method the example used the pid as anti proton. Does this mean that this example is assuming the particle to be anti-proton because 'it is actually proton, but we want to make this particle move opposite direction to JF12 model because we want to backtrack where it was before'. or is there another reason why it choose anti-proton for the cosmic ray candidate?

I was following this example with actual observation dataset from our experiment and I changed the pid to be proton and recently I realized something seem to be wrong and reading the documentation again.

**Comment by rafaelab** [comment]
Usually one is interested in the motion of a particle of charge Q to Earth. To track it back, one should consider the equivalent antiparticle, of charge -Q.  This way, charge-time symmetry is preserved. 
CRPropa doesn't know if you are doing forward or backward propagation, so the only way to tell the code to do what you want is to change the charge. Therefore, if you are interested in the behaviour of protons, you should inject antiprotons when doing backtracking.
