### ISSUE TITLE
observer onDetection doesn't work as expected

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#43]
From the following code:

# observer
obs = Observer()
obs.add( ObserverPoint() )
sim.add( obs )  

# output
output_txt = TextOutput(outfile[:-4] + "txt")
obs.onDetection(output_txt)
output_root = ROOTEventOutput1D(outfile)
obs.onDetection(output_root)

I would expect the same output in both files. Currently, the output is only recorded in one file.

**Comment by geromueller** [comment]
onDetection takes a single module. To have the output in both files use
another ModuleList containing both outputs.

Am 28.09.2015 um 14:51 schrieb Tobias Winchen:

**Comment by DavidWalz** [comment]
What do you suggest Tobias?

**Comment by adundovi** [comment]
Does it make sense to use two observers with the same properties in a single ModuleList (except the different onDetection action, plus one of them shouldn't deactivate the candidate on hit)?

**Comment by DavidWalz** [comment]
Using a ModuleList as Gero proposes is simpler than using two observers with the same properties
I think it's not necessary to extend Observer to take any number of onDetection Modules.
