### ISSUE TITLE
A free line in the lense data will lead to an error when loading a lense

### ISSUE THREAD

**Issue by MarcusWirtz** [CRPropa/CRPropa3#44]
Input:
from crpropa import *
lens = MagneticLens('pathto/lens.cfg')

Output:
 ERROR READING LINE:
    ... line skipped!

**Comment by TobiasWinchen** [comment]
Dear Marcus,

On Monday 12 October 2015 02:31:45 MarcusWirtz wrote:
> Input:
> from crpropa import *
> lens = MagneticLens('pathto/lens.cfg')
> 
> Output:
>  ERROR READING LINE:
>     ... line skipped!


thank you for your report, the output may indeed be somewhat misleading. 
Although there is an `error' reading the line, as it doesn't describe a 
lenspart, the program will continue and the line only be skipped. 

Cheers,


Tobias
