### ISSUE TITLE
Failing example notebook for secondary

### ISSUE THREAD

**Issue by JulienDoerner** [CRPropa/CRPropa3#467]
Currently the example notebooks `secondaries/photons.ipynb` and `secondaries/secondary_photons.ipynb` raise an error: 

    Exception in crpropa::ModuleList::run: 
    std::bad_alloc

I traced this error down to `sim.add(EMInverseComptonScattering(URB_Protheroe96(),True))`. With changing the photon field from Proteroe96 to Nitu21 the error does not ocurre anymore. 
This is also related to the failings of the crpropa-example-test.

**Comment by JulienDoerner** [comment]
The photon field `URB_Fixsen11` gives the same propblem.

**Comment by rafaelab** [comment]
I think the problem has to do with the limits of the tabulated data for some models. I've tried adding some `if`s to fix it, with no success.

**Comment by JulienDoerner** [comment]
I found the error to be related to the sampled center of mass energy. It is possible to sample slighly larger energies than the upper limit of the tabulated range $(s > 10^{23} \, \mathrm{eV}^2)$. Therefore the tabulated range in the `ICSSecondariesEnergyDistribution` is not sufficient enough. Increasing this upper bound of the table by a factor 2 should be enough. 

I will prepare a PR to provide this fix.

**Comment by rafaelab** [comment]
Exactly, @JulienDoerner.
A good reference would be the minimum among all background photon energies (~1e-10 eV for URB) times the maximum energy we wish to treat (~1e22 eV), squared. That would be ~1e24 eV^2.

> I found the error to be related to the sampled center of mass energy. It is possible to sample slighly larger energies than the upper limit of the tabulated range (s>1023 eV2). Therefore the tabulated range in the `ICSSecondariesEnergyDistribution` is not sufficient enough. Increasing this upper bound of the table by a factor 2 should be enough.
> 
> I will prepare a PR to provide this fix.
