### ISSUE TITLE
Loading TF17 man

### ISSUE THREAD

**Issue by VasundharaShaw** [CRPropa/CRPropa3#482]
Hello 
I am trying to use the TF17 model and I want to load different configurations of the model so for example "Ad1" disc model and "C0" halo model. This is how I call the field:

  bField  = TF17Field("Ad1","C0") . 
  
 I have attached the error below. Its not clear to me how can call different components of TF17.  

Thanks!
![Screenshot 2024-04-16 at 11 39 07](https://github.com/CRPropa/CRPropa3/assets/51244533/82066eb2-05f2-4d67-92b0-c0d9fe5b436a)

**Comment by JulienDoerner** [comment]
hey @VasundharaShaw, 
CRPropa defines seperate varaibles for the models. You can use them like 
` bfield = TF17Field(TF17DiskModel_Ad1, TF17HaloModel_C0)` 
where you can change the disk model to `Ad1`, `Bd1` and `Dd1` as well as the halo models `C0` or `C1`.

I hope this answers your question.

**Comment by VasundharaShaw** [comment]
@JulienDoerner Thanks a lot. It works now!
