### ISSUE TITLE
grid.get() in Python

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#50]
When doing print grid.get(i, j, k) in python, I get:

    <Swig Object of type 'float *' at 0x109f21750>

I've tested this with a ScalarGrid.

Probably crpropa.i needs some modifying to dereference this SWIG float reference.

**Comment by adundovi** [comment]
Why do we have get() and getValue() if we expect to get value from get()?

[Here](https://github.com/CRPropa/CRPropa3/blob/46be4a6a727b8842f4ca883ba17d046f1b5d3c23/include/crpropa/Grid.h#L122):
```
	/** Accessor */
	const T &get(size_t ix, size_t iy, size_t iz) const {
		return grid[ix * Ny * Nz + iy * Nz + iz];
	}

	T getValue(size_t ix, size_t iy, size_t iz) {
		return grid[ix * Ny * Nz + iy * Nz + iz];
	}
```

We could override get() with getValue() when accessing it from python, but that will not be consistent with the C++ interface.

**Comment by adundovi** [comment]
If we decide to repurpose grid.get(), I'll re-open this bug report.
