### ISSUE TITLE
CRPropa3 versioning

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#66]
I see that you pick 1.0 for the first release? Why not 3.0? :-)
Maybe keeping versions globally consistent (CRPropa3 >= 3.0) would avoid some ambiguity among users... And I don't see what we lose with that.

**Comment by kuempel** [comment]
Yes, the release should be 3.0. Probably the label is only a placeholder...

**Comment by adundovi** [comment]
Ok. Fixed.
