### ISSUE TITLE
Failed to build CRPropa

### ISSUE THREAD

**Issue by eicheB** [CRPropa/CRPropa3#67]
I just tried to update CRPropa, but due to some reason it failed (see CRPropa_failed2build.txt)...any ideas?

[CRPropa_failed2build.txt](https://github.com/CRPropa/CRPropa3/files/184159/CRPropa_failed2build.txt)

**Comment by adundovi** [comment]
I've just commited 4f09bc7 which fixes it. Please try again with the newest version.
