### ISSUE TITLE
File download

### ISSUE THREAD

**Issue by DavidWalz** [CRPropa/CRPropa3#79]
Although not listed we currently require wget (curl for Apple users) for downloading the data files.
wget is not provided by default on e.g. Archlinux, thus we should state wget as a dependency and add a suitable error message when running cmake.

Alternatively, we could start using the FILE(DOWNLOAD ... EXPECTED_MD5SUM) command which is available as of CMake 2.8.2.
For Apple we are requiring 2.8.12 already (for the relative path issue), so this wouldn't be an issue.
Current Linux distributions should also be > 2.8.2, including SL6.

Using FILE(DOWNLOAD ... ) we would profit from someone else already having solved our problem and get rid of 50+ cmake lines.
Should we make the change?

**Comment by adundovi** [comment]
Generally, I don't see why not - the less dependencies the less maintenence and possible pitfalls.

**Comment by TobiasWinchen** [comment]
Hi,

On Monday 30 May 2016 05:05:40 David Walz wrote:
> Although not listed we currently require wget (curl for Apple users) for
> downloading the data files. wget is not provided by default on e.g.
> Archlinux, thus we should state wget as a dependency and add a suitable
> error message when running cmake.
> 
> Alternatively, we could start using the FILE(DOWNLOAD ... EXPECTED_MD5SUM)
> command which is available as of CMake 2.8.2. For Apple we are requiring
> 2.8.12 already (for the relative path issue), so this wouldn't be an issue.
> Current Linux distributions should also be > 2.8.2, including SL6.
> 
> Using FILE(DOWNLOAD ... ) we would profit from someone else already having
> solved our problem and get rid of 50+ cmake lines. Should we make the
> change?

I can think of no reason why not -


Cheers,


Tobi

**Comment by DavidWalz** [comment]
Thanks for the input! Closed with c2bdda8f3155fc28f0ee0a6f4d6ea4429161438e.
