### ISSUE TITLE
Git info

### ISSUE THREAD

**Issue by DavidWalz** [CRPropa/CRPropa3#80]
Andrej added a version info functionality, reading e.g. 3.0-62-g74aa3a0 for
-  current tag: 3.0
-  number of commits after tagging: 62
-  hash of current commit: 74aa3a0

Andrej and I suggest to add this info to
- TextOutput
- HDF5Output
- (ROOT - Outputs)
- `crpropa.__version__`
- ipython-notebook examples

If there's no objections we'll add this soon.
Additional ideas how to promote and use this info are welcome.

**Comment by adundovi** [comment]
In addition, I would suggest that we introduce some kind of a [doctype](https://en.wikipedia.org/wiki/Document_type_definition)-function which would be included in a header of every steering card. Basically, it can only be a comment like
```python
# version: 3.0-62-g74aa3a0 
```
or we could define functional "comment":
```python
declare_version("3.0-62-g74aa3a0")
```
which would not only bookkeep the crpropa version used with the steering card, but also print a warning in a case of version mismatch (if the warning parameter is set to true).
```
WARNING: Version mismatch. To clear this warning review the
steering card for potential incompatibilities and update its version
declaration or install declared version of CRPropa.
To get the differences use:
git diff 74aa3a0 259f138
```

What do you think? Should we implement this in C++-part or in SWIG interface?

**Comment by adundovi** [comment]
Implemented for TextOutput, for HDF5Output and introduced declare_version(). See [FAQ](https://github.com/CRPropa/CRPropa3/wiki/FAQ).
