### ISSUE TITLE
SWIG, inheritance and protected methods

### ISSUE THREAD

**Issue by adundovi** [CRPropa/CRPropa3#83]
It seems that SWIG cannot expose C++ protected methods to Python in a case where one would like to inherit an abstract class (e.g. crpropa.AbstractCondition) and use its protected methods (e.g. reject()) in a derived class [1].

Should we provide public methods which would expose protected ones in cases of classes which would likely be re-used in Python?

Thanks @lukasmerten for spotting this.

[1] http://www.swig.org/Doc2.0/SWIGDocumentation.html#SWIGPlus_nn15

**Comment by DavidWalz** [comment]
> Should we provide public methods which would expose protected ones in cases of classes which would likely be re-used in Python?

What would be a use case?

**Comment by adundovi** [comment]
> What would be a use case?

Custom breaking conditions modules. Maybe @lukasmerten would like to explain more.

**Comment by geromueller** [comment]
Hi,

this should be done by the "-dirprot" command line option. It is on by 
default.

self.reject(..) should work in this case.

Gero

Am Mittwoch, 8. Juni 2016, 04:43:15 CEST schrieb Andrej Dundovic:

**Comment by lukasmerten** [comment]
Hi all,
self.reject() does not work. Attached you find an example.

The idea behind this is to create a module that writes out candidates for a list of given trajectory lengths. I will need this for a time evolution analysis of the phase space elements in the diffusion approach. 

How can I check if  the "-dirprot" command line option is set correctly? or can set it somehow manually?

Best, Lukas


[MyMaximumTrajectory.txt](https://github.com/CRPropa/CRPropa3/files/304804/MyMaximumTrajectory.txt)

**Comment by geromueller** [comment]
Hi,

i just pushed the fix.

Cheers
Gero

Am Mittwoch, 8. Juni 2016, 06:06:02 CEST schrieb Lukas Merten:

**Comment by lukasmerten** [comment]
Hi
Thanks Gero.
But at least for me it doesn't work. The error message changed but nevertheless something is weird.
I created a minimal example.
The error is as follows:

  File "MyMaximumTrajectory.py", line 31, in <module>
    maxTra.process(c)
  File "MyMaximumTrajectory.py", line 14, in process
    self.reject(c)
NotImplementedError: Wrong number or type of arguments for overloaded function 'AbstractCondition_reject'.
  Possible C/C++ prototypes are:
    crpropa::AbstractCondition::reject(crpropa::Candidate *) const
    crpropa::AbstractCondition::reject(crpropa::ref_ptr< crpropa::Candidate >) const

When I print type(c) I get <type 'CandidateRefPtr'>. Which at should be the right typeof argument for the process function. 

Appreciate any ideas.
Lukas
[MyMaximumTrajectory.txt](https://github.com/CRPropa/CRPropa3/files/305357/MyMaximumTrajectory.txt)

**Comment by TobiasWinchen** [comment]
Hi,

did you call the constructor of the base class in python, e.g.

def __init__(self):
	crpropa.Module.__init__(self)

I had a weired error once in a python module where I forgot this.

Cheers,


Tobi

**Comment by geromueller** [comment]
Hi,

actually it needs to be
	crpropa.AbstractCondition.__init__(self)
with Module.__init__ i get the same error as you  did.

Gero

Am Donnerstag, 9. Juni 2016, 02:11:39 CEST schrieb Tobias Winchen:

**Comment by TobiasWinchen** [comment]
Hi,

On Thursday 09 June 2016 02:14:36 you wrote:
> Hi,
> 
> actually it needs to be
> 	crpropa.AbstractCondition.__init__(self)
> with Module.__init__ i get the same error as you  did.

Yes, of course - I encountered the issue when coding a module a while ago. Of 
course the constructor of the specific base class has to be called when 
inheriting in python.

Cheers,


Tobi
