### ISSUE TITLE
HDF5 - Error

### ISSUE THREAD

**Issue by DavidWit** [CRPropa/CRPropa3#84]
```
Scanning dependencies of target healpix_base
[  1%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/error_handling.cc.o
[  2%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/geom_utils.cc.o
[  2%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_base.cc.o
[  3%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_tables.cc.o
[  4%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/pointing.cc.o
[  4%] Linking CXX static library libhealpix_base.a
[  4%] Built target healpix_base
Scanning dependencies of target kiss
[  5%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/logger.cpp.o
[  6%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/path.cpp.o
[  7%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/string.cpp.o
[  7%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/uuid.cpp.o
[  8%] Linking CXX static library libkiss.a
[  8%] Built target kiss
Scanning dependencies of target pugixml
[  9%] Building CXX object libs/pugixml/CMakeFiles/pugixml.dir/pugixml.cpp.o
[  9%] Linking CXX static library libpugixml.a
[  9%] Built target pugixml
Scanning dependencies of target HepPID
[  9%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleIDMethods.cc.o
[ 10%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleName.cc.o
[ 11%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/Version.cc.o
[ 11%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateEvtGen.cc.o
[ 12%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateGeanttoPDT.cc.o
[ 13%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateHerwig.cc.o
[ 14%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateIsajet.cc.o
[ 14%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDG.cc.o
[ 15%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDTtoGeant.cc.o
[ 16%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePythia.cc.o
[ 16%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateQQ.cc.o
[ 17%] Linking CXX static library libHepPID.a
[ 17%] Built target HepPID
Scanning dependencies of target sophia
[ 18%] Building Fortran object libs/sophia/CMakeFiles/sophia.dir/sophia_interface.f.o
[ 19%] Linking Fortran static library libsophia.a
[ 19%] Built target sophia
Scanning dependencies of target dint
[ 20%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/advance.cpp.o
[ 20%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/background.cpp.o
[ 21%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/binfread.cpp.o
[ 22%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/check.cpp.o
[ 22%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/cvector.cpp.o
[ 23%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/decay.cpp.o
[ 24%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/deriv.cpp.o
[ 25%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/error.cpp.o
[ 25%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/final.cpp.o
[ 26%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/fold.cpp.o
[ 27%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/frag.cpp.o
[ 27%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/gauleg.cpp.o
[ 28%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/inject.cpp.o
[ 29%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/io_util.cpp.o
[ 30%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/load.cpp.o
[ 30%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/math_util.cpp.o
[ 31%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prepare.cpp.o
[ 32%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prop_second.cpp.o
[ 32%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/rate.cpp.o
[ 33%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/spectrum.cpp.o
[ 34%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/sync.cpp.o
[ 35%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/vector.cpp.o
[ 35%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/DintEMCascade.cpp.o
[ 36%] Linking CXX static library libdint.a
[ 36%] Built target dint
Scanning dependencies of target eleca
[ 37%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Common.cpp.o
[ 37%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/EnergyLoss.cpp.o
[ 38%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Particle.cpp.o
[ 39%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Process.cpp.o
[ 40%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Propagation.cpp.o
[ 40%] Linking CXX static library libeleca.a
[ 40%] Built target eleca
Scanning dependencies of target crpropa
[ 41%] Building CXX object CMakeFiles/crpropa.dir/src/Random.cpp.o
[ 42%] Building CXX object CMakeFiles/crpropa.dir/src/Clock.cpp.o
[ 42%] Building CXX object CMakeFiles/crpropa.dir/src/ModuleList.cpp.o
[ 43%] Building CXX object CMakeFiles/crpropa.dir/src/Module.cpp.o
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/Candidate.cpp.o
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/EmissionMap.cpp.o
[ 45%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleState.cpp.o
[ 46%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleID.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleMass.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/ProgressBar.cpp.o
[ 48%] Building CXX object CMakeFiles/crpropa.dir/src/Cosmology.cpp.o
[ 49%] Building CXX object CMakeFiles/crpropa.dir/src/Source.cpp.o
[ 49%] Building CXX object CMakeFiles/crpropa.dir/src/Common.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonBackground.cpp.o
[ 51%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonPropagation.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/GridTools.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/XmlExecute.cpp.o
[ 53%] Building CXX object CMakeFiles/crpropa.dir/src/module/BreakCondition.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/Boundary.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/Observer.cpp.o
[ 55%] Building CXX object CMakeFiles/crpropa.dir/src/module/SimplePropagation.cpp.o
[ 56%] Building CXX object CMakeFiles/crpropa.dir/src/module/PropagationCK.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/ElectronPairProduction.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/NuclearDecay.cpp.o
[ 58%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoPionProduction.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoDisintegration.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/Redshift.cpp.o
[ 60%] Building CXX object CMakeFiles/crpropa.dir/src/module/Output.cpp.o
[ 61%] Building CXX object CMakeFiles/crpropa.dir/src/module/TextOutput.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputShell.cpp.o
[ 63%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputROOT.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputCRPropa2.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonOutput1D.cpp.o
[ 65%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonEleCa.cpp.o
[ 66%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMCascade.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMPairProduction.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMDoublePairProduction.cpp.o
[ 68%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMTripletPairProduction.cpp.o
[ 69%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMInverseComptonScattering.cpp.o
[ 69%] Building CXX object CMakeFiles/crpropa.dir/src/module/SynchrotronRadiation.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/module/Tools.cpp.o
[ 71%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticField.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticFieldGrid.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/JF12Field.cpp.o
[ 73%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/PshirkovField.cpp.o
[ 74%] Building CXX object CMakeFiles/crpropa.dir/src/Version.cpp.o
[ 74%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/MagneticLens.cpp.o
[ 75%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ModelMatrix.cpp.o
[ 76%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/Pixelization.cpp.o
[ 77%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ParticleMapsContainer.cpp.o
[ 77%] Linking CXX shared library libcrpropa.so
[ 77%] Built target crpropa
Scanning dependencies of target gtest
[ 78%] Building CXX object libs/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 79%] Linking CXX static library libgtest.a
[ 79%] Built target gtest
Scanning dependencies of target gtest_main
[ 79%] Building CXX object libs/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 80%] Linking CXX static library libgtest_main.a
[ 80%] Built target gtest_main
Scanning dependencies of target testMagneticField
[ 81%] Building CXX object CMakeFiles/testMagneticField.dir/test/testMagneticField.cpp.o
[ 81%] Linking CXX executable testMagneticField
libcrpropa.so: undefined reference to `H5Pclose'
libcrpropa.so: undefined reference to `H5Screate_simple'
libcrpropa.so: undefined reference to `H5Fcreate'
libcrpropa.so: undefined reference to `H5Tcreate'
libcrpropa.so: undefined reference to `H5Pset_chunk'
libcrpropa.so: undefined reference to `H5Sselect_hyperslab'
libcrpropa.so: undefined reference to `H5Dwrite'
libcrpropa.so: undefined reference to `H5Dset_extent'
libcrpropa.so: undefined reference to `H5Fclose'
libcrpropa.so: undefined reference to `H5Pset_layout'
libcrpropa.so: undefined reference to `H5Tinsert'
libcrpropa.so: undefined reference to `H5check_version'
libcrpropa.so: undefined reference to `H5Dget_space'
libcrpropa.so: undefined reference to `H5Sget_simple_extent_npoints'
libcrpropa.so: undefined reference to `H5T_NATIVE_UINT64_g'
libcrpropa.so: undefined reference to `H5Tclose'
libcrpropa.so: undefined reference to `H5Sclose'
libcrpropa.so: undefined reference to `H5T_NATIVE_DOUBLE_g'
libcrpropa.so: undefined reference to `H5Dclose'
libcrpropa.so: undefined reference to `H5open'
libcrpropa.so: undefined reference to `H5Dcreate2'
libcrpropa.so: undefined reference to `H5Pset_deflate'
libcrpropa.so: undefined reference to `H5Pcreate'
libcrpropa.so: undefined reference to `H5T_NATIVE_INT32_g'
libcrpropa.so: undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'
collect2: ld returned 1 exit status
make[2]: *** [testMagneticField] Error 1
make[1]: *** [CMakeFiles/testMagneticField.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by geromueller** [comment]
Please add the output of a *clean* cmake call.

Am Freitag, 17. Juni 2016, 05:24:03 CEST schrieb DavidWit:

**Comment by DavidWit** [comment]
Scanning dependencies of target eleca
[  1%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Common.cpp.o
[  1%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/EnergyLoss.cpp.o
[  2%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Particle.cpp.o
[  3%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Process.cpp.o
[  4%] Building CXX object libs/EleCa/CMakeFiles/eleca.dir/src/Propagation.cpp.o
[  4%] Linking CXX static library libeleca.a
[  4%] Built target eleca
Scanning dependencies of target gtest
[  5%] Building CXX object libs/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  6%] Linking CXX static library libgtest.a
[  6%] Built target gtest
Scanning dependencies of target gtest_main
[  6%] Building CXX object libs/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[  7%] Linking CXX static library libgtest_main.a
[  7%] Built target gtest_main
Scanning dependencies of target kiss
[  8%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/logger.cpp.o
[  9%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/path.cpp.o
[ 10%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/string.cpp.o
[ 10%] Building CXX object libs/kiss/CMakeFiles/kiss.dir/src/uuid.cpp.o
[ 11%] Linking CXX static library libkiss.a
[ 11%] Built target kiss
Scanning dependencies of target healpix_base
[ 12%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/error_handling.cc.o
[ 13%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/geom_utils.cc.o
[ 13%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_base.cc.o
[ 14%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/healpix_tables.cc.o
[ 15%] Building CXX object libs/healpix_base/CMakeFiles/healpix_base.dir/pointing.cc.o
[ 15%] Linking CXX static library libhealpix_base.a
[ 15%] Built target healpix_base
Scanning dependencies of target pugixml
[ 16%] Building CXX object libs/pugixml/CMakeFiles/pugixml.dir/pugixml.cpp.o
[ 16%] Linking CXX static library libpugixml.a
[ 16%] Built target pugixml
Scanning dependencies of target HepPID
[ 16%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleIDMethods.cc.o
[ 17%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/ParticleName.cc.o
[ 18%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/Version.cc.o
[ 18%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateEvtGen.cc.o
[ 19%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateGeanttoPDT.cc.o
[ 20%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateHerwig.cc.o
[ 21%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateIsajet.cc.o
[ 21%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDG.cc.o
[ 22%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePDTtoGeant.cc.o
[ 23%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translatePythia.cc.o
[ 23%] Building CXX object libs/HepPID/CMakeFiles/HepPID.dir/src/translateQQ.cc.o
[ 24%] Linking CXX static library libHepPID.a
[ 24%] Built target HepPID
Scanning dependencies of target sophia
[ 25%] Building Fortran object libs/sophia/CMakeFiles/sophia.dir/sophia_interface.f.o
[ 26%] Linking Fortran static library libsophia.a
[ 26%] Built target sophia
Scanning dependencies of target dint
[ 27%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/advance.cpp.o
[ 27%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/background.cpp.o
[ 28%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/binfread.cpp.o
[ 29%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/check.cpp.o
[ 29%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/cvector.cpp.o
[ 30%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/decay.cpp.o
[ 31%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/deriv.cpp.o
[ 32%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/error.cpp.o
[ 32%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/final.cpp.o
[ 33%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/fold.cpp.o
[ 34%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/frag.cpp.o
[ 34%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/gauleg.cpp.o
[ 35%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/inject.cpp.o
[ 36%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/io_util.cpp.o
[ 37%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/load.cpp.o
[ 37%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/math_util.cpp.o
[ 38%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prepare.cpp.o
[ 39%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/prop_second.cpp.o
[ 39%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/rate.cpp.o
[ 40%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/spectrum.cpp.o
[ 41%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/sync.cpp.o
[ 42%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/vector.cpp.o
[ 42%] Building CXX object libs/dint/CMakeFiles/dint.dir/src/DintEMCascade.cpp.o
[ 43%] Linking CXX static library libdint.a
[ 43%] Built target dint
Scanning dependencies of target crpropa
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/Random.cpp.o
[ 45%] Building CXX object CMakeFiles/crpropa.dir/src/Clock.cpp.o
[ 45%] Building CXX object CMakeFiles/crpropa.dir/src/ModuleList.cpp.o
[ 46%] Building CXX object CMakeFiles/crpropa.dir/src/Module.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/Candidate.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/EmissionMap.cpp.o
[ 48%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleState.cpp.o
[ 49%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleID.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleMass.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/ProgressBar.cpp.o
[ 51%] Building CXX object CMakeFiles/crpropa.dir/src/Cosmology.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/Source.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/Common.cpp.o
[ 53%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonBackground.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonPropagation.cpp.o
[ 55%] Building CXX object CMakeFiles/crpropa.dir/src/GridTools.cpp.o
[ 55%] Building CXX object CMakeFiles/crpropa.dir/src/XmlExecute.cpp.o
[ 56%] Building CXX object CMakeFiles/crpropa.dir/src/module/BreakCondition.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/Boundary.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/Observer.cpp.o
[ 58%] Building CXX object CMakeFiles/crpropa.dir/src/module/SimplePropagation.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/PropagationCK.cpp.o
[ 60%] Building CXX object CMakeFiles/crpropa.dir/src/module/ElectronPairProduction.cpp.o
[ 60%] Building CXX object CMakeFiles/crpropa.dir/src/module/NuclearDecay.cpp.o
[ 61%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoPionProduction.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoDisintegration.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/Redshift.cpp.o
[ 63%] Building CXX object CMakeFiles/crpropa.dir/src/module/Output.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/TextOutput.cpp.o
[ 65%] Building CXX object CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o
[ 65%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputShell.cpp.o
[ 66%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputROOT.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputCRPropa2.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonOutput1D.cpp.o
[ 68%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonEleCa.cpp.o
[ 69%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMCascade.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMPairProduction.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMDoublePairProduction.cpp.o
[ 71%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMTripletPairProduction.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMInverseComptonScattering.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/module/SynchrotronRadiation.cpp.o
[ 73%] Building CXX object CMakeFiles/crpropa.dir/src/module/Tools.cpp.o
[ 74%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticField.cpp.o
[ 75%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticFieldGrid.cpp.o
[ 75%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/JF12Field.cpp.o
[ 76%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/PshirkovField.cpp.o
[ 77%] Building CXX object CMakeFiles/crpropa.dir/src/Version.cpp.o
[ 77%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/MagneticLens.cpp.o
[ 78%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ModelMatrix.cpp.o
[ 79%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/Pixelization.cpp.o
[ 80%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ParticleMapsContainer.cpp.o
[ 80%] Linking CXX shared library libcrpropa.so
[ 80%] Built target crpropa
Scanning dependencies of target testMagneticField
[ 81%] Building CXX object CMakeFiles/testMagneticField.dir/test/testMagneticField.cpp.o
[ 81%] Linking CXX executable testMagneticField
libcrpropa.so: undefined reference to `H5Pclose'
libcrpropa.so: undefined reference to `H5Screate_simple'
libcrpropa.so: undefined reference to `H5Fcreate'
libcrpropa.so: undefined reference to `H5Tcreate'
libcrpropa.so: undefined reference to `H5Pset_chunk'
libcrpropa.so: undefined reference to `H5Sselect_hyperslab'
libcrpropa.so: undefined reference to `H5Dwrite'
libcrpropa.so: undefined reference to `H5Dset_extent'
libcrpropa.so: undefined reference to `H5Fclose'
libcrpropa.so: undefined reference to `H5Pset_layout'
libcrpropa.so: undefined reference to `H5Tinsert'
libcrpropa.so: undefined reference to `H5check_version'
libcrpropa.so: undefined reference to `H5Dget_space'
libcrpropa.so: undefined reference to `H5Sget_simple_extent_npoints'
libcrpropa.so: undefined reference to `H5T_NATIVE_UINT64_g'
libcrpropa.so: undefined reference to `H5Tclose'
libcrpropa.so: undefined reference to `H5Sclose'
libcrpropa.so: undefined reference to `H5T_NATIVE_DOUBLE_g'
libcrpropa.so: undefined reference to `H5Dclose'
libcrpropa.so: undefined reference to `H5open'
libcrpropa.so: undefined reference to `H5Dcreate2'
libcrpropa.so: undefined reference to `H5Pset_deflate'
libcrpropa.so: undefined reference to `H5Pcreate'
libcrpropa.so: undefined reference to `H5T_NATIVE_INT32_g'
libcrpropa.so: undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'
collect2: ld returned 1 exit status
make[2]: *** [testMagneticField] Error 1
make[1]: *** [CMakeFiles/testMagneticField.dir/all] Error 2
make: *** [all] Error 2

**Comment by geromueller** [comment]
I am sorry! I meant the output when you call "cmake -D..." itself, not the outout of the make command. Which OS are you using?

**Comment by DavidWit** [comment]
-- The Fortran compiler identification is GNU 4.4.6
-- The C compiler identification is GNU 4.4.6
-- The CXX compiler identification is GNU 4.4.6
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use --as-needed linker flags!
-- Build Type: Release
-- CRPropa version: 3.0-82-g3c97a4a 3c97a4a109d661b79b112c1a16c31ba32e17fffe refs/heads/master
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
Using provided EIGEN
-- ROOT: Found!
--   CFlags:      -pthread -m64 -I/root_v5.34.34/include/root
--   Libs:        -L/root_v5.34.34/lib/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP Fortran flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp 
-- Google perftools: NOT Found!
--   Include: GOOGLE_PERFTOOLS_INCLUDE_DIR-NOTFOUND
-- FFTW3 with single precision (FFTW3F): Found!
--   Include:     /usr/include
--   Library:     /usr/lib64/libfftw3f.so
-- Quimby: NOT Found!
--   Include:     QUIMBY_INCLUDE_DIR-NOTFOUND
--   Library:     QUIMBY_LIBRARY-NOTFOUND
-- SAGA: NOT Found!
--   Include:     SAGA_INCLUDE_DIR-NOTFOUND
--   Library:     SAGA_LIBRARY-NOTFOUND
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23")
-- muParser: Found!
--   Include:     /muparser-2.2.5/include
--   Library:     /muparser-2.2.5/lib/libmuparser.so
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3")
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib64/librt.so;/usr/lib64/libz.so;/usr/lib64/libdl.so;/usr/lib64/libm.so (found version "1.8.16")
-- Use absolute RPATH /CP3_170616/lib
-- Downloading data file from crpropa.desy.de ~ 35 MB
-- Extracting data file
-- Found SWIG: /usr/bin/swig (found version "1.3.40")
-- Python: Found!
--   Version:     2.7/27
--   Executeable: /Python-2.7.11/bin/python
--   Include:     /Python-2.7.11/include/python2.7
--   Library:     /Python-2.7.11/lib/python2.7/config/libpython2.7.a
--   Site-package directory: /CP3_170616/lib/python2.7/site-packages
-- Found numpy headers in /Python-2.7.11/lib/python2.7/site-packages/numpy/core/include
-- Configuring done
-- Generating done
-- Build files have been written

**Comment by DavidWit** [comment]
CentOS 6.3

**Comment by geromueller** [comment]
Hi. I can not reproduce this error. I installed CentOS in a VM. The only 2 differences i found:

-i have gcc 4.4.7 (you have 4.4.6) 
- the hdf5 detection line is different: "HDF5: Using hdf5 compiler wrapper to determine C configuration"
  -> how did you install hdf5?
  i uesed the epel version
Gero

**Comment by DavidWit** [comment]
I installed hdf5 using the source code.

**Comment by geromueller** [comment]
I still can not reproduce the problem. I installed hdf5 from source as well. Please clear the build directory and use -DCMAKE_PREFIX_PATH to point to the hdf5 files. Or, disable hdf5 if not required.
Otherwise i need a detailed list of commands you used to install the software (crpropa/hdf5 and dependencies)

**Comment by DavidWalz** [comment]
Hi David,
were you able to solve the problem or pinpoint the error?
Cheers, David

**Comment by DavidWalz** [comment]
closing for now
