### ISSUE TITLE
Typo in Wiki: Tutorials: Gal. Back. (1) ?

### ISSUE THREAD

**Issue by seanpquinn** [CRPropa/CRPropa3#90]
[http://nbviewer.jupyter.org/github/CRPropa/CRPropa3-notebooks/blob/master/galactic_backtracking/galactic_backtracking.v3.ipynb#(Optional)-Plotting](url)

```
# Angle definitions:
# CRPropa uses
#   longitude (phi) [-pi, pi], with +/-pi pointing in x-direction
```
+-pi point in -x, and phi=0 points in x. Can be verified using 

```
import numpy as np
import crpropa as crp
x=crp.Vector3d()
x.setRThetaPhi(1,np.pi/2,0)
x
```
Vector( 1, 0, 6.12323E-17 )

```
x.setRThetaPhi(1,np.pi/2,np.pi)
x
```
Vector( -1, 1.22465E-16, 6.12323E-17 )

```
x.setRThetaPhi(1,np.pi/2,-np.pi)
x
```
Vector( -1, 1.22465E-16, 6.12323E-17 )

**Comment by DavidWalz** [comment]
Thanks, fixed.
