### ISSUE TITLE
testCore

### ISSUE THREAD

**Issue by hossein-norouzi** [CRPropa/CRPropa3#91]
Hi I am being installed after all the problems we encountered how the other side.
make test
1-error:
 1/12 Test  #1: testCore ..........................***Failed    0.39 sec
2-I run it with command if a site is what the more complete the installation process is explained.

**Comment by geromueller** [comment]
Hello,

please attach the file from Testing/Temporary/LastTest.log

Gero

Am Samstag, 16. Juli 2016, 20:54:56 CEST schrieb hossein norouzi:

**Comment by hossein-norouzi** [comment]
Thank you, I'll solve this Mshklv What should I do when I can not use this software.
![screenshot from 2016-07-16 22-20-12](https://cloud.githubusercontent.com/assets/17244353/16899178/f29d3e0e-4bae-11e6-8695-4e5f6c4dfaf7.png)

**Comment by geromueller** [comment]
Hi, look at the tutorials: https://github.com/CRPropa/CRPropa3/wiki
