### ISSUE TITLE
error import crpropa

### ISSUE THREAD

**Issue by hossein-norouzi** [CRPropa/CRPropa3#92]
hi 
To install the module in Python section 6 Rahnmayym problem I'm grateful.

![screenshot from 2016-07-17 19-48-50](https://cloud.githubusercontent.com/assets/17244353/16905324/21123a3c-4c59-11e6-9ca0-cf122e8d7a40.png)

**Comment by geromueller** [comment]
Hello,

please have a look here: https://github.com/CRPropa/CRPropa3/wiki/Installation
