### ISSUE TITLE
Cascade Simulation

### ISSUE THREAD

**Issue by carlosblanco2718** [CRPropa/CRPropa3#93]
What is the correct way to propagate secondary gammas which are expected to undergo EMcascade? 

The examples referring to DintPropagation, EleCaPropagation, DintElcaPropagation do not seem to work for me. The errors reported from these are, in order:

NotImplementedError                       Traceback (most recent call last)
<ipython-input-6-106140b625df> in <module>()
      1 import crpropa
      2 
----> 3 crpropa.DintPropagation("photon_monoenergetic_source.dat", "spectrumDINT.dat", 0.1 * 1E-9 * crpropa.gauss, 4, 4)

NotImplementedError: Wrong number or type of arguments for overloaded function 'DintPropagation'.

----------------------------------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)
<ipython-input-7-33e3d55f73f0> in <module>()
      1 import crpropa
      2 
----> 3 crpropa.EleCaPropagation("photon_monoenergetic_source.dat", "eleca_photons.dat", True, 1E17*crpropa.eV, 0.1 * 1E-9 * crpropa.gauss)

AttributeError: 'module' object has no attribute 'EleCaPropagation'

----------------------------------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)
<ipython-input-8-e56d6725c1cf> in <module>()
      1 import crpropa
      2 
----> 3 crpropa.DintElcaPropagation("photon_monoenergetic_source.dat", "dintElca_spectrum.dat", True, .5 * crpropa.EeV, 0.1 * 1E-9 * crpropa.gauss)

AttributeError: 'module' object has no attribute 'DintElcaPropagation'

Additionally, is there a way to implement a user defined background radiation field?

**Comment by DavidWalz** [comment]
Hi,

Thanks for your notice. I just pushed the fix to the [notebook example](http://nbviewer.jupyter.org/github/CRPropa/CRPropa3-notebooks/blob/master/secondaries/photons.v3.ipynb), which should be visible in a couple of minutes. 

> What is the correct way to propagate secondary gammas which are expected to undergo EMcascade?

Apart from the options in the notebook example, you have two more options.

1) For high energy photons E > 10^17 eV you can add the interactions modules for EM particles to the normal simulation chain in whatever setup you prefer (1D, 3D, 4D), e.g.
```python
sim = ModuleList()
for background in (CMB, EBL_Gilmore12, URB_Protheroe96):
    sim.add( EMPairProduction(background) )
    sim.add( EMDoublePairProduction(background) )
    sim.add( EMTripletPairProduction(background) )
    sim.add( EMInverseComptonScattering(background) )
```
For lower energies the number of secondary particles will exceed your memory.

2) You can use the `EMCascade` module in the simulation chain. This soak up all EM particles and store it in form of energy - distance histograms. After the normal simulation you can then propagate these spectra in 1D using DINT, e.g.
```python
...
m = EMCascade()
sim.add( m )
...
sim.run()
m.runCascade('spectrum_EMparticles.txt')
```

> Additionally, is there a way to implement a user defined background radiation field?

All interaction rates on the various backgrounds are calculated beforehand using the scripts provided in CRPropa3-data. You would have to implement your background radiation field there `photonField.py`, produce the corresponding interaction rates and finally add the option to use them in CRPropa.

**Comment by carlosblanco2718** [comment]
Thanks very much for the swift response. Would it be possible to further explain the process of implementing a user defined radiation field?  Im trying to simulate VHE gammas traversing a galactic radiation field  and id like to run it through a cascade module. which would be the relevant interaction rates?

**Comment by DavidWalz** [comment]
With VHE you mean E < 10^14 eV?

Typically, the dominant interaction of photons with a background radiation field is pair production (Breit-Wheeler process). This interaction is implemented in `EMPairProduction`.
In order to compute the required interaction rates for a custom radiation field you could clone [CRPropa3-data](https://github.com/CRPropa/CRPropa3-data). There you would define your radiation field in `photonField.py` and compute the interaction rates with `calc_em.py`.

If you are also interested in secondary photons from the electromagnetic cascade you will also need to consider the interactions of VHE electrons with your radiation field: Triplet-pair production and inverse Compton scattering are implemented as interaction modules (see example above) and the corresponding interaction rates are calculated with `calc_em.py` as well.

If you try out this approach please keep us posted about your experiences.

**Comment by carlosblanco2718** [comment]
By VHE I mean energies on the order of 10^13 to 10^15 eV.

I have started implementing the ISRF in Porter and Strong, 2005 (Arxiv: astro-ph/0507119)

I added an EBL object to photonField.py and added this object to calc_em.py . Running photonField.py produces the following spectral comparison plot:
![iro](https://cloud.githubusercontent.com/assets/20825101/17718181/1aeaf536-63d8-11e6-9571-cb92fe2707cb.png)

Running calc_em.py produces the expected additional files in the data directory. I assume that I should place these text files in $CRPROPA_DIR/build/data. can you confirm? is there anything else I need to do in order to be able to run CRPropa in a way that will simulate cascades (including secondaries) on the newly implemented "IRB_PorterStrong" radiation field?

**Comment by DavidWalz** [comment]
Sorry for the late reply. The ISRF looks interesting.

>  I assume that I should place these text files in $CRPROPA_DIR/build/data.
Yes.

>  is there anything else I need to do in order to be able to run CRPropa in a way that will simulate cascades (including secondaries) on the newly implemented "IRB_PorterStrong" radiation field?

So your simulation might look like
```python
sim = ModuleList()
sim.add( EMPairProduction(IRB_PorterStrong) )
sim.add( EMDoublePairProduction(IRB_PorterStrong) )
sim.add( EMTripletPairProduction(IRB_PorterStrong) )
sim.add( EMInverseComptonScattering(IRB_PorterStrong) )
```

To do that you need to add IRB_PorterStrong in PhotonBackground.h. 
In EMPairProduction.cpp, EMDoublePairProduction for photons and EMTripletPairProduction and EMInverseComptonScattering for electrons you will need to add your field in the corresponding  setFieldMethods .
