### ISSUE TITLE
XML 1D outputs not working

### ISSUE THREAD

**Issue by rafaelab** [CRPropa/CRPropa3#94]
When trying to run the 1D examples in the xml test folder, the output file is empty.
There are no problems with the 3D examples.

**Comment by adundovi** [comment]
Some of Python examples don't work also (e.g. testNuclearDecay.py). I'll try to find some time to review and correct them.

**Comment by DavidWalz** [comment]
We should include the xml files and python tests in Travis-CI so see when a commit breaks one of the tests.

**Comment by adundovi** [comment]
I suppose then we need to rewrite these tests because most of them produce an image as a result, which is not suitable for testing, right?

**Comment by DavidWalz** [comment]
We can at least ascertain that the scripts are runnable.

**Comment by adundovi** [comment]
The old XML support should be dropped as we agreed during the Brussels' meeting.
