### ISSUE TITLE
make fails at  testGalacticMagneticLens

### ISSUE THREAD

**Issue by carlosblanco2718** [CRPropa/CRPropa3#97]
I get the following error when trying to 'make'.  using ubuntu 16.04 &

'The CXX compiler identification is GNU 5.4.0'

:~/Software/crpropa/CRPropa3/build$ make
[  4%] Built target healpix_base
[  8%] Built target kiss
[  9%] Built target pugixml
[ 17%] Built target HepPID
[ 18%] Building Fortran object libs/sophia/CMakeFiles/sophia.dir/sophia_interface.f.o
[ 19%] Linking Fortran static library libsophia.a
[ 19%] Built target sophia
[ 36%] Built target dint
[ 40%] Built target eleca
Scanning dependencies of target crpropa
[ 41%] Building CXX object CMakeFiles/crpropa.dir/src/Random.cpp.o
[ 42%] Building CXX object CMakeFiles/crpropa.dir/src/Clock.cpp.o
[ 42%] Building CXX object CMakeFiles/crpropa.dir/src/ModuleList.cpp.o
[ 43%] Building CXX object CMakeFiles/crpropa.dir/src/Module.cpp.o
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/Candidate.cpp.o
[ 44%] Building CXX object CMakeFiles/crpropa.dir/src/EmissionMap.cpp.o
[ 45%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleState.cpp.o
[ 46%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleID.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/ParticleMass.cpp.o
[ 47%] Building CXX object CMakeFiles/crpropa.dir/src/ProgressBar.cpp.o
[ 48%] Building CXX object CMakeFiles/crpropa.dir/src/Cosmology.cpp.o
[ 49%] Building CXX object CMakeFiles/crpropa.dir/src/Source.cpp.o
[ 49%] Building CXX object CMakeFiles/crpropa.dir/src/Common.cpp.o
[ 50%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonBackground.cpp.o
[ 51%] Building CXX object CMakeFiles/crpropa.dir/src/PhotonPropagation.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/GridTools.cpp.o
[ 52%] Building CXX object CMakeFiles/crpropa.dir/src/XmlExecute.cpp.o
[ 53%] Building CXX object CMakeFiles/crpropa.dir/src/module/BreakCondition.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/Boundary.cpp.o
[ 54%] Building CXX object CMakeFiles/crpropa.dir/src/module/Observer.cpp.o
[ 55%] Building CXX object CMakeFiles/crpropa.dir/src/module/SimplePropagation.cpp.o
[ 56%] Building CXX object CMakeFiles/crpropa.dir/src/module/PropagationCK.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/ElectronPairProduction.cpp.o
[ 57%] Building CXX object CMakeFiles/crpropa.dir/src/module/NuclearDecay.cpp.o
[ 58%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoPionProduction.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotoDisintegration.cpp.o
[ 59%] Building CXX object CMakeFiles/crpropa.dir/src/module/Redshift.cpp.o
[ 60%] Building CXX object CMakeFiles/crpropa.dir/src/module/Output.cpp.o
[ 61%] Building CXX object CMakeFiles/crpropa.dir/src/module/TextOutput.cpp.o
/home/carlos/Software/crpropa/CRPropa3/src/module/TextOutput.cpp: In member function ‘virtual void crpropa::TextOutput::process(crpropa::Candidate*) const’:
/home/carlos/Software/crpropa/CRPropa3/src/module/TextOutput.cpp:141:25: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
     c->getSerialNumber());
                         ^
/home/carlos/Software/crpropa/CRPropa3/src/module/TextOutput.cpp:166:64: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
   p += sprintf(buffer + p, "%10i\t", c->getSourceSerialNumber());
                                                                ^
/home/carlos/Software/crpropa/CRPropa3/src/module/TextOutput.cpp:193:32: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘uint64_t {aka long unsigned int}’ [-Wformat=]
     c->getCreatedSerialNumber());
                                ^
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/HDF5Output.cpp.o
[ 62%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputShell.cpp.o
[ 63%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputROOT.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/OutputCRPropa2.cpp.o
[ 64%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonOutput1D.cpp.o
[ 65%] Building CXX object CMakeFiles/crpropa.dir/src/module/PhotonEleCa.cpp.o
[ 66%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMCascade.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMPairProduction.cpp.o
[ 67%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMDoublePairProduction.cpp.o
[ 68%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMTripletPairProduction.cpp.o
[ 69%] Building CXX object CMakeFiles/crpropa.dir/src/module/EMInverseComptonScattering.cpp.o
[ 69%] Building CXX object CMakeFiles/crpropa.dir/src/module/SynchrotronRadiation.cpp.o
[ 70%] Building CXX object CMakeFiles/crpropa.dir/src/module/Tools.cpp.o
[ 71%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticField.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/MagneticFieldGrid.cpp.o
[ 72%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/JF12Field.cpp.o
[ 73%] Building CXX object CMakeFiles/crpropa.dir/src/magneticField/PshirkovField.cpp.o
[ 74%] Building CXX object CMakeFiles/crpropa.dir/src/Version.cpp.o
[ 74%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/MagneticLens.cpp.o
[ 75%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ModelMatrix.cpp.o
[ 76%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/Pixelization.cpp.o
[ 77%] Building CXX object CMakeFiles/crpropa.dir/src/magneticLens/ParticleMapsContainer.cpp.o
[ 77%] Linking CXX shared library libcrpropa.so
[ 77%] Built target crpropa
[ 79%] Built target gtest
[ 80%] Built target gtest_main
Scanning dependencies of target testGalacticMagneticLens
[ 81%] Building CXX object CMakeFiles/testGalacticMagneticLens.dir/test/testMagneticLens.cpp.o
[ 82%] Linking CXX executable testGalacticMagneticLens
libcrpropa.so: undefined reference to `is_directory(std::string const&)'
libcrpropa.so: undefined reference to `executable_path()'
libcrpropa.so: undefined reference to `mu::ParserBase::DefineConst(std::string const&, double)'
libcrpropa.so: undefined reference to `kiss::trim(std::string const&, std::string const&)'
libcrpropa.so: undefined reference to `kiss::ends_with(std::string const&, std::string const&)'
libcrpropa.so: undefined reference to `HepPID::particleName(int const&)'
libcrpropa.so: undefined reference to `eleca::Propagation::InitBkgArray(std::string const&)'
libcrpropa.so: undefined reference to `eleca::Propagation::ReadTables(std::string const&)'
libcrpropa.so: undefined reference to `mu::ParserBase::SetExpr(std::string const&)'
libcrpropa.so: undefined reference to `concat_path(std::string const&, std::string const&)'
libcrpropa.so: undefined reference to `DintEMCascade::DintEMCascade(int, int, std::string, double, double, double, double)'
libcrpropa.so: undefined reference to `mu::ParserBase::DefineVar(std::string const&, double*)'
collect2: error: ld returned 1 exit status
CMakeFiles/testGalacticMagneticLens.dir/build.make:108: recipe for target 'testGalacticMagneticLens' failed
make[2]: *** [testGalacticMagneticLens] Error 1
CMakeFiles/Makefile2:76: recipe for target 'CMakeFiles/testGalacticMagneticLens.dir/all' failed
make[1]: *** [CMakeFiles/testGalacticMagneticLens.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by TobiasWinchen** [comment]
Dear Carlos,

I was not able to reproduce the issue on a fresh installation of Ubuntu 16.04, it thus has likely to do something with your local environment. Please check any changes you made to your local environment, in particular if there is an old installation somewhere in your LD_LIBRARY_PATH. 

Cheers,


Tobi
