### ISSUE TITLE
Hard dependency on SWIG and python header

### ISSUE THREAD

**Issue by TobiasWinchen** [CRPropa/CRPropa3#98]
Contrary to the claim in the wiki, installation without swig and python won't work. On an almost  minimum debian I get:

`[...]`
` Downloading data file from crpropa.desy.de ~ 35 MB`
`-- Extracting data file`
`CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 `
`(message):`
`  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)`
`Call Stack (most recent call first):`
 ` /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 `
`(_FPHSA_FAILURE_MESSAGE)`
 ` /usr/share/cmake-3.5/Modules/FindSWIG.cmake:75 `
`(FIND_PACKAGE_HANDLE_STANDARD_ARGS)`
 ` CMakeLists.txt:338 (FIND_PACKAGE)`

and after installing SWIG

` [...]`
`  -- Extracting data file`
`  -- Found SWIG: /usr/bin/swig3.0 (found version "3.0.7") `
`CMake Error at python/Python.cmake:19 (MESSAGE):`
`  Python.h not found`
`Call Stack (most recent call first):`
`  CMakeLists.txt:339 (include)`

after installing python-dev it works fine. We should either fix this or 'officially' make SWIG and python hard dependencies.

**Comment by adundovi** [comment]
Cannot reproduce. Tried in minimal Ubuntu 14.04, Debian Stretch and Fedora 24 inside LXC (without python-dev and SWIG). In all cases I ended up with CRPropa without the python library compiled.

In addition to the base installation, I have installed the following packages:
- Fedora:  ``dnf install git gcc gcc-c++ gcc-gfortran make cmake``
- Debian: ```apt-get install g++ gfortran cmake gcc wget zip``
- Ubuntu: ``apt-get install g++ gfortran cmake gcc git``

You should probably try to run cmake with:
```
cmake .. -DENABLE_PYTHON=OFF
```

**Comment by TobiasWinchen** [comment]
On Thursday 18 August 2016 03:44:14 Andrej Dundovic wrote:

> In addition to the base installation, I have installed the following
> packages: - Fedora:  ``dnf install git gcc gcc-c++ gcc-gfortran make
> cmake`` - Debian: ```apt-get install g++ gfortran cmake gcc wget zip``
> - Ubuntu: ``apt-get install g++ gfortran cmake gcc git``
> 
> You should probably try to run cmake with:
> ```
> cmake .. -DENABLE_PYTHON=OFF
> ```

CMake should not fail, but disable python (with a warning message), if Python 
bindings cannot be build.

**Comment by adundovi** [comment]
Yes, I've already done this check in the last commit.

On 18 August 2016 13:25:46 CEST, Tobias Winchen <notifications@github.com> wrote:
>On Thursday 18 August 2016 03:44:14 Andrej Dundovic wrote:
>
>> In addition to the base installation, I have installed the following
>> packages: - Fedora:  ``dnf install git gcc gcc-c++ gcc-gfortran make
>> cmake`` - Debian: ```apt-get install g++ gfortran cmake gcc wget
>zip``
>> - Ubuntu: ``apt-get install g++ gfortran cmake gcc git``
>> 
>> You should probably try to run cmake with:
>> ```
>> cmake .. -DENABLE_PYTHON=OFF
>> ```
>
>CMake should not fail, but disable python (with a warning message), if
>Python 
>bindings cannot be build.
>
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/CRPropa/CRPropa3/issues/98#issuecomment-240696094

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
